//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     ALP_MaterialFlowNode.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/libalpopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace ALP
    {
        class MaterialFlowNode;
    }
    class NXObject;
    namespace ALP
    {
        class _MaterialFlowNodeBuilder;
        class MaterialFlowNodeImpl;
        /** Represents Material Flow information  <br> To create a new instance of this class, use @link NXOpen::ALP::ALPManager::CreateMaterialFlowNode  NXOpen::ALP::ALPManager::CreateMaterialFlowNode @endlink  <br> 
         <br>  Created in NX2406.0.0.  <br>  
        */
        class ALPOPENCPPEXPORT  MaterialFlowNode : public NXOpen::NXObject
        {
            private: MaterialFlowNodeImpl * m_materialflownode_impl;
            private: friend class  _MaterialFlowNodeBuilder;
            protected: MaterialFlowNode();
            public: ~MaterialFlowNode();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
