//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_PmiIdSymbol.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_IdSymbol.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Annotations
    {
        class PmiIdSymbol;
    }
    namespace Annotations
    {
        class IdSymbol;
    }
    namespace Annotations
    {
        class _PmiIdSymbolBuilder;
        class PmiIdSymbolImpl;
        /** Represents an PMI ID symbol  <br> To create or edit an instance of this class, use @link NXOpen::Annotations::PmiIdSymbolBuilder  NXOpen::Annotations::PmiIdSymbolBuilder @endlink  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class NXOPENCPP_ANNOTATIONSEXPORT  PmiIdSymbol : public NXOpen::Annotations::IdSymbol
        {
            private: PmiIdSymbolImpl * m_pmiidsymbol_impl;
            private: friend class  _PmiIdSymbolBuilder;
            protected: PmiIdSymbol();
            public: ~PmiIdSymbol();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
