//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CableRouter_Managed_Cable.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CableRouter_Managed_DataTypes.hxx>
#include <NXOpen/CableRouter_Managed_Device.hxx>
#include <NXOpen/CableRouter_Managed_Node.hxx>
#include <NXOpen/CableRouter_Managed_SegmentPath.hxx>
#include <NXOpen/CableRouter_Managed_BaseData.hxx>
#include <NXOpen/libnxopencpp_cablerouter_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CableRouter
    {
        namespace Managed
        {
            class Cable;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class BaseData;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class Device;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class Node;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class SegmentPath;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class _CableBuilder;
            class CableImpl;
            /** Represents the physical and logical cables in the NX Cable Router application.  <br> This class must be created by loading cables in the session from Teamcenter.  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_CABLEROUTEREXPORT  Cable : public NXOpen::CableRouter::Managed::BaseData
            {
                private: CableImpl * m_cable_impl;
                private: friend class  _CableBuilder;
                protected: Cable();
                public: ~Cable();
                /** This method returns @link NXOpen::CableRouter::Managed::SegmentPath NXOpen::CableRouter::Managed::SegmentPath@endlink  set saved for this cable 
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXOpen::CableRouter::Managed::SegmentPath *> GetSegmentPaths
                (
                );
                /**Returns  the logical @link NXOpen::CableRouter::Managed::Cable NXOpen::CableRouter::Managed::Cable@endlink  identifier 
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString LogicalID
                (
                );
                /**Returns  the starting @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  for this object 
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::Device * StartDevice
                (
                );
                /**Returns  the ending @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  for this object
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::Device * EndDevice
                (
                );
                /**Returns  the from @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  for this object
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::Node * FromNode
                (
                );
                /**Returns  the to @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  for this object
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::Node * ToNode
                (
                );
                /**Returns  the to route status for this object
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::CableRouterManagedCableRoutestatus RouteStatus
                (
                );
                /**Returns  the length correction 
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double LengthCorrection
                (
                );
                /**Returns  the from extra length
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double FromExtraLength
                (
                );
                /**Returns  the to extra length
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double ToExtraLength
                (
                );
                /**Returns  the length of the path
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double Length
                (
                );
                /**Returns  the minimum length of the path
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double MinimumLength
                (
                );
                /**Returns  the maximum length of the path
                 <br>  Created in NX2412.0.0.  <br>  
                 <br> License requirements : None */
                public: double MaximumLength
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
