//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CableRouter_Managed_SettingsBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CableRouter_Managed_DataTypes.hxx>
#include <NXOpen/LineColorFontWidthBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/TextColorFontWidthBuilder.hxx>
#include <NXOpen/libnxopencpp_cablerouter_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CableRouter
    {
        namespace Managed
        {
            class SettingsBuilder;
        }
    }
    class Builder;
    class LineColorFontWidthBuilder;
    class NXColor;
    class TextColorFontWidthBuilder;
    namespace CableRouter
    {
        namespace Managed
        {
            class _SettingsBuilderBuilder;
            class SettingsBuilderImpl;
            /** Builder class to modify the settings of the current session.  <br> To create a new instance of this class, use @link NXOpen::CableRouter::CableRouterCollection::CreateManagedSettingsBuilder  NXOpen::CableRouter::CableRouterCollection::CreateManagedSettingsBuilder @endlink  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_CABLEROUTEREXPORT  SettingsBuilder : public NXOpen::Builder
            {
                private: SettingsBuilderImpl * m_settingsbuilder_impl;
                private: friend class  _SettingsBuilderBuilder;
                protected: SettingsBuilder();
                public: ~SettingsBuilder();

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool FitOnSelection
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetFitOnSelection
                (
                    bool fitOnSelection /** fitonselection */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool DrawLabelAlongLine
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetDrawLabelAlongLine
                (
                    bool drawLabelAlongLine /** drawlabelalongline */ 
                );

                /// \endcond 
                /**Returns  a flag for whether the amount of labels drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool LimitLabelsShown
                (
                );
                /**Sets  a flag for whether the amount of labels drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLimitLabelsShown
                (
                    bool shouldObjectsBeLimited /** shouldobjectsbelimited */ 
                );
                /**Returns  a number for max number of labels to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int MaxLabelsShown
                (
                );
                /**Sets  a number for max number of labels to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetMaxLabelsShown
                (
                    int numberOfLabels /** numberoflabels */ 
                );
                /**Returns  a flag for whether the amount of @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool LimitNodesShown
                (
                );
                /**Sets  a flag for whether the amount of @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLimitNodesShown
                (
                    bool shouldObjectsBeLimited /** shouldobjectsbelimited */ 
                );
                /**Returns  a number for max number of @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int MaxNodesShown
                (
                );
                /**Sets  a number for max number of @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetMaxNodesShown
                (
                    int numberOfNode /** numberofnode */ 
                );
                /**Returns  a flag for whether the amount of @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool LimitDevicesShown
                (
                );
                /**Sets  a flag for whether the amount of @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  drawn to screen should be limited 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLimitDevicesShown
                (
                    bool shouldObjectsBeLimited /** shouldobjectsbelimited */ 
                );
                /**Returns  a number for max number of @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int MaxDevicesShown
                (
                );
                /**Sets  a number for max number of @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  to draw
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetMaxDevicesShown
                (
                    int numberOfDevices /** numberofdevices */ 
                );
                /**Returns  a number for the layer to draw the generated objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int LayerNumber
                (
                );
                /**Sets  a number for the layer to draw the generated objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLayerNumber
                (
                    int layerNumber /** layernumber */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowNodes
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowNodes
                (
                    bool showNodes /** shownodes */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowNodeLabels
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::Node NXOpen::CableRouter::Managed::Node@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowNodeLabels
                (
                    bool showNodeLabels /** shownodelabels */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowSegments
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowSegments
                (
                    bool showSegments /** showsegments */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowSegmentLabels
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowSegmentLabels
                (
                    bool showSegmentLabels /** showsegmentlabels */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowDevices
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowDevices
                (
                    bool showDevices /** showdevices */ 
                );
                /**Returns  a flag for whether @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ShowDeviceLabels
                (
                );
                /**Sets  a flag for whether @link NXOpen::CableRouter::Managed::Device NXOpen::CableRouter::Managed::Device@endlink  labels are displayed 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetShowDeviceLabels
                (
                    bool showDeviceLabels /** showdevicelabels */ 
                );
                /**Returns  a set of values for color, width, and line font of the nodal network 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::LineColorFontWidthBuilder * BasicDisplayProperties
                (
                );
                /**Returns  a set of values for the color of the selected @link NXOpen::CableRouter::Managed::Cable NXOpen::CableRouter::Managed::Cable@endlink 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * CableSelectionColor
                (
                );
                /**Sets  a set of values for the color of the selected @link NXOpen::CableRouter::Managed::Cable NXOpen::CableRouter::Managed::Cable@endlink 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetCableSelectionColor
                (
                    NXOpen::NXColor * cableSelectionColor /** cableselectioncolor */ 
                );
                /**Returns  a set of values for the color of the @link NXOpen::CableRouter::Managed::Cable NXOpen::CableRouter::Managed::Cable@endlink  selected by the automatic route process
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * AutomaticRouteColor
                (
                );
                /**Sets  a set of values for the color of the @link NXOpen::CableRouter::Managed::Cable NXOpen::CableRouter::Managed::Cable@endlink  selected by the automatic route process
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetAutomaticRouteColor
                (
                    NXOpen::NXColor * automaticCableSelectionColor /** automaticcableselectioncolor */ 
                );
                /**Returns  the color of an available @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * AvailableColor
                (
                );
                /**Sets  the color of an available @link NXOpen::CableRouter::Managed::LineSegment NXOpen::CableRouter::Managed::LineSegment@endlink 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetAvailableColor
                (
                    NXOpen::NXColor * availableColor /** availablecolor */ 
                );
                /**Returns  the color for start objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * StartObjectColor
                (
                );
                /**Sets  the color for start objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetStartObjectColor
                (
                    NXOpen::NXColor * startObjectColor /** startobjectcolor */ 
                );
                /**Returns  the color for end objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * EndObjectColor
                (
                );
                /**Sets  the color for end objects
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetEndObjectColor
                (
                    NXOpen::NXColor * endObjectColor /** endobjectcolor */ 
                );
                /**Returns  a set of values for color, width, and font of the nodal network labels 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::TextColorFontWidthBuilder * LabelTextProperties
                (
                );
                /**Returns  a number for the font size of the nodal network labels
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double LabelFontSize
                (
                );
                /**Sets  a number for the font size of the nodal network labels
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLabelFontSize
                (
                    double selectionColor /** selectioncolor */ 
                );

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXString> GetRuleSets
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetRuleSets
                (
                    const std::vector<NXString> & listBoxStylesList /** Rule set names to add */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString StyleTitleString
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetStyleTitleString
                (
                    const NXString & fontSize /** fontsize */ 
                );
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void SetStyleTitleString
                (
                    const char * fontSize /** fontsize */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes ObjectTypeEnum
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetObjectTypeEnum
                (
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** objecttype */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int PropertyEnum
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetPropertyEnum
                (
                    int propertyType /** propertytype */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int ComparisonEnum
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetComparisonEnum
                (
                    int comparisonType /** comparisontype */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString RuleValueString
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetRuleValueString
                (
                    const NXString & ruleValue /** rulevalue */ 
                );
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void SetRuleValueString
                (
                    const char * ruleValue /** rulevalue */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double RuleValueNumeric
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetRuleValueNumeric
                (
                    double ruleValue /** rulevalue */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * RuleColor
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetRuleColor
                (
                    NXOpen::NXColor * ruleColor /** rulecolor */ 
                );

                /// \endcond 
                /**Returns  the file name of the data set from the native file system
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString FileName
                (
                );
                /**Sets  the file name of the data set from the native file system
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetFileName
                (
                    const NXString & filename /** filename */ 
                );
                /**Sets  the file name of the data set from the native file system
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void SetFileName
                (
                    const char * filename /** filename */ 
                );

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void CreateRule
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void CreateNumericRule
                (
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsNumericcomparison comparison /** Comparison to use for this rule */,
                    double value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void CreateStringRule
                (
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsStringcomparison comparison /** Comparison to use for this rule */,
                    const NXString & value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void CreateStringRule
                (
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsStringcomparison comparison /** Comparison to use for this rule */,
                    const char * value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void EditExistingRule
                (
                    int index /** Rule index to modify */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void EditExistingNumericRule
                (
                    int index /** Rule Index to modify */,
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this Rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsNumericcomparison comparison /** Comparison to use for this rule */,
                    double value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void EditExistingStringRule
                (
                    int index /** Rule Index to modify */,
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsStringcomparison comparison /** Comparison to use for this rule */,
                    const NXString & value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void EditExistingStringRule
                (
                    int index /** Rule Index to modify */,
                    NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes objectType /** Object type that will be affected by this rule */,
                    int propertyChoice /** Property that will be affected by this rule */,
                    NXOpen::CableRouter::Managed::CableRouterManagedSettingsStringcomparison comparison /** Comparison to use for this rule */,
                    const char * value /** Value to use for this rule */,
                    NXOpen::NXColor * color /** Color of the objects that match this rule */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void DeleteRule
                (
                    int index /** Rule index to delete */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void CreateRuleSet
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void DeleteRuleSet
                (
                    const NXString & selected /** Name of the rule set to delete */
                );
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void DeleteRuleSet
                (
                    const char * selected /** Name of the rule set to delete */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXString> GetRuleStrings
                (
                    int index /** Rule to examine */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int GetNumberOfActiveRules
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CableRouter::Managed::CableRouterManagedObjecttypes GetActiveRuleObjectType
                (
                    int index /** Rule to examine in the active rule set*/
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int GetActiveRuleProperty
                (
                    int index /** Rule to examine in the active rule set*/
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int GetActiveRuleComparison
                (
                    int index /** Rule to examine in the active rule set*/
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double GetActiveRuleNumericValue
                (
                    int index /** Rule to examine in the active rule set*/,
                    bool* success /** Returns if a numeric value was found */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString GetActiveRuleStringValue
                (
                    int index /** Rule to examine in the active rule set*/,
                    bool* success /** Returns if a string value was found */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: int GetActiveRuleColor
                (
                    int index /** Rule to examine in the active rule set*/
                );

                /// \endcond 
                /** Loads the rules and rule sets from the provided json string
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void LoadFromJSON
                (
                    const NXString & json /** The json value to build the rules and rule sets from */
                );
                /** Loads the rules and rule sets from the provided json string
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void LoadFromJSON
                (
                    const char * json /** The json value to build the rules and rule sets from */
                );

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: NXString CreateJSON
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool HasValidActiveRuleSet
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: bool IsValidRuleSetName
                (
                    const NXString & name /** The rule set name to check */
                );
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                bool IsValidRuleSetName
                (
                    const char * name /** The rule set name to check */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString GetActiveRuleSetName
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetActiveRuleSet
                (
                    const NXString & name /** The name of the rule set to try to make active */
                );
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                void SetActiveRuleSet
                (
                    const char * name /** The name of the rule set to try to make active */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXString> GetRuleSetNames
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: bool MoveRuleToBottom
                (
                    int row /** The rule index to move */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: bool MoveRuleToTop
                (
                    int row /** The rule index to move */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: bool MoveRuleUp
                (
                    int row /** The rule index to move */
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /** This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: bool MoveRuleDown
                (
                    int row /** The rule index to move */
                );

                /// \endcond 
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
