//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_SMTCSYSDataOnQueryCurve.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class SMTCSYSDataOnQueryCurve;
    }
    class CoordinateSystem;
    namespace CAE
    {
        class _SMTCSYSDataOnQueryCurveBuilder;
        class SMTCSYSDataOnQueryCurveImpl;
        /**Represents a @link NXOpen::CAE::SMTCSYSDataOnQueryCurve NXOpen::CAE::SMTCSYSDataOnQueryCurve@endlink . <br> An instance of this class can not be obtained  <br> 
         <br>  Created in NX2412.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  SMTCSYSDataOnQueryCurve : public NXOpen::TaggedObject
        {
            /** CSYS definition type. */
            public: enum CSYSDefinitionType
            {
                CSYSDefinitionTypeUseSummation/** use summation */ ,
                CSYSDefinitionTypeSpecifyCSYS/** specify csys */ ,
                CSYSDefinitionTypeGlobal/** global */ 
            };

            private: SMTCSYSDataOnQueryCurveImpl * m_smtcsysdataonquerycurve_impl;
            private: friend class  _SMTCSYSDataOnQueryCurveBuilder;
            protected: SMTCSYSDataOnQueryCurve();
            public: ~SMTCSYSDataOnQueryCurve();
            /** Initialtion the CSYS data for query curve in Nodal Force Reports On Path Dialog functionlaity.
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void InitCSYSData
            (
            );
            /** Gets the CSYS definition type at the given query curve point. 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType GetCSYSDefinitionTypeAtCurvePoint
            (
                int pointIndex /** pointindex */ 
            );
            /** Sets the CSYS definition type at the given query curve point. 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetCSYSDefinitionTypeAtCurvePoint
            (
                int pointIndex /** pointindex */ ,
                NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType csysDefinitionType /** csysdefinitiontype */ 
            );
            /** Gets the CSYS at given query curve point.
                    
                    If the CSYS definition type at this point is not @link NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType::SpecifyCSYS NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType::SpecifyCSYS@endlink , null tag is returned.
                     
                    
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CoordinateSystem * GetSpecifyCSYSAtCurvePoint
            (
                int pointIndex /** pointindex */ 
            );
            /** Sets the CSYS at given query curve point when the CSYS definition type is @link NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType::SpecifyCSYS NXOpen::CAE::SMTCSYSDataOnQueryCurve::CSYSDefinitionType::SpecifyCSYS@endlink . 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetSpecifyCSYSAtCurvePoint
            (
                int pointIndex /** pointindex */ ,
                NXOpen::CoordinateSystem * csysTag /** csystag */ 
            );
            /**Returns  the point number of the query curve. 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: int PointNumber
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
