//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAM_MachineCycleManagerBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_cam_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAM
    {
        class MachineCycleManagerBuilder;
    }
    class Builder;
    namespace CAM
    {
        class _MachineCycleManagerBuilderBuilder;
        class MachineCycleManagerBuilderImpl;
        /** Machine Cycle Manager builder  <br> To create a new instance of this class, use @link NXOpen::CAM::OperationCollection::CreateMachineCycleManagerBuilder  NXOpen::CAM::OperationCollection::CreateMachineCycleManagerBuilder @endlink  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_CAMEXPORT  MachineCycleManagerBuilder : public NXOpen::Builder
        {
            /** the button action type */
            public: enum ButtonActionType
            {
                ButtonActionTypeNone/** none */ ,
                ButtonActionTypeUserFunction/** user function */ ,
                ButtonActionTypeExecute/** execute */ ,
                ButtonActionTypeShellExecute/** shell execute */ 
            };

            private: MachineCycleManagerBuilderImpl * m_machinecyclemanagerbuilder_impl;
            private: friend class  _MachineCycleManagerBuilderBuilder;
            protected: MachineCycleManagerBuilder();
            public: ~MachineCycleManagerBuilder();
            /**Returns  the machine cycle file to be processed 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString CycleFile
            (
            );
            /**Sets  the machine cycle file to be processed 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetCycleFile
            (
                const NXString & filename /** filename */ 
            );
            /**Sets  the machine cycle file to be processed 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetCycleFile
            (
                const char * filename /** filename */ 
            );
            /**Returns  the folder location to place the processed machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString OutputFolder
            (
            );
            /**Sets  the folder location to place the processed machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetOutputFolder
            (
                const NXString & foldername /** foldername */ 
            );
            /**Sets  the folder location to place the processed machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetOutputFolder
            (
                const char * foldername /** foldername */ 
            );
            /**Returns  the display name of the machine cycle 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString DisplayName
            (
            );
            /**Sets  the display name of the machine cycle 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetDisplayName
            (
                const NXString & displayName /** displayname */ 
            );
            /**Sets  the display name of the machine cycle 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetDisplayName
            (
                const char * displayName /** displayname */ 
            );
            /**Returns  the description of the machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Description
            (
            );
            /**Sets  the description of the machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetDescription
            (
                const NXString & description /** description */ 
            );
            /**Sets  the description of the machine cycle file 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetDescription
            (
                const char * description /** description */ 
            );
            /** Process the machine cycle file and place it in the output folder 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void Publish
            (
            );
            /**Returns  the licensing sold to IDs of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXString SoldToIDs
            (
            );
            /**Sets  the licensing sold to IDs of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetSoldToIDs
            (
                const NXString & soldToIDs /** soldtoids */ 
            );
            /**Sets  the licensing sold to IDs of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetSoldToIDs
            (
                const char * soldToIDs /** soldtoids */ 
            );
            /**Returns  the licensing expiration date of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXString ExpirationDate
            (
            );
            /**Sets  the licensing expiration date of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void SetExpirationDate
            (
                const NXString & expirationDate /** expirationdate */ 
            );
            /**Sets  the licensing expiration date of the machine cycle file 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void SetExpirationDate
            (
                const char * expirationDate /** expirationdate */ 
            );
            /** Perform custom user button action 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            public: void PerformCustomAction
            (
                NXOpen::CAM::MachineCycleManagerBuilder::ButtonActionType actionType /** actiontype */ ,
                const NXString & function /** function */ ,
                const NXString & command /** command */ ,
                const NXString & filespec /** filespec */ ,
                const NXString & parameters /** parameters */ ,
                const NXString & directory /** directory */ 
            );
            /** Perform custom user button action 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : nx_cam_met_omp_auth (" NX CAM Metrology On Machine Probing Author") */
            void PerformCustomAction
            (
                NXOpen::CAM::MachineCycleManagerBuilder::ButtonActionType actionType /** actiontype */ ,
                const char * function /** function */ ,
                const char * command /** command */ ,
                const char * filespec /** filespec */ ,
                const char * parameters /** parameters */ ,
                const char * directory /** directory */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
