//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DesignSimulation_ResultMeasureBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/libnxopencpp_designsimulation_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DesignSimulation
    {
        class ResultMeasureBuilder;
    }
    class Builder;
    class ScCollector;
    namespace DesignSimulation
    {
        class _ResultMeasureBuilderBuilder;
        class ResultMeasureBuilderImpl;
        /**
            Represents a @link NXOpen::DesignSimulation::ResultMeasure NXOpen::DesignSimulation::ResultMeasure@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::DesignSimulation::Study::CreateResultMeasureBuilder  NXOpen::DesignSimulation::Study::CreateResultMeasureBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        ResultValue </term> <description> 
         
        Maximum </description> </item> 

        </list> 

         <br>  Created in NX2306.0.0.  <br>  
        */
        class NXOPENCPP_DESIGNSIMULATIONEXPORT  ResultMeasureBuilder : public NXOpen::Builder
        {
            /** Result type option */
            public: enum ResultTypeOption
            {
                ResultTypeOptionDisplacement/** displacement */ ,
                ResultTypeOptionStress/** stress */ ,
                ResultTypeOptionSafetyFactor/** safety factor */ ,
                ResultTypeOptionThermal/** thermal */ 
            };

            /** Result component type option */
            public: enum ResultComponentOption
            {
                ResultComponentOptionDisplacementMagnitude/** displacement magnitude */ ,
                ResultComponentOptionDisplacementWorstInXYZ/** displacement worst in xyz */ ,
                ResultComponentOptionDisplacementX/** displacement x */ ,
                ResultComponentOptionDisplacementY/** displacement y */ ,
                ResultComponentOptionDisplacementZ/** displacement z */ ,
                ResultComponentOptionStressVonMises/** stress von mises */ ,
                ResultComponentOptionStressWorstPrincipal/** stress worst principal */ ,
                ResultComponentOptionSafetyFactorVonMises/** safety factor von mises */ ,
                ResultComponentOptionTemperature/** temperature */ 
            };

            /** Result value option */
            public: enum ResultValueOption
            {
                ResultValueOptionMinimum/** minimum */ ,
                ResultValueOptionMaximum/** maximum */ 
            };

            private: ResultMeasureBuilderImpl * m_resultmeasurebuilder_impl;
            private: friend class  _ResultMeasureBuilderBuilder;
            protected: ResultMeasureBuilder();
            public: ~ResultMeasureBuilder();
            /**Returns  the selected entity
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * SelectedEntities
            (
            );
            /**Returns  the result measure name 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Name
            (
            );
            /**Sets  the result measure name 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetName
            (
                const NXString & resultMeasureName /** resultmeasurename */ 
            );
            /**Sets  the result measure name 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            void SetName
            (
                const char * resultMeasureName /** resultmeasurename */ 
            );
            /**Returns  the result type 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ResultMeasureBuilder::ResultTypeOption ResultType
            (
            );
            /**Sets  the result type 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetResultType
            (
                NXOpen::DesignSimulation::ResultMeasureBuilder::ResultTypeOption resultType /** resulttype */ 
            );
            /**Returns  the result component 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ResultMeasureBuilder::ResultComponentOption ResultComponent
            (
            );
            /**Sets  the result component 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetResultComponent
            (
                NXOpen::DesignSimulation::ResultMeasureBuilder::ResultComponentOption resultComponentType /** resultcomponenttype */ 
            );
            /**Returns  the oepration type 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ResultMeasureBuilder::ResultValueOption ResultValue
            (
            );
            /**Sets  the oepration type 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetResultValue
            (
                NXOpen::DesignSimulation::ResultMeasureBuilder::ResultValueOption resultValueType /** resultvaluetype */ 
            );
            /**Returns  the flag indicating whether the object uses an user-defined name 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool UserSetName
            (
            );
            /**Sets  the flag indicating whether the object uses an user-defined name 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetUserSetName
            (
                bool userSetName /** usersetname */ 
            );
            /**Returns  the label PMI 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: bool LabelPMI
            (
            );
            /**Sets  the label PMI 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetLabelPMI
            (
                bool labelPMI /** labelpmi */ 
            );
            /**Returns  the number of Natural Frequencies computed for Natural Frequencies analysis type.
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int NaturalFrequenciesCount
            (
            );
            /**Returns  the index of the Natural Frequency to display for Natural Frequencies analysis type.
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: int NaturalFrequencyIndex
            (
            );
            /**Sets  the index of the Natural Frequency to display for Natural Frequencies analysis type.
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_perf_predictor (" Performance Predictor") */
            public: void SetNaturalFrequencyIndex
            (
                int resultModeIndex /** resultmodeindex */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
