//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Document_PageBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Document_BaseObjectBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libdocumentopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Document
    {
        class PageBuilder;
    }
    namespace Document
    {
        class BaseObjectBuilder;
    }
    namespace Document
    {
        class SelectContextObject;
    }
    namespace Document
    {
        class _PageBuilderBuilder;
        class PageBuilderImpl;
        /** Represents the PageBuilder.
              <br> To create a new instance of this class, use @link NXOpen::Document::PageCollection::CreatePageBuilder  NXOpen::Document::PageCollection::CreatePageBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class DOCUMENTOPENCPPEXPORT  PageBuilder : public NXOpen::Document::BaseObjectBuilder
        {
            private: PageBuilderImpl * m_pagebuilder_impl;
            private: friend class  _PageBuilderBuilder;
            protected: PageBuilder();
            public: ~PageBuilder();
            /**Returns the height 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: double Height
            (
            );
            /**Sets the height 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: void SetHeight
            (
                double height /** height */ 
            );
            /**Returns the width 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: double Width
            (
            );
            /**Sets the width 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: void SetWidth
            (
                double width /** width */ 
            );
            /**Returns  the reference element selection item 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Document::SelectContextObject * ReferenceElement
            (
            );
            /**Returns  the template 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXString TemplateFile
            (
            );
            /**Sets  the template 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetTemplateFile
            (
                const NXString & templateName /** templatename */ 
            );
            /**Sets  the template 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            void SetTemplateFile
            (
                const char * templateName /** templatename */ 
            );
            /**Returns the apply to all 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool ApplyToAllPages
            (
            );
            /**Sets the apply to all 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetApplyToAllPages
            (
                bool applyToAllPages /** applytoallpages */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
