//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_RotatingPointer.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_BodyFeature.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class RotatingPointer;
    }
    namespace Features
    {
        class BodyFeature;
    }
    namespace Features
    {
        class _RotatingPointerBuilder;
        class RotatingPointerImpl;
        /** Represents a rotating pointer feature  <br> To create or edit an instance of this class, use @link NXOpen::Features::RotatingPointerBuilder  NXOpen::Features::RotatingPointerBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  RotatingPointer : public NXOpen::Features::BodyFeature
        {
            private: RotatingPointerImpl * m_rotatingpointer_impl;
            private: friend class  _RotatingPointerBuilder;
            protected: RotatingPointer();
            public: ~RotatingPointer();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
