//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_StructureDesign_SplitRailBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace StructureDesign
        {
            class SplitRailBuilder;
        }
    }
    class Builder;
    class Expression;
    class SelectTaggedObjectList;
    namespace Features
    {
        namespace StructureDesign
        {
            class _SplitRailBuilderBuilder;
            class SplitRailBuilderImpl;
            /**
                Represents a @link Features::StructureDesign::SplitRailBuilder Features::StructureDesign::SplitRailBuilder@endlink  builder
                 <br> To create a new instance of this class, use @link NXOpen::Features::StructureDesignCollection::CreateStructureDesignSplitRailBuilder  NXOpen::Features::StructureDesignCollection::CreateStructureDesignSplitRailBuilder @endlink  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  SplitRailBuilder : public NXOpen::Builder
            {
                private: SplitRailBuilderImpl * m_splitrailbuilder_impl;
                private: friend class  _SplitRailBuilderBuilder;
                protected: SplitRailBuilder();
                public: ~SplitRailBuilder();
                /**Returns  the select rail part 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObjectList * SelectRailPart
                (
                );
                /**Returns  the select stanchion part 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObjectList * SelectStanchionPart
                (
                );
                /**Returns  the offset distance in the Z direction 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Offset
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
