//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_BlendCurveOnSurfaceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class BlendCurveOnSurfaceBuilder;
    }
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    class Point;
    class SelectCurveList;
    namespace Features
    {
        class _BlendCurveOnSurfaceBuilderBuilder;
        class BlendCurveOnSurfaceBuilderImpl;
        /**
            Represents a @link Features::BlendCurveOnSurface Features::BlendCurveOnSurface@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::FreeformCurveCollection::CreateBlendCurveOnSurfaceBuilder  NXOpen::Features::FreeformCurveCollection::CreateBlendCurveOnSurfaceBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        AssociativeToggle </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        BlendOption </term> <description> 
         
        Fillet </description> </item> 

        <item><term> 
         
        BlendRadiusDim.Value </term> <description> 
         
        10 (millimeters part), 0.4 (inches part) </description> </item> 

        <item><term> 
         
        ChamferAngle.Value </term> <description> 
         
        45 </description> </item> 

        <item><term> 
         
        ChamferOption </term> <description> 
         
        Symmetric </description> </item> 

        <item><term> 
         
        Distance1.Value </term> <description> 
         
        10 (millimeters part), 0.4 (inches part) </description> </item> 

        <item><term> 
         
        Distance2.Value </term> <description> 
         
        10 (millimeters part), 0.4 (inches part) </description> </item> 

        <item><term> 
         
        TrimCurve </term> <description> 
         
        1 </description> </item> 

        </list> 

         <br>  Created in NX2406.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  BlendCurveOnSurfaceBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** Dialog options for blend Creation */
            public: enum BlendOptions
            {
                BlendOptionsFillet/** Fillet - Creates an arc between the two curves on surface */,
                BlendOptionsChamfer/** Chamfer - Creates a chamfer between the two curves on surface */
            };

            /** Dialog options for chamfer creation */
            public: enum ChamferOptions
            {
                ChamferOptionsSymmetric/** Symmetric - specify one distance */,
                ChamferOptionsAsymmetric/** Asymmetric - specify two distances */,
                ChamferOptionsOffsetandAngle/** OffsetandAngle - specify offset distance and angle */
            };

            private: BlendCurveOnSurfaceBuilderImpl * m_blendcurveonsurfacebuilder_impl;
            private: friend class  _BlendCurveOnSurfaceBuilderBuilder;
            protected: BlendCurveOnSurfaceBuilder();
            public: ~BlendCurveOnSurfaceBuilder();
            /**Returns  the blend options that specify what type of blend is to be created, fillet or chamfer 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::BlendCurveOnSurfaceBuilder::BlendOptions BlendOption
            (
            );
            /**Sets  the blend options that specify what type of blend is to be created, fillet or chamfer 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetBlendOption
            (
                NXOpen::Features::BlendCurveOnSurfaceBuilder::BlendOptions blendOption /** blendoption */ 
            );
            /**Returns  the target curves 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectCurveList * TargetCurves
            (
            );
            /**Returns  the trim curve toggle 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : None */
            public: bool TrimCurve
            (
            );
            /**Sets  the trim curve toggle 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTrimCurve
            (
                bool trimCurve /** trimcurve */ 
            );
            /**Returns  the blend radius dim 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * BlendRadiusDim
            (
            );
            /** TODO: fill in a description for this 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void ComplementArc
            (
            );
            /**Returns  the chamfer options that specify what type of chamfer is to be created 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::BlendCurveOnSurfaceBuilder::ChamferOptions ChamferOption
            (
            );
            /**Sets  the chamfer options that specify what type of chamfer is to be created 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetChamferOption
            (
                NXOpen::Features::BlendCurveOnSurfaceBuilder::ChamferOptions chamferOption /** chamferoption */ 
            );
            /**Returns  the distance for line 1 for Symmetric, Asymmetric, and for OffSet and Angle Chamfer
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Distance1
            (
            );
            /**Returns  the distance for line 2 for Asymmetric Chamfer 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Distance2
            (
            );
            /**Returns  the angle for Offset and Angle Chamfer 
             <br>  Created in NX2412.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * ChamferAngle
            (
            );
            /**Returns  the specify point 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * SpecifyPoint
            (
            );
            /**Sets  the specify point 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSpecifyPoint
            (
                NXOpen::Point * specifyPoint /** specifypoint */ 
            );
            /**Returns  the associative toggle 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : None */
            public: bool AssociativeToggle
            (
            );
            /**Sets  the associative toggle 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAssociativeToggle
            (
                bool associativeToggle /** associativetoggle */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
