//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_StructuralElementCopyBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/ErrorList.hxx>
#include <NXOpen/Features_ShipDesign_StructuralElementCopyTargetListItemBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/IAttributeSourceObjectBuilder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class StructuralElementCopyBuilder;
        }
    }
    class ErrorList;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class StructuralElementCopyTargetListItemBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class StructuralElementCopyTargetListItemBuilderList;
        }
    }
    class IAttributeSourceObjectBuilder;
    class NXObject;
    class SelectNXObjectList;
    namespace Features
    {
        namespace ShipDesign
        {
            class _StructuralElementCopyBuilderBuilder;
            class StructuralElementCopyBuilderImpl;
            /**  Represents a @link NXOpen::Features::ShipDesign::StructuralElementCopyBuilder NXOpen::Features::ShipDesign::StructuralElementCopyBuilder@endlink   
                         It is used in Ship Building Application. The operation copies a structural element to 
                         a different (and compatible) plane.
                     <br> To create a new instance of this class, use @link NXOpen::Features::ShipCollection::CreateStructuralElementCopyBuilder  NXOpen::Features::ShipCollection::CreateStructuralElementCopyBuilder @endlink  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  StructuralElementCopyBuilder : public NXOpen::Features::FeatureBuilder, public virtual NXOpen::IAttributeSourceObjectBuilder
            {
                private: StructuralElementCopyBuilderImpl * m_structuralelementcopybuilder_impl;
                private: friend class  _StructuralElementCopyBuilderBuilder;
                protected: StructuralElementCopyBuilder();
                public: ~StructuralElementCopyBuilder();
                /**Returns   @brief  Source structural element  

                 
                            
                                The source structural element that will be copied.
                             
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: NXOpen::SelectNXObjectList * SourceStructuralElements
                (
                );
                /**Returns   @brief  Copy target list  

                 
                            
                                The list of target planes (and a name for each new structural element) where the source structural element will be copied.
                             
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::StructuralElementCopyTargetListItemBuilderList * StructuralElementCopyTargetList
                (
                );
                /** Create single structural element copy target list item. 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: NXOpen::Features::ShipDesign::StructuralElementCopyTargetListItemBuilder * CreateStructuralElementCopyTargetListItem
                (
                );
                /**  Auto assigns the attributes for a given array of objects and returns an array of objects that failed to auto assign.
                   
                 <br>  Created in NX8.5.0.  <br>  
                 <br> License requirements : None */
                public: virtual NXOpen::ErrorList * AutoAssignAttributes
                (
                    const std::vector<NXOpen::NXObject *> & objects /** objects */ 
                );
                /**  Auto assigns the attributes for a given object and returns an array of objects that failed to auto assign.
                        properties needs to be created using @link CreateAttributeTitleToNamingPatternMap CreateAttributeTitleToNamingPatternMap@endlink 
                   
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual NXOpen::ErrorList * AutoAssignAttributesWithNamingPattern
                (
                    const std::vector<NXOpen::NXObject *> & objects /** objects */ ,
                    const std::vector<NXOpen::NXObject *> & properties /** properties */ 
                );
                /** Creates a map object of attribute titles to their corresponding naming pattern 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual NXOpen::NXObject * CreateAttributeTitleToNamingPatternMap
                (
                    std::vector<NXString> & attributeTitles /** attributetitles */ ,
                    std::vector<NXString> & titlePatterns /** titlepatterns */ 
                );
                /** Get the available item revision naming rule revision ids for the given logical object.
                        Logical object should be created using @link NXOpen::PDM::PartOperationBuilder::CreateLogicalObjects NXOpen::PDM::PartOperationBuilder::CreateLogicalObjects@endlink .
                        The valid revision ids will be stored in revOptions and can be set using @link NXOpen::AttributePropertiesBaseBuilder NXOpen::AttributePropertiesBaseBuilder@endlink .
                        For usage, set Title = "DB_PART_REV" and StringValue = revOptions(index). 
                    
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual void GetItemRevisionNamingRules
                (
                    NXOpen::NXObject * object /** object */ ,
                    std::vector<NXString> & revOptions /** revoptions */ 
                );
                /** Get the available item naming rule patterns for the given logical object. 
                        Logical object should be created using @link NXOpen::PDM::PartOperationBuilder::CreateLogicalObjects NXOpen::PDM::PartOperationBuilder::CreateLogicalObjects@endlink .
                        The valid naming rule patterns will be stored in patternList. For usage, set attributeTitles = "DB_PART_NO" and titlePatterns = patternList(index) for @link CreateAttributeTitleToNamingPatternMap CreateAttributeTitleToNamingPatternMap@endlink .
                    
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual void GetItemNamingRulePatterns
                (
                    NXOpen::NXObject * object /** object */ ,
                    std::vector<NXString> & patternList /** patternlist */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
