//--------------------------------------------------------------------------
// Copyright 2025 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Inspector_Characteristic.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/libinspectoropencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Inspector
    {
        class Characteristic;
    }
    class NXObject;
    namespace Inspector
    {
        class _CharacteristicBuilder;
        class CharacteristicImpl;
        /** Represents a Characteristic object. 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class INSPECTOROPENCPPEXPORT  Characteristic : public NXOpen::NXObject
        {
            private: CharacteristicImpl * m_characteristic_impl;
            private: friend class  _CharacteristicBuilder;
            protected: Characteristic();
            public: ~Characteristic();
            /**Returns  the universally unique identifier. This is also referred to as the characteristic base identifier.
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_inspector (" NX Inspector Workflow for defining Characteristics") */
            public: NXString UniversallyUniqueIdentifier
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
