//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     LineDesigner_ConnectionCreatorBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/liblinedesigneropencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace LineDesigner
    {
        class ConnectionCreatorBuilder;
    }
    class Builder;
    class Expression;
    class SelectDisplayableObject;
    namespace LineDesigner
    {
        class _ConnectionCreatorBuilderBuilder;
        class ConnectionCreatorBuilderImpl;
        /** 
            
            
            
            
            
             <br> To create a new instance of this class, use @link NXOpen::LineDesigner::LineDesignerManager::CreateConnectionCreatorBuilder  NXOpen::LineDesigner::LineDesignerManager::CreateConnectionCreatorBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        ConectionOffset.Value (deprecated) </term> <description> 
         
        0 (millimeters part), 0 (inches part) </description> </item> 

        <item><term> 
         
        ConectionType </term> <description> 
         
        MoveAndConnect </description> </item> 

        <item><term> 
         
        ExpressionString </term> <description> 
         
        0.0 </description> </item> 

        </list> 

         <br>  Created in NX9.0.0.  <br>  
        */
        class LINEDESIGNEROPENCPPEXPORT  ConnectionCreatorBuilder : public NXOpen::Builder
        {
            /** This enum is providing possible connection types    */
            public: enum ConnectionType
            {
                ConnectionTypeMoveAndConnect/** move and connect */ ,
                ConnectionTypeMove/** move */ ,
                ConnectionTypeConnect/** connect */ 
            };

            private: ConnectionCreatorBuilderImpl * m_connectioncreatorbuilder_impl;
            private: friend class  _ConnectionCreatorBuilderBuilder;
            protected: ConnectionCreatorBuilder();
            public: ~ConnectionCreatorBuilder();
            /**Returns  the source connector used in connection
             <br>  Created in NX9.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: NXOpen::SelectDisplayableObject * SourceConnector
            (
            );
            /**Returns  the target connector used in connection 
             <br>  Created in NX9.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: NXOpen::SelectDisplayableObject * TargetConnector
            (
            );
            /**Returns  the current connection type 
             <br>  Created in NX9.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: NXOpen::LineDesigner::ConnectionCreatorBuilder::ConnectionType ConectionType
            (
            );
            /**Sets  the current connection type 
             <br>  Created in NX9.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: void SetConectionType
            (
                NXOpen::LineDesigner::ConnectionCreatorBuilder::ConnectionType conectionType /** conectiontype */ 
            );
            /**Returns  the connection offset 
             <br>  @deprecated Deprecated in NX2206.0.0.  The offset value will be retrieved from the UIComp itself. <br>  

             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: NX_DEPRECATED("Deprecated in NX2206.0.0.  The offset value will be retrieved from the UIComp itself.") NXOpen::Expression * ConectionOffset
            (
            );
            /**Returns  the connection expression RHS string 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: NXString ExpressionString
            (
            );
            /**Sets  the connection expression RHS string 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            public: void SetExpressionString
            (
                const NXString & expressionString /** expressionstring */ 
            );
            /**Sets  the connection expression RHS string 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : ld_line_designer ("FULL LINE DESIGNER") */
            void SetExpressionString
            (
                const char * expressionString /** expressionstring */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
