//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MechanicalRouting_CablewayPatternBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Routing_AttributeHolder.hxx>
#include <NXOpen/Routing_RouteObjectCollector.hxx>
#include <NXOpen/libnxopencpp_mechanicalrouting_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MechanicalRouting
    {
        class CablewayPatternBuilder;
    }
    class Builder;
    namespace Routing
    {
        class AttributeHolder;
    }
    namespace Routing
    {
        class RouteObjectCollector;
    }
    namespace MechanicalRouting
    {
        class _CablewayPatternBuilderBuilder;
        class CablewayPatternBuilderImpl;
        /** Builder class for Cableway Interface Node command.  <br> To create a new instance of this class, use @link NXOpen::MechanicalRouting::BuilderFactory::CreateCablewayPatternBuilder  NXOpen::MechanicalRouting::BuilderFactory::CreateCablewayPatternBuilder @endlink  <br> 
         <br>  Created in NX2406.0.0.  <br>  
        */
        class NXOPENCPP_MECHANICALROUTINGEXPORT  CablewayPatternBuilder : public NXOpen::Builder
        {
            /** Determines how to choose which pattern to assign. */
            public: enum CablewayPatternMethod
            {
                CablewayPatternMethodNone/** No Pattern. */,
                CablewayPatternMethodSpecifiedPattern/** Pattern selected from Specify Item dialog */
            };

            private: CablewayPatternBuilderImpl * m_cablewaypatternbuilder_impl;
            private: friend class  _CablewayPatternBuilderBuilder;
            protected: CablewayPatternBuilder();
            public: ~CablewayPatternBuilder();
            /**Returns  the object used for selection of path segments 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: NXOpen::Routing::RouteObjectCollector * PathSelection
            (
            );
            /** The button to handle the flip state 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: void Flip
            (
            );
            /** Gets the attribute holder for library defined attributes on cableway pattern to be applied 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: NXOpen::Routing::AttributeHolder * GetAttributeHolder
            (
            );
            /** Resets the attribute holder for library defined attributes for cableway pattern attribute holder
                        This API is recommended to be used before assigning attributes onto builder so as to ensure cableway pattern apply operation to function correctly 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: void ResetAttributeHolder
            (
            );
            /**Returns  the method to determine which pattern to assign. 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: NXOpen::MechanicalRouting::CablewayPatternBuilder::CablewayPatternMethod CablewayPatternMethodType
            (
            );
            /**Sets  the method to determine which pattern to assign. 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: void SetCablewayPatternMethodType
            (
                NXOpen::MechanicalRouting::CablewayPatternBuilder::CablewayPatternMethod method /** method */ 
            );
            /**Returns  
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: NXString CablewayPatternPartNumber
            (
            );
            /** 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: void SetFlip
            (
                bool flip /** flip */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
