//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MechanicalRouting_CablewayElectricalTopologyPathBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Routing_RouteObjectCollector.hxx>
#include <NXOpen/libnxopencpp_mechanicalrouting_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MechanicalRouting
    {
        class CablewayElectricalTopologyPathBuilder;
    }
    class Builder;
    namespace Routing
    {
        class RouteObjectCollector;
    }
    namespace MechanicalRouting
    {
        class _CablewayElectricalTopologyPathBuilderBuilder;
        class CablewayElectricalTopologyPathBuilderImpl;
        /** Builder for marking paths as Electrical Topology Paths.  <br> To create a new instance of this class, use @link NXOpen::MechanicalRouting::BuilderFactory::CreateCablewayElectricalTopologyPathBuilder  NXOpen::MechanicalRouting::BuilderFactory::CreateCablewayElectricalTopologyPathBuilder @endlink  <br> 
         <br>  Created in NX2406.0.0.  <br>  
        */
        class NXOPENCPP_MECHANICALROUTINGEXPORT  CablewayElectricalTopologyPathBuilder : public NXOpen::Builder
        {
            private: CablewayElectricalTopologyPathBuilderImpl * m_cablewayelectricaltopologypathbuilder_impl;
            private: friend class  _CablewayElectricalTopologyPathBuilderBuilder;
            protected: CablewayElectricalTopologyPathBuilder();
            public: ~CablewayElectricalTopologyPathBuilder();
            /**Returns  the selected stock components. These can have bare paths.
                        If any stock components have regular stock, then they will always be deleted from 
                        the stock component part before marking the stock components as cableway Electrical Topology Path. 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: NXOpen::Routing::RouteObjectCollector * StockComponents
            (
            );
            /**Returns  whether to mark or unmark the selected stock components as cableway Electrical Topology Path. 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: bool ElectricalTopologyPath
            (
            );
            /**Sets  whether to mark or unmark the selected stock components as cableway Electrical Topology Path. 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : routing_cabling ("Routing Cabling") */
            public: void SetElectricalTopologyPath
            (
                bool isElectricalTopologyPath /** iselectricaltopologypath */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
