//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MotionInternal.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class MotionInternal;
    class DebugSession;
    class DisplayableObject;
    namespace Motion
    {
        class MotionSolution;
    }
    class MotionInternalImpl;

    /// \cond NX_NO_DOC 
    /** Represents class containing APIs used for Autotest generation on motion Intent.
    This class should not be made available to customers
     <br> To obtain an instance of this class, refer to @link NXOpen::DebugSession  NXOpen::DebugSession @endlink  <br> 
     <br>  Created in NX7.5.0.  <br>  
    */
    class NXOPENDEBUGSESSIONCPPEXPORT  MotionInternal
    {
        private: MotionInternalImpl * m_motioninternal_impl;
        private: NXOpen::DebugSession* m_owner;
        /// \cond NX_NO_DOC 
        public: explicit MotionInternal(NXOpen::DebugSession *owner);


        /// \endcond 
        public: 
        /**Returns the tag of this object.  */
        tag_t Tag() const; 
        public: ~MotionInternal();

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : mechanisms ("MECHANISMS") */
        public: void RunCosimWithSimulinkHost
        (
            NXOpen::Motion::MotionSolution * solution /** solution */ 
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX2312.0.0.  <br>  
         <br> License requirements : None */
        public: void PrintTransformationInView
        (
            int viewIndex /** view port index */,
            NXOpen::DisplayableObject * objectTag /** objecttag */ 
        );

        /// \endcond 
    }; //lint !e1712 default constructor not defined for class  


    /// \endcond 
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
