//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     PartMfg_SaveStructureBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libpartmfgopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace PartMfg
    {
        class SaveStructureBuilder;
    }
    class Builder;
    namespace PartMfg
    {
        class _SaveStructureBuilderBuilder;
        class SaveStructureBuilderImpl;
        /** Builder class  <br> To create a new instance of this class, use @link NXOpen::PartMfg::BopPart::CreateSaveStructureBuilder  NXOpen::PartMfg::BopPart::CreateSaveStructureBuilder @endlink  <br> 
         <br>  Created in NX2406.0.0.  <br>  
        */
        class PARTMFGOPENCPPEXPORT  SaveStructureBuilder : public NXOpen::Builder
        {
            private: SaveStructureBuilderImpl * m_savestructurebuilder_impl;
            private: friend class  _SaveStructureBuilderBuilder;
            protected: SaveStructureBuilder();
            public: ~SaveStructureBuilder();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
