//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     SketchIssue.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Sketch.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class SketchIssue;
    class NXObject;
    class _SketchIssueBuilder;
    class SketchIssueImpl;
    /** Represents a sketch checking issue.  <br> To create an instance of this class refer to @link NXOpen::SketchFindIssuesBuilder NXOpen::SketchFindIssuesBuilder@endlink   <br> 
     <br>  Created in NX2412.0.0.  <br>  
    */
    class NXOPENCPPEXPORT  SketchIssue : public NXOpen::NXObject
    {
        /** the various types of issues. */
        public: enum Type
        {
            TypeAlmostHorizontal/** The line is almost horizontal. */,
            TypeAlmostConnected/** A vertex or point is close to another disconnected vertex or point. */,
            TypeAlmostTangent/** Curves are not far apart and almost tangent. */,
            TypeAlmostTangentAtVertex/** Curves are almost tangent where they are connected. */,
            TypeAlmostParallel/** Lines are almost parallel. */,
            TypeOverlapping/** A curve is exactly and completely overlapping with another curve. */,
            TypeTinyCurve/** The curve is very small. */,
            TypeAlmostConcentric/** The centers of arcs or circles are almost coincident. */,
            TypeAlmostEqualRadius/** The radii of circles are almost equal. */,
            TypeAlmostEqualLength/** The length of lines are almost equal. */,
            TypeAlmostPerpendicular/** Intersecting lines are almost perpendicular. */,
            TypeAlmostCollinear/** Parallel curves are almost collinear. */,
            TypeAlmostPointOnCurve/** A vertex or point is close to another disconnected curve. */,
            TypeAlmostVertical/** The line is almost vertical. */
        };

        private: SketchIssueImpl * m_sketchissue_impl;
        private: friend class  _SketchIssueBuilder;
        protected: SketchIssue();
        public: ~SketchIssue();
        /**Returns  the type of issue. 
         <br>  Created in NX2412.0.0.  <br>  
         <br> License requirements : None */
        public: NXOpen::SketchIssue::Type IssueType
        (
        );
        /**Returns  the flag indicating whether the issue is ignored. 
         <br>  Created in NX2412.0.0.  <br>  
         <br> License requirements : None */
        public: bool IsIgnored
        (
        );
        /** Ignore the issue so it is no longer displayed. To remove the ignore state, simply delete the issue. If 
                the issue still applies, a new @link NXOpen::SketchIssue NXOpen::SketchIssue@endlink  will be created the next time 
                issues are found using the @link NXOpen::SketchFindIssuesBuilder NXOpen::SketchFindIssuesBuilder@endlink . 
         <br>  Created in NX2412.0.0.  <br>  
         <br> License requirements : None */
        public: void IgnoreIssue
        (
        );
        /** Returns the geometry associated with the issue. 
         <br>  Created in NX2412.0.0.  <br>  
         <br> License requirements : None */
        public: std::vector<NXOpen::Sketch::SketchGeometry> GetGeometry
        (
        );
    };
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
