//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Vsa_FixturePlaneFeatureBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_vsa_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Vsa
    {
        class FixturePlaneFeatureBuilder;
    }
    class Builder;
    namespace Vsa
    {
        class _FixturePlaneFeatureBuilderBuilder;
        class FixturePlaneFeatureBuilderImpl;
        /** Represents a @link NXOpen::Vsa::FixturePlaneFeatureBuilder NXOpen::Vsa::FixturePlaneFeatureBuilder@endlink   <br> To create a new instance of this class, use @link NXOpen::Vsa::VsaManager::CreatePlaneFeatureBuilder  NXOpen::Vsa::VsaManager::CreatePlaneFeatureBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        DoubleKurtosisForm </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        DoubleKurtosisLoc </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        DoubleKurtosisSize </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        DoubleSkewnessForm </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        DoubleSkewnessLoc </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        DoubleSkewnessSize </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FormType </term> <description> 
         
        Normal </description> </item> 

        <item><term> 
         
        I </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        J </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        K </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        LocType </term> <description> 
         
        Normal </description> </item> 

        <item><term> 
         
        SizeType </term> <description> 
         
        Normal </description> </item> 

        <item><term> 
         
        X </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        Y </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        Z </term> <description> 
         
        0 </description> </item> 

        </list> 

         <br>  Usable only on Windows <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_VSAEXPORT  FixturePlaneFeatureBuilder : public NXOpen::Builder
        {
            /**
                     This enum is for Size distribution type.
                    */
            public: enum APISizeType
            {
                APISizeTypeNormal/** normal */ ,
                APISizeTypeUniform/** uniform */ ,
                APISizeTypeExtreme/** extreme */ ,
                APISizeTypePearson/** pearson */ ,
                APISizeTypeTrapeziodal/** trapeziodal */ 
            };

            /**
                    This enum is for Location distribution type.
                    */
            public: enum APILocType
            {
                APILocTypeNormal/** normal */ ,
                APILocTypeUniform/** uniform */ ,
                APILocTypeExtreme/** extreme */ ,
                APILocTypePearson/** pearson */ ,
                APILocTypeTrapeziodal/** trapeziodal */ 
            };

            /**
                    This enum is for Form distribution type.
                    */
            public: enum APIFormType
            {
                APIFormTypeNormal/** normal */ ,
                APIFormTypeUniform/** uniform */ ,
                APIFormTypeExtreme/** extreme */ ,
                APIFormTypePearson/** pearson */ ,
                APIFormTypeTrapeziodal/** trapeziodal */ 
            };

            private: FixturePlaneFeatureBuilderImpl * m_fixtureplanefeaturebuilder_impl;
            private: friend class  _FixturePlaneFeatureBuilderBuilder;
            protected: FixturePlaneFeatureBuilder();
            public: ~FixturePlaneFeatureBuilder();
            /**Returns  the name 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Name
            (
            );
            /**Sets  the name 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetName
            (
                const NXString & name /** name */ 
            );
            /**Sets  the name 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            void SetName
            (
                const char * name /** name */ 
            );
            /**Returns  the string description 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Description
            (
            );
            /**Sets  the string description 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDescription
            (
                const NXString & stringDescription /** stringdescription */ 
            );
            /**Sets  the string description 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            void SetDescription
            (
                const char * stringDescription /** stringdescription */ 
            );
            /**Returns  the x 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double X
            (
            );
            /**Sets  the x 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetX
            (
                double x /** x */ 
            );
            /**Returns  the y 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double Y
            (
            );
            /**Sets  the y 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetY
            (
                double y /** y */ 
            );
            /**Returns  the z 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double Z
            (
            );
            /**Sets  the z 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetZ
            (
                double z /** z */ 
            );
            /**Returns  the i 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double I
            (
            );
            /**Sets  the i 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetI
            (
                double i /** i */ 
            );
            /**Returns  the j 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double J
            (
            );
            /**Sets  the j 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetJ
            (
                double j /** j */ 
            );
            /**Returns  the k 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double K
            (
            );
            /**Sets  the k 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetK
            (
                double k /** k */ 
            );
            /**Returns  the length Width
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double Width
            (
            );
            /**Sets  the length Width
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetWidth
            (
                double width /** width */ 
            );
            /**Returns  the length Length
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double Length
            (
            );
            /**Sets  the length Length
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetLength
            (
                double length /** length */ 
            );
            /**Returns  the length vector I
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double ILength
            (
            );
            /**Sets  the length vector I
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetILength
            (
                double vectorI /** vectori */ 
            );
            /**Returns  the length vector J
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double JLength
            (
            );
            /**Sets  the length vector J
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetJLength
            (
                double vectorI /** vectori */ 
            );
            /**Returns  the length vector K
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double KLength
            (
            );
            /**Sets  the length vector K
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetKLength
            (
                double vectorK /** vectork */ 
            );
            /**Returns  the enum size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Vsa::FixturePlaneFeatureBuilder::APISizeType SizeType
            (
            );
            /**Sets  the enum size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetSizeType
            (
                NXOpen::Vsa::FixturePlaneFeatureBuilder::APISizeType sizeType /** sizetype */ 
            );
            /**Returns  the double skewness size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleSkewnessSize
            (
            );
            /**Sets  the double skewness size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleSkewnessSize
            (
                double doubleSkewnessSize /** doubleskewnesssize */ 
            );
            /**Returns  the double kurtosis size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleKurtosisSize
            (
            );
            /**Sets  the double kurtosis size 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleKurtosisSize
            (
                double doubleKurtosisSize /** doublekurtosissize */ 
            );
            /**Returns  the enum loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Vsa::FixturePlaneFeatureBuilder::APILocType LocType
            (
            );
            /**Sets  the enum loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetLocType
            (
                NXOpen::Vsa::FixturePlaneFeatureBuilder::APILocType locType /** loctype */ 
            );
            /**Returns  the double skewness loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleSkewnessLoc
            (
            );
            /**Sets  the double skewness loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleSkewnessLoc
            (
                double doubleSkewnessLoc /** doubleskewnessloc */ 
            );
            /**Returns  the double kurtosis loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleKurtosisLoc
            (
            );
            /**Sets  the double kurtosis loc 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleKurtosisLoc
            (
                double doubleKurtosisLoc /** doublekurtosisloc */ 
            );
            /**Returns  the enum form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Vsa::FixturePlaneFeatureBuilder::APIFormType FormType
            (
            );
            /**Sets  the enum form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetFormType
            (
                NXOpen::Vsa::FixturePlaneFeatureBuilder::APIFormType formType /** formtype */ 
            );
            /**Returns  the double skewness form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleSkewnessForm
            (
            );
            /**Sets  the double skewness form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleSkewnessForm
            (
                double doubleSkewnessForm /** doubleskewnessform */ 
            );
            /**Returns  the double kurtosis form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: double DoubleKurtosisForm
            (
            );
            /**Sets  the double kurtosis form 
             <br>  Usable only on Windows <br> 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_vsa_build (" Building VSA model") */
            public: void SetDoubleKurtosisForm
            (
                double doubleKurtosisForm /** doublekurtosisform */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
