//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     AECDesign_AECDesignSession.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_aecdesign_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace AECDesign
    {
        class AECDesignSession;
    }
    class Session;
    namespace AECDesign
    {
        class AECDesignNavigatorCollection;
    }
    namespace AECDesign
    {
        class AECDesignNavigatorRoot;
    }
    namespace AECDesign
    {
        class PlanElevationViewManager;
    }
    namespace Annotations
    {
        class AECDesignBaseLine;
    }
    namespace Annotations
    {
        class Annotation;
    }
    class Curve;
    namespace Features
    {
        namespace AECDesign
        {
            class Grid;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class Level;
        }
    }
    class NXObject;
    class Part;
    class Sketch;
    namespace AECDesign
    {
        class AECDesignSessionImpl;
        /** Represents AECDesign session  <br> To obtain an instance of this class, refer to @link NXOpen::Session  NXOpen::Session @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_AECDESIGNEXPORT  AECDesignSession
        {
            private: AECDesignSessionImpl * m_aecdesignsession_impl;
            private: NXOpen::Session* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit AECDesignSession(NXOpen::Session *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~AECDesignSession();
            /** Get names for all the levels
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: std::vector<NXString> GetLevelNames
            (
            );
            /**Returns  the active level name
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXString ActiveLevelName
            (
            );
            /**Sets  the active level name
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetActiveLevelName
            (
                const NXString & activeLevel /** activelevel */ 
            );
            /**Sets  the active level name
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            void SetActiveLevelName
            (
                const char * activeLevel /** activelevel */ 
            );
            /** Gets the position and height of active level
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void GetActiveLevelPositionAndHeight
            (
                double* levelPosition /** levelposition */ ,
                double* levelHeight /** levelheight */ 
            );
            /** Establish aec design navigator root  @return  
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: NXOpen::AECDesign::AECDesignNavigatorRoot * GetAECDesignNavigatorRoot
            (
            );
            /**Returns  the level container
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Part * LevelContainer
            (
            );
            /**Sets  the level container
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetLevelContainer
            (
                NXOpen::Part * levelContainer /** levelcontainer */ 
            );
            /** Starts level creation 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void StartLevelCreation
            (
                NXOpen::Features::AECDesign::Level * level /** level */ 
            );
            /** Finishes level creation 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void FinishLevelCreation
            (
                NXOpen::Features::AECDesign::Level * level /** level */ 
            );
            /** Add Curves to grid line 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void AddCurvesToGridLine
            (
                NXOpen::Sketch * tgSketch /** tgsketch */ ,
                const std::vector<NXOpen::Curve *> & curves /** curves */ 
            );
            /** Set Curves to last saved curves in grid task 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetLastSavedCurvesInGridTask
            (
                NXOpen::Sketch * tgSketch /** tgsketch */ ,
                const std::vector<NXOpen::Curve *> & curves /** curves */ 
            );
            /** Set multi-segment toggle on 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetMultiSegmentToggleOn
            (
            );
            /** Set multi-segment toggle off 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetMultiSegmentToggleOff
            (
            );
            /** Starts grid creation 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: NXOpen::Features::AECDesign::Grid * CreateGrid
            (
            );
            /** Starts grid task 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void StartGridTask
            (
                NXOpen::Features::AECDesign::Grid * tgGridFrec /** tggridfrec */ 
            );
            /** Finishes grid task 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void FinishGridTask
            (
                NXOpen::Features::AECDesign::Grid * tgGridFrec /** tggridfrec */ 
            );
            /**Returns  the plan elevation view manager
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::AECDesign::PlanElevationViewManager * PlanElevationViewManager
            (
            );
            /** Deletes objects for grid or level 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void DeleteObjectsForGridLevel
            (
                NXOpen::Sketch * tgSketch /** tgsketch */ ,
                const std::vector<NXOpen::NXObject *> & objects /** Objects to be deleted */
            );
            /** Starts to edit AEC line format
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void StartEditAECLineFormat
            (
                NXOpen::NXObject * tgAECLine /** tgaecline */ 
            );
            /** Finishes the last AEC line format
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void FinishLastAECLineFormat
            (
            );
            /** Enables AEC line format elbow
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void EnableAECLineElbow
            (
                NXOpen::Annotations::Annotation * tgElbow /** tgelbow */ 
            );
            /** Changes the state of AEC line format toggle
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void ChangeLineEndToggleState
            (
                NXOpen::Annotations::Annotation * tgToggle /** tgtoggle */ 
            );
            /** On exiting the BIM Design application
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void OnExitApplication
            (
            );
            /** Sets the origin for the BIM line. It will not move the BIM line.
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetOnlySelfOriginBaseLine
            (
                NXOpen::Annotations::AECDesignBaseLine * tgBaseLine /** tgbaseline */ ,
                double x /** x */ ,
                double y /** y */ ,
                double z /** z */ 
            );
            /** Updates dimensions of BIM curves 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: bool UpdateDimensionsOfBIMCurves
            (
                NXOpen::Sketch * tgSketch /** tgsketch */ ,
                const std::vector<NXOpen::Annotations::AECDesignBaseLine *> & baseCurves /** basecurves */ 
            );
            /** Updates and regenerates all symbols for base line.
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void UpdateAndRegenAllSymbolsForBaseLine
            (
                NXOpen::Annotations::AECDesignBaseLine * tgBaseLine /** tgbaseline */ 
            );
            /** Sets the state of in the level update.
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetStateOfInLevelUpdate
            (
                bool bInLevelUpdate /** binlevelupdate */ 
            );
            /** Exits the Sketch environment. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void LevelSketchEnd
            (
            );
            /** Sets entites as the last saved entites in the grid task. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_bim ("AEC Design") */
            public: void SetLastSavedEntitesInGridTask
            (
                NXOpen::Sketch * tgSketch /** tgsketch */ ,
                const std::vector<NXOpen::NXObject *> & entites /** entites */ 
            );


            /** Returns the @link NXOpen::AECDesign::AECDesignNavigatorCollection NXOpen::AECDesign::AECDesignNavigatorCollection@endlink  belonging to this session 
             <br>  Created in NX2206.0.0.  <br>  
            */
            public: NXOpen::AECDesign::AECDesignNavigatorCollection *NavigatorCollection();
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
