//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_LaminateCompositeMapping.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class LaminateCompositeMapping;
    }
    class NXObject;
    namespace CAE
    {
        class _LaminateCompositeMappingBuilder;
        class LaminateCompositeMappingImpl;
        /** Laminate Composite Mapping  <br> To create or edit an instance of this class, use @link NXOpen::CAE::LaminateCompositeMappingBuilder  NXOpen::CAE::LaminateCompositeMappingBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  LaminateCompositeMapping : public NXOpen::NXObject
        {
            private: LaminateCompositeMappingImpl * m_laminatecompositemapping_impl;
            private: friend class  _LaminateCompositeMappingBuilder;
            protected: LaminateCompositeMapping();
            public: ~LaminateCompositeMapping();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
