//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_ModelAndLoadPreProcessBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_AcousticsAndVibrationSolverParametersComponentAccessor.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class ModelAndLoadPreProcessBuilder;
    }
    class Builder;
    namespace CAE
    {
        class AcousticsAndVibrationSolverParametersComponentAccessor;
    }
    namespace CAE
    {
        class _ModelAndLoadPreProcessBuilderBuilder;
        class ModelAndLoadPreProcessBuilderImpl;
        /**
            Builds a @link NXOpen::CAE::ModelAndLoadPreProcess NXOpen::CAE::ModelAndLoadPreProcess@endlink  object which 
            represets a data processing meta solution.
             <br> To create a new instance of this class, use @link NXOpen::CAE::ModelAndLoadPreProcessor::CreateBuilder  NXOpen::CAE::ModelAndLoadPreProcessor::CreateBuilder @endlink  <br> 
         <br>  Created in NX1847.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  ModelAndLoadPreProcessBuilder : public NXOpen::Builder
        {
            private: ModelAndLoadPreProcessBuilderImpl * m_modelandloadpreprocessbuilder_impl;
            private: friend class  _ModelAndLoadPreProcessBuilderBuilder;
            protected: ModelAndLoadPreProcessBuilder();
            public: ~ModelAndLoadPreProcessBuilder();
            /**Returns  the meta solution name. 
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXString MetaSolutionName
            (
            );
            /**Sets  the meta solution name. 
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetMetaSolutionName
            (
                const NXString & title /** title */ 
            );
            /**Sets  the meta solution name. 
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            void SetMetaSolutionName
            (
                const char * title /** title */ 
            );
            /**Returns  the solver Parameters 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAE::AcousticsAndVibrationSolverParametersComponentAccessor * SolverParameters
            (
            );
            /**Returns  the option "Run Job in Foreground" 
             <br>  @deprecated Deprecated in NX1953.0.0.  Use the accessors in the contained @link AcousticsAndVibrationSolverParametersComponentAccessor AcousticsAndVibrationSolverParametersComponentAccessor@endlink  instead. <br>  

             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX1953.0.0.  Use the accessors in the contained AcousticsAndVibrationSolverParametersComponentAccessor instead.") bool RunInForeground
            (
            );
            /**Sets  the option "Run Job in Foreground" 
             <br>  @deprecated Deprecated in NX1953.0.0.  Use the accessors in the contained @link AcousticsAndVibrationSolverParametersComponentAccessor AcousticsAndVibrationSolverParametersComponentAccessor@endlink  instead. <br>  

             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NX_DEPRECATED("Deprecated in NX1953.0.0.  Use the accessors in the contained AcousticsAndVibrationSolverParametersComponentAccessor instead.") void SetRunInForeground
            (
                bool runInForeground /** runinforeground */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
