//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DesignSimulation_AnalysisBodyResults.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DesignSimulation_AnalysisBodySubcaseResults.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_designsimulation_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DesignSimulation
    {
        class AnalysisBodyResults;
    }
    namespace DesignSimulation
    {
        class AnalysisBodySubcaseResults;
    }
    class NXObject;
    namespace DesignSimulation
    {
        class _AnalysisBodyResultsBuilder;
        class AnalysisBodyResultsImpl;
        /** Represents analysis results for an @link NXOpen::DesignSimulation::AnalysisBody NXOpen::DesignSimulation::AnalysisBody@endlink .  <br> Analysis results are created internally by the owning Study  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class NXOPENCPP_DESIGNSIMULATIONEXPORT  AnalysisBodyResults : public NXOpen::NXObject
        {
             /** Represents a triangular facet with ordered indices of its vertices. */
            public:
            struct Facet
            {
                public: /** vertex 1 */int V1;
                public: /** vertex 2 */int V2;
                public: /** vertex 3 */int V3;
                public: Facet() :
                    V1(),
                    V2(),
                    V3()
                {
                }
                /** Constructor for the Facet struct. */ 
                public: Facet(int v1Initial /** vertex 1 */, 
                        int v2Initial /** vertex 2 */, 
                        int v3Initial /** vertex 3 */) :
                    V1(v1Initial),
                    V2(v2Initial),
                    V3(v3Initial)
                {
                }
            };

            private: AnalysisBodyResultsImpl * m_analysisbodyresults_impl;
            private: friend class  _AnalysisBodyResultsBuilder;
            protected: AnalysisBodyResults();
            public: ~AnalysisBodyResults();
            /**Returns  the number of vertices in the analysis results contour 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: int NumberOfContourVertices
            (
            );
            /**Returns  the number of facets in the analysis results contour 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: int NumberOfContourFacets
            (
            );
            /** Gets all the vertices in the analysis results contour. Count should match <ja_property>NXOpen.DesignSimulation.AnalysisBodyResults.NumberOfContourVertices</ja_property>. 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: std::vector<NXOpen::Point3d> GetContourVertices
            (
            );
            /** Get vertex coordinates at given index. The index must be between 0 and <ja_property>NXOpen.DesignSimulation.AnalysisBodyResults.NumberOfContourVertices</ja_property>. 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point3d GetContourVertexAt
            (
                int index /** index */ 
            );
            /** Gets all the facets (triangular) in the analysis results contour. Count should match <ja_property>NXOpen.DesignSimulation.AnalysisBodyResults.NumberOfContourFacets</ja_property>. 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: std::vector<NXOpen::DesignSimulation::AnalysisBodyResults::Facet> GetContourFacets
            (
            );
            /** Get facet at given index. The index must be between 0 and <ja_property>NXOpen.DesignSimulation.AnalysisBodyResults.NumberOfContourFacets</ja_property>. 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::AnalysisBodyResults::Facet GetContourFacetAt
            (
                int index /** index */ 
            );
            /** Returns the analysis result data per @link NXOpen::DesignSimulation::Subcase NXOpen::DesignSimulation::Subcase@endlink  in the owning @link NXOpen::DesignSimulation::Study NXOpen::DesignSimulation::Study@endlink .
                        @link NXOpen::DesignSimulation::AnalysisBodySubcaseResults NXOpen::DesignSimulation::AnalysisBodySubcaseResults@endlink  will have results for <ja_property>NXOpen.DesignSimulation.AnalysisBodyResults.NumberOfContourVertices</ja_property> vertices. 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: std::vector<NXOpen::DesignSimulation::AnalysisBodySubcaseResults *> GetSubcaseResults
            (
            );
            /** Blanks the analysis body result. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void Blank
            (
            );
            /** Unblanks the analysis body result. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void Unblank
            (
            );
            /**Returns  the blank status of this analysis body result. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool IsBlanked
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
