//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DocumentPartValidator.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/IValidator.hxx>
#include <NXOpen/IValidator.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class DocumentPartValidator;
    class IValidator;
    class _DocumentPartValidatorBuilder;
    class DocumentPartValidatorImpl;

    /// \cond NX_NO_DOC 
    /** validator for Document objects in a document part.  <br> To create a new instance of this class, use @link NXOpen::DocumentDebugSession::CreatePartValidator  NXOpen::DocumentDebugSession::CreatePartValidator @endlink  <br> 
     <br>  Created in NX2306.0.0.  <br>  
    */
    class NXOPENDEBUGSESSIONCPPEXPORT  DocumentPartValidator : public NXOpen::TaggedObject, public virtual NXOpen::IValidator
    {
        private: DocumentPartValidatorImpl * m_documentpartvalidator_impl;
        private: friend class  _DocumentPartValidatorBuilder;
        protected: DocumentPartValidator();
        public: ~DocumentPartValidator();

        /// \cond NX_NO_DOC 
        /**Returns  This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : None */
        public: virtual NXOpen::ValidatorVersion ValidatorVersion
        (
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /**Sets  This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : None */
        public: virtual void SetValidatorVersion
        (
            NXOpen::ValidatorVersion version /** version */ 
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /**Returns  This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : None */
        public: virtual NXOpen::ValidatorPrintLevel ValidatorPrintLevel
        (
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /**Sets  This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : None */
        public: virtual void SetValidatorPrintLevel
        (
            NXOpen::ValidatorPrintLevel level /** level */ 
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX7.5.0.  <br>  
         <br> License requirements : None */
        public: virtual void Destroy
        (
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX9.0.0.  <br>  
         <br> License requirements : None */
        public: virtual void SetValidatorPrintOodStatus
        (
            bool status /** status */ 
        );

        /// \endcond 
    };

    /// \endcond 
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
