//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Document_BordersBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libdocumentopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Document
    {
        class BordersBuilder;
    }
    class Builder;
    namespace Document
    {
        class _BordersBuilderBuilder;
        class BordersBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Represents the BordersBuilder.
              <br> To create a new instance of this class, use @link NXOpen::Document::ToolsManager::CreateBordersBuilder  NXOpen::Document::ToolsManager::CreateBordersBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        BottomMargin </term> <description> 
         
        5 (millimeters part), 0 (inches part) </description> </item> 

        <item><term> 
         
        CreateBorders </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        LeftMargin </term> <description> 
         
        5 (millimeters part), 0 (inches part) </description> </item> 

        <item><term> 
         
        RightMargin </term> <description> 
         
        5 (millimeters part), 0 (inches part) </description> </item> 

        <item><term> 
         
        TopMargin </term> <description> 
         
        5 (millimeters part), 0 (inches part) </description> </item> 

        <item><term> 
         
        Width </term> <description> 
         
        8 (millimeters part), 0.3149 (inches part) </description> </item> 

        </list> 

         <br>  Created in NX2306.0.0.  <br>  
        */
        class DOCUMENTOPENCPPEXPORT  BordersBuilder : public NXOpen::Builder
        {
            private: BordersBuilderImpl * m_bordersbuilder_impl;
            private: friend class  _BordersBuilderBuilder;
            protected: BordersBuilder();
            public: ~BordersBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool CreateBorders
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetCreateBorders
            (
                bool createBorders /** createborders */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: double Width
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetWidth
            (
                double width /** width */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: double TopMargin
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetTopMargin
            (
                double topMargin /** topmargin */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: double BottomMargin
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetBottomMargin
            (
                double bottomMargin /** bottommargin */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: double LeftMargin
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetLeftMargin
            (
                double leftMargin /** leftmargin */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: double RightMargin
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetRightMargin
            (
                double rightMargin /** rightmargin */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
