//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DSE_DesignConstraintBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libdseopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DSE
    {
        class DesignConstraintBuilder;
    }
    class Builder;
    class Expression;
    class TaggedObject;
    namespace DSE
    {
        class _DesignConstraintBuilderBuilder;
        class DesignConstraintBuilderImpl;
        /** Represents Design Constraint builder. <br> To create a new instance of this class, use @link NXOpen::DSE::StudyManager::CreateDesignConstraintBuilder  NXOpen::DSE::StudyManager::CreateDesignConstraintBuilder @endlink  <br> 
         <br>  Created in NX2007.0.0.  <br>  
        */
        class DSEOPENCPPEXPORT  DesignConstraintBuilder : public NXOpen::Builder
        {
            /** Represents different target type options to compare for Constraint.*/
            public: enum TargetType
            {
                TargetTypeEqualto/** equalto */ ,
                TargetTypeGreaterthanorEqualto/** greaterthanor equalto */ ,
                TargetTypeLessthanorEqualto/** lessthanor equalto */ ,
                TargetTypeWithinRange/** within range */ 
            };

            /** Represents normalization controls to define default normalisation factor or to specify.*/
            public: enum NormalizationOption
            {
                NormalizationOptionUseDefault/** use default */ ,
                NormalizationOptionSpecify/** specify */ 
            };

            private: DesignConstraintBuilderImpl * m_designconstraintbuilder_impl;
            private: friend class  _DesignConstraintBuilderBuilder;
            protected: DesignConstraintBuilder();
            public: ~DesignConstraintBuilder();
            /**Returns  the constraint name 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: NXString ConstraintName
            (
            );
            /**Sets  the constraint name 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetConstraintName
            (
                const NXString & constraintName /** constraintname */ 
            );
            /**Sets  the constraint name 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            void SetConstraintName
            (
                const char * constraintName /** constraintname */ 
            );
            /**Returns  the constraint type 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DSE::DesignConstraintBuilder::TargetType ConstraintType
            (
            );
            /**Sets  the constraint type 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetConstraintType
            (
                NXOpen::DSE::DesignConstraintBuilder::TargetType constraintType /** constrainttype */ 
            );
            /**Returns  the constraint limit value 
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::TargetValueExpression DSE::DesignConstraintBuilder::TargetValueExpression@endlink  instead. <br>  

             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::TargetValueExpression instead.") double ConstraintTargetValue
            (
            );
            /**Sets  the constraint limit value 
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::TargetValueExpression DSE::DesignConstraintBuilder::TargetValueExpression@endlink  instead. <br>  

             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::TargetValueExpression instead.") void SetConstraintTargetValue
            (
                double constraintTargetValue /** constrainttargetvalue */ 
            );
            /** Set the selected application object 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetSelectedAppObject
            (
                NXOpen::TaggedObject * appObject /** appobject */ 
            );
            /**Returns  the constraint linear weight 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: int LinearWeight
            (
            );
            /**Sets  the constraint linear weight 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetLinearWeight
            (
                int linearWeight /** linearweight */ 
            );
            /**Returns  the constraint quad weight 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: int QuadWeight
            (
            );
            /**Sets  the constraint quad weight 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetQuadWeight
            (
                int quadWeight /** quadweight */ 
            );
            /**Returns  the constraint upper limit available only when target type is range
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::UpperLimitExpression DSE::DesignConstraintBuilder::UpperLimitExpression@endlink  instead. <br>  

             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::UpperLimitExpression instead.") double ConstraintUpperLimit
            (
            );
            /**Sets  the constraint upper limit available only when target type is range
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::UpperLimitExpression DSE::DesignConstraintBuilder::UpperLimitExpression@endlink  instead. <br>  

             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::UpperLimitExpression instead.") void SetConstraintUpperLimit
            (
                double constraintUpperLimit /** constraintupperlimit */ 
            );
            /**Returns  the constraint lower limit available only when target type is range
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::LowerLimitExpression DSE::DesignConstraintBuilder::LowerLimitExpression@endlink  instead. <br>  

             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::LowerLimitExpression instead.") double ConstraintLowerLimit
            (
            );
            /**Sets  the constraint lower limit available only when target type is range
             <br>  @deprecated Deprecated in NX2212.0.0.  Use @link DSE::DesignConstraintBuilder::LowerLimitExpression DSE::DesignConstraintBuilder::LowerLimitExpression@endlink  instead. <br>  

             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: NX_DEPRECATED("Deprecated in NX2212.0.0.  Use DSE::DesignConstraintBuilder::LowerLimitExpression instead.") void SetConstraintLowerLimit
            (
                double constraintLowerLimit /** constraintlowerlimit */ 
            );
            /**Returns  the normalization factor control available only when target type is not range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DSE::DesignConstraintBuilder::NormalizationOption NormalizationType
            (
            );
            /**Sets  the normalization factor control available only when target type is not range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetNormalizationType
            (
                NXOpen::DSE::DesignConstraintBuilder::NormalizationOption normalizationType /** normalizationtype */ 
            );
            /**Returns  the normalization factor available only when target type is not range and normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: double NormalizationFactor
            (
            );
            /**Sets  the normalization factor available only when target type is not range and normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetNormalizationFactor
            (
                double normalizationFactor /** normalizationfactor */ 
            );
            /**Returns  the lower normalization factor control available only when target type is range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DSE::DesignConstraintBuilder::NormalizationOption LowerNormalizationType
            (
            );
            /**Sets  the lower normalization factor control available only when target type is range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetLowerNormalizationType
            (
                NXOpen::DSE::DesignConstraintBuilder::NormalizationOption lowerNormalizationType /** lowernormalizationtype */ 
            );
            /**Returns  the lower normalization factor available only when target type is range and lower normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: double LowerNormalizationFactor
            (
            );
            /**Sets  the lower normalization factor available only when target type is range and lower normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetLowerNormalizationFactor
            (
                double lowerNormalizationFactor /** lowernormalizationfactor */ 
            );
            /**Returns  the upper normalization factor control available only when target type is range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DSE::DesignConstraintBuilder::NormalizationOption UpperNormalizationType
            (
            );
            /**Sets  the upper normalization factor control available only when target type is range
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetUpperNormalizationType
            (
                NXOpen::DSE::DesignConstraintBuilder::NormalizationOption upperNormalizationType /** uppernormalizationtype */ 
            );
            /**Returns  the upper normalization factor available only when target type is range and upper normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: double UpperNormalizationFactor
            (
            );
            /**Sets  the upper normalization factor available only when target type is range and upper normalization control is opted to specify
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_design_explorer (" NX Design Space Exploration") */
            public: void SetUpperNormalizationFactor
            (
                double upperNormalizationFactor /** uppernormalizationfactor */ 
            );
            /**Returns  the target value expression
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * TargetValueExpression
            (
            );
            /**Returns  the lower limit expression
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * LowerLimitExpression
            (
            );
            /**Returns  the upper limit expression
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * UpperLimitExpression
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
