//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Falcon_AisleNetworkByPointBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Falcon_JigComponentBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libfalconopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Falcon
    {
        class AisleNetworkByPointBuilder;
    }
    class Builder;
    namespace Falcon
    {
        class JigComponentBuilder;
    }
    namespace Falcon
    {
        class _AisleNetworkByPointBuilderBuilder;
        class AisleNetworkByPointBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Aisle Network By Point <br> To create a new instance of this class, use @link NXOpen::Falcon::FalconManager::CreateAisleNetworkByPointBuilder  NXOpen::Falcon::FalconManager::CreateAisleNetworkByPointBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class FALCONOPENCPPEXPORT  AisleNetworkByPointBuilder : public NXOpen::Builder
        {
            private: AisleNetworkByPointBuilderImpl * m_aislenetworkbypointbuilder_impl;
            private: friend class  _AisleNetworkByPointBuilderBuilder;
            protected: AisleNetworkByPointBuilder();
            public: ~AisleNetworkByPointBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : flow_analysis (" Flow Analysis") */
            public: NXOpen::Falcon::JigComponentBuilder * JigComponent
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool KeepAisleOnXyPlane
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : flow_analysis (" Flow Analysis") */
            public: void SetKeepAisleOnXyPlane
            (
                bool keepAisleOnXyPlane /** keepaisleonxyplane */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
