//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_DrawShapes_DivideBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace DrawShapes
        {
            class DivideBuilder;
        }
    }
    class Builder;
    class SelectCurveList;
    namespace Features
    {
        namespace DrawShapes
        {
            class _DivideBuilderBuilder;
            class DivideBuilderImpl;
            /** Represents @link  NXOpen::Features::DrawShapes::DivideBuilder   NXOpen::Features::DrawShapes::DivideBuilder @endlink 
                        allowing user to divide curves.
                     <br> To create a new instance of this class, use @link NXOpen::Features::DrawShapes::DrawShapeCollection::CreateDivideBuilder  NXOpen::Features::DrawShapes::DrawShapeCollection::CreateDivideBuilder @endlink  <br> 
             <br>  Created in NX2206.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  DivideBuilder : public NXOpen::Builder
            {
                private: DivideBuilderImpl * m_dividebuilder_impl;
                private: friend class  _DivideBuilderBuilder;
                protected: DivideBuilder();
                public: ~DivideBuilder();
                /**Returns  the curves to be divided 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectCurveList * Targets
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
