//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     LogicEditorDebugSession.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class LogicEditorDebugSession;
    class DebugSession;
    class BasePart;
    class RuleBaseValidator;
    class TaggedObject;
    class LogicEditorDebugSessionImpl;

    /// \cond NX_NO_DOC 
    /** Represents a class that is used for NX Logic Editor Autotest.  This class should not be made available to customers  <br> To obtain an instance of this class, refer to @link NXOpen::DebugSession  NXOpen::DebugSession @endlink  <br> 
     <br>  Created in NX1953.0.0.  <br>  
    */
    class NXOPENDEBUGSESSIONCPPEXPORT  LogicEditorDebugSession
    {
        private: LogicEditorDebugSessionImpl * m_logiceditordebugsession_impl;
        private: NXOpen::DebugSession* m_owner;
        /// \cond NX_NO_DOC 
        public: explicit LogicEditorDebugSession(NXOpen::DebugSession *owner);


        /// \endcond 
        public: 
        /**Returns the tag of this object.  */
        tag_t Tag() const; 
        public: ~LogicEditorDebugSession();

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX1953.0.0.  <br>  
         <br> License requirements : None */
        public: NXOpen::RuleBaseValidator * CreateLogicEditorValidator
        (
            NXOpen::BasePart * displayPart /** part being validated */,
            int validateMask /** validatemask */ ,
            double relativeTolerance /** relativetolerance */ 
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX1953.0.0.  <br>  
         <br> License requirements : None */
        public: void SetRuleInstances
        (
            NXOpen::RuleBaseValidator * mainValidator /** main logic editor validator */,
            const std::vector<NXOpen::TaggedObject *> & ruleInstances /** prepare RuleInstance for validate */
        );

        /// \endcond 

        /// \cond NX_NO_DOC 
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX1953.0.0.  <br>  
         <br> License requirements : None */
        public: void PopulateValidators
        (
            NXOpen::RuleBaseValidator * mainValidator /** main logic editor rule validator */,
            std::vector<NXOpen::RuleBaseValidator *> & validators /** created validators */
        );

        /// \endcond 
    }; //lint !e1712 default constructor not defined for class  


    /// \endcond 
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
