//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Mechatronics_BondZoneBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Mechatronics_ZoneBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_mechatronics_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Mechatronics
    {
        class BondZoneBuilder;
    }
    class Builder;
    class Expression;
    namespace Mechatronics
    {
        class SelectRigidBodyList;
    }
    namespace Mechatronics
    {
        class ZoneBuilder;
    }
    namespace Mechatronics
    {
        class _BondZoneBuilderBuilder;
        class BondZoneBuilderImpl;
        /** Represents a @link NXOpen::Mechatronics::BondZone NXOpen::Mechatronics::BondZone@endlink  builder.  <br> To create a new instance of this class, use @link NXOpen::Mechatronics::BondZoneCollection::CreateBondZoneBuilder  NXOpen::Mechatronics::BondZoneCollection::CreateBondZoneBuilder @endlink  <br> 
         <br>  Created in NX1953.0.0.  <br>  
        */
        class NXOPENCPP_MECHATRONICSEXPORT  BondZoneBuilder : public NXOpen::Builder
        {
            /** the action mode for bond. */
            public: enum ActionModes
            {
                ActionModesCollision/** when collision happens */,
                ActionModesUserDefined/** when user defined */
            };

            private: BondZoneBuilderImpl * m_bondzonebuilder_impl;
            private: friend class  _BondZoneBuilderBuilder;
            protected: BondZoneBuilder();
            public: ~BondZoneBuilder();
            /**Returns  the zone builder that holds the parameters. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXOpen::Mechatronics::ZoneBuilder * Zone
            (
            );
            /**Returns  the bond bodies. This can be @link NXOpen::Mechatronics::RigidBody NXOpen::Mechatronics::RigidBody@endlink .
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXOpen::Mechatronics::SelectRigidBodyList * BondBodies
            (
            );
            /**Returns  the action mode. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXOpen::Mechatronics::BondZoneBuilder::ActionModes ActionMode
            (
            );
            /**Sets  the action mode. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: void SetActionMode
            (
                NXOpen::Mechatronics::BondZoneBuilder::ActionModes mode /** mode */ 
            );
            /**Returns  the category. It should be between 0 and 16. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: int Category
            (
            );
            /**Sets  the category. It should be between 0 and 16. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: void SetCategory
            (
                int category /** category */ 
            );
            /**Returns  whether update mass center or not 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: bool UpdateMassCenter
            (
            );
            /**Sets  whether update mass center or not 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: void SetUpdateMassCenter
            (
                bool updateMassCenter /** updatemasscenter */ 
            );
            /**Returns  whether check rigid relative velocity for bond 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: bool CheckRelativeVelocity
            (
            );
            /**Sets  whether check rigid relative velocity for bond 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: void SetCheckRelativeVelocity
            (
                bool checkVel /** checkvel */ 
            );
            /**Returns  the bond threshold value for relative linear velocity 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXOpen::Expression * LinearRelativeVelocity
            (
            );
            /**Returns  the bond threshold value for relative angular velocity 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXOpen::Expression * AngularRelativeVelocity
            (
            );
            /**Returns  the name. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: NXString Name
            (
            );
            /**Sets  the name. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            public: void SetName
            (
                const NXString & name /** name */ 
            );
            /**Sets  the name. 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_mcd_core ("Mechatronics Concept Designer") */
            void SetName
            (
                const char * name /** name */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
