//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     PartMfg_WorkInstructionManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/PartMfg_AssignWorkInstructionTemplateBuilder.hxx>
#include <NXOpen/PartMfg_CreateWorkInstructionBuilder.hxx>
#include <NXOpen/PartMfg_CreateWorkInstructionTemplateBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libpartmfgopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace PartMfg
    {
        class WorkInstructionManager;
    }
    namespace PartMfg
    {
        class PartMfgPart;
    }
    namespace PartMfg
    {
        class AssignWorkInstructionTemplateBuilder;
    }
    namespace PartMfg
    {
        class CreateWorkInstructionBuilder;
    }
    namespace PartMfg
    {
        class CreateWorkInstructionTemplateBuilder;
    }
    namespace PartMfg
    {
        class WorkInstructionManagerImpl;

        /// \cond NX_NO_DOC 
        /** Represents the manager object for Work instructions.
              <br> To obtain an instance of this class, refer to @link NXOpen::PartMfg::PartMfgPart  NXOpen::PartMfg::PartMfgPart @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class PARTMFGOPENCPPEXPORT  WorkInstructionManager
        {
            private: WorkInstructionManagerImpl * m_workinstructionmanager_impl;
            private: NXOpen::PartMfg::PartMfgPart* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit WorkInstructionManager(NXOpen::PartMfg::PartMfgPart *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~WorkInstructionManager();

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::PartMfg::CreateWorkInstructionBuilder * CreateWorkInstructionBuilder
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::PartMfg::CreateWorkInstructionTemplateBuilder * CreateTemplateBuilder
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::PartMfg::AssignWorkInstructionTemplateBuilder * CreateAssignWorkInstructionTemplateBuilder
            (
            );

            /// \endcond 
        }; //lint !e1712 default constructor not defined for class  


        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
