//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Safety_JointBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Safety_EntityBuilder.hxx>
#include <NXOpen/libsafetyopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Safety
    {
        class JointBuilder;
    }
    namespace Safety
    {
        class EntityBuilder;
    }
    namespace Safety
    {
        class _JointBuilderBuilder;
        class JointBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Represents a builder of Safety Joint object  <br> To create a new instance of this class, use @link NXOpen::Safety::JointManager::CreateJointBuilder  NXOpen::Safety::JointManager::CreateJointBuilder @endlink  <br> 
         <br>  Created in NX1953.0.0.  <br>  
        */
        class SAFETYOPENCPPEXPORT  JointBuilder : public NXOpen::Safety::EntityBuilder
        {
            private: JointBuilderImpl * m_jointbuilder_impl;
            private: friend class  _JointBuilderBuilder;
            protected: JointBuilder();
            public: ~JointBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXString EntityName
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : sc_md_prepost ("Simcenter Safety Pre and Post") */
            public: void SetEntityName
            (
                const NXString & name /** name */ 
            );
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : sc_md_prepost ("Simcenter Safety Pre and Post") */
            void SetEntityName
            (
                const char * name /** name */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
