#ifndef NXOpen_ANNOTATIONS_PMIEDGECONDITIONSYMBOLDATA_HXX_INCLUDED
#define NXOpen_ANNOTATIONS_PMIEDGECONDITIONSYMBOLDATA_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_PmiEdgeConditionSymbolData.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_BaseEdgeConditionSymbolBuilder.hxx>
#include <NXOpen/Annotations_PmiSemanticData.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Annotations
    {
        class PmiEdgeConditionSymbolData;
    }
    namespace Annotations
    {
        class PmiSemanticData;
    }
    namespace Annotations
    {
        class PmiEdgeConditionSymbolDataImpl;
        /** Represents PMI Edge Condition Symbol Data. 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_ANNOTATIONSEXPORT  PmiEdgeConditionSymbolData : public NXOpen::Annotations::PmiSemanticData
        {
            private: PmiEdgeConditionSymbolDataImpl * m_pmiedgeconditionsymboldata_impl;
            /// \cond NX_NO_DOC 
            public: explicit PmiEdgeConditionSymbolData(void *ptr);
            /// \endcond 
            /**Returns  the Edge Condition Symbol Method 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXOpen::Annotations::BaseEdgeConditionSymbolBuilder::MethodType MethodType
            (
            );
            /**Returns  the Edge Condition Symbol All Around 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: bool AllAround
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation A1 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationA1
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation A2 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationA2
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation B1 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationB1
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation B2 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationB2
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation C1 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationC1
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation C2 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviationC2
            (
            );
            /**Returns  the Edge Condition Symbol Limit Deviation 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : geometric_tol ("GDT") */
            public: NXString LimitDeviation
            (
            );
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
