#ifndef NXOpen_CAE_AMMATERIALSMANAGER_HXX_INCLUDED
#define NXOpen_CAE_AMMATERIALSMANAGER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_AmMaterialsManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class AmMaterialsManager;
    }
    namespace CAE
    {
        class SimSimulation;
    }
    namespace CAE
    {
        class AmMaterialsSolutionCollection;
    }
    namespace CAE
    {
        class AmMaterialsManagerImpl;
        /** Represents the Am Materials manager that contains all Am Materials objects.  <br> To obtain an instance of this class, refer to @link NXOpen::CAE::SimSimulation  NXOpen::CAE::SimSimulation @endlink  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  AmMaterialsManager
        {
            private: AmMaterialsManagerImpl * m_ammaterialsmanager_impl;
            private: NXOpen::CAE::SimSimulation* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit AmMaterialsManager(NXOpen::CAE::SimSimulation *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~AmMaterialsManager();


            /** Returns the @link NXOpen::CAE::AmMaterialsSolutionCollection NXOpen::CAE::AmMaterialsSolutionCollection@endlink  belonging to this sim part. 
             <br>  Created in NX2212.0.0.  <br>  
            */
            public: NXOpen::CAE::AmMaterialsSolutionCollection *Solutions();
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
