#ifndef NXOpen_CAM_ROTARYBUILDUPADDITIVEBUILDER_HXX_INCLUDED
#define NXOpen_CAM_ROTARYBUILDUPADDITIVEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAM_RotaryBuildupAdditiveBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAM_Geometry.hxx>
#include <NXOpen/CAM_MillOperationBuilder.hxx>
#include <NXOpen/libnxopencpp_cam_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAM
    {
        class RotaryBuildupAdditiveBuilder;
    }
    namespace CAM
    {
        class Geometry;
    }
    namespace CAM
    {
        class MillOperationBuilder;
    }
    namespace CAM
    {
        class PartAxisBuilder;
    }
    namespace CAM
    {
        class _RotaryBuildupAdditiveBuilderBuilder;
        class RotaryBuildupAdditiveBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Represents a rotary buildup additive builder  <br> To create a new instance of this class, use @link NXOpen::CAM::OperationCollection::CreateRotaryBuildupAdditiveBuilder  NXOpen::CAM::OperationCollection::CreateRotaryBuildupAdditiveBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_CAMEXPORT  RotaryBuildupAdditiveBuilder : public NXOpen::CAM::MillOperationBuilder
        {
            private: RotaryBuildupAdditiveBuilderImpl * m_rotarybuildupadditivebuilder_impl;
            private: friend class  _RotaryBuildupAdditiveBuilderBuilder;
            protected: RotaryBuildupAdditiveBuilder();
            public: ~RotaryBuildupAdditiveBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAM::PartAxisBuilder * PartAxisBuilder
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAM::Geometry * CheckGeometry
            (
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
