#ifndef NXOpen_COMPOSITES_CROSSSECTIONBUILDER_HXX_INCLUDED
#define NXOpen_COMPOSITES_CROSSSECTIONBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Composites_CrossSectionBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libcompositesopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Composites
    {
        class CrossSectionBuilder;
    }
    class Builder;
    class Plane;
    namespace Composites
    {
        class _CrossSectionBuilderBuilder;
        class CrossSectionBuilderImpl;

        /// \cond NX_NO_DOC 
        /**
            Creates or edits a @link Composites::CrossSection Composites::CrossSection@endlink  object.
             <br> To create a new instance of this class, use @link NXOpen::Composites::Manager::CreateCrossSectionBuilder  NXOpen::Composites::Manager::CreateCrossSectionBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        PlyScale </term> <description> 
         
        1 </description> </item> 

        </list> 

         <br>  Created in NX2206.0.0.  <br>  
        */
        class COMPOSITESOPENCPPEXPORT  CrossSectionBuilder : public NXOpen::Builder
        {
            private: CrossSectionBuilderImpl * m_crosssectionbuilder_impl;
            private: friend class  _CrossSectionBuilderBuilder;
            protected: CrossSectionBuilder();
            public: ~CrossSectionBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: NXOpen::Plane * PlaneSelect
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: void SetPlaneSelect
            (
                NXOpen::Plane * planeSelect /** planeselect */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: double PlyScale
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: void SetPlyScale
            (
                double plyScale /** plyscale */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
