#ifndef NXOpen_COMPOSITES_DESIGNSTATION_HXX_INCLUDED
#define NXOpen_COMPOSITES_DESIGNSTATION_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Composites_DesignStation.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Composites_Base.hxx>
#include <NXOpen/libcompositesopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Composites
    {
        class DesignStation;
    }
    namespace Composites
    {
        class Base;
    }
    namespace Composites
    {
        class _DesignStationBuilder;
        class DesignStationImpl;

        /// \cond NX_NO_DOC 
        /** Represents a definition of a Design Station to perform a virtual core sample on a composite part.  <br> Design Stations are created with a @link Composites::DesignStationBuilder Composites::DesignStationBuilder@endlink .  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class COMPOSITESOPENCPPEXPORT  DesignStation : public NXOpen::Composites::Base
        {
            private: DesignStationImpl * m_designstation_impl;
            private: friend class  _DesignStationBuilder;
            protected: DesignStation();
            public: ~DesignStation();
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
