#ifndef NXOpen_CONTACTLESSINSPECTION_SURFACEPOINTMEASUREMENT_HXX_INCLUDED
#define NXOpen_CONTACTLESSINSPECTION_SURFACEPOINTMEASUREMENT_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     ContactlessInspection_SurfacePointMeasurement.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/ContactlessInspection_PointMeasurement.hxx>
#include <NXOpen/libcontactlessinspectionopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace ContactlessInspection
    {
        class SurfacePointMeasurement;
    }
    namespace ContactlessInspection
    {
        class PointMeasurement;
    }
    namespace ContactlessInspection
    {
        class _SurfacePointMeasurementBuilder;
        class SurfacePointMeasurementImpl;
        /**
                Represents the base class for an Contactless Inspection Surface Point Measurement.
             <br> To create or edit an instance of this class, use @link NXOpen::ContactlessInspection::MeasureSurfacePointBuilder  NXOpen::ContactlessInspection::MeasureSurfacePointBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class CONTACTLESSINSPECTIONOPENCPPEXPORT  SurfacePointMeasurement : public NXOpen::ContactlessInspection::PointMeasurement
        {
            private: SurfacePointMeasurementImpl * m_surfacepointmeasurement_impl;
            private: friend class  _SurfacePointMeasurementBuilder;
            protected: SurfacePointMeasurement();
            public: ~SurfacePointMeasurement();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
