#ifndef NXOpen_CONTACTLESSINSPECTION_GAUGEALIGNMENTBUILDER_HXX_INCLUDED
#define NXOpen_CONTACTLESSINSPECTION_GAUGEALIGNMENTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     ContactlessInspection_GaugeAlignmentBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libcontactlessinspectionopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace ContactlessInspection
    {
        class GaugeAlignmentBuilder;
    }
    class Builder;
    class SelectPlane;
    namespace ContactlessInspection
    {
        class _GaugeAlignmentBuilderBuilder;
        class GaugeAlignmentBuilderImpl;

        /// \cond NX_NO_DOC 
        /**The builder class to create a @link ContactlessInspection::GaugeAlignment ContactlessInspection::GaugeAlignment@endlink  object in Contactless Inspection Application. <br> To create a new instance of this class, use @link NXOpen::ContactlessInspection::Manager::CreateGaugeAlignmentBuilder  NXOpen::ContactlessInspection::Manager::CreateGaugeAlignmentBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class CONTACTLESSINSPECTIONOPENCPPEXPORT  GaugeAlignmentBuilder : public NXOpen::Builder
        {
            private: GaugeAlignmentBuilderImpl * m_gaugealignmentbuilder_impl;
            private: friend class  _GaugeAlignmentBuilderBuilder;
            protected: GaugeAlignmentBuilder();
            public: ~GaugeAlignmentBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXString PrimaryDatumLabel
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            public: void SetPrimaryDatumLabel
            (
                const NXString & primaryDatumLabel /** primarydatumlabel */ 
            );
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            void SetPrimaryDatumLabel
            (
                const char * primaryDatumLabel /** primarydatumlabel */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectPlane * PrimaryDatum
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXString SecondaryDatumLabel
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            public: void SetSecondaryDatumLabel
            (
                const NXString & secondaryDatumLabel /** secondarydatumlabel */ 
            );
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            void SetSecondaryDatumLabel
            (
                const char * secondaryDatumLabel /** secondarydatumlabel */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectPlane * SecondaryDatum
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXString TertiayDatumLabel
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            public: void SetTertiayDatumLabel
            (
                const NXString & tertiayDatumLabel /** tertiaydatumlabel */ 
            );
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_contctles_inspect (" NX Contactless Inspection") */
            void SetTertiayDatumLabel
            (
                const char * tertiayDatumLabel /** tertiaydatumlabel */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectPlane * TertiaryDatum
            (
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
