#ifndef NXOpen_DESIGNSIMULATION_RESULTSETTINGSBUILDER_HXX_INCLUDED
#define NXOpen_DESIGNSIMULATION_RESULTSETTINGSBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DesignSimulation_ResultSettingsBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DesignSimulation_ViewContourBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_designsimulation_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DesignSimulation
    {
        class ResultSettingsBuilder;
    }
    class Builder;
    namespace DesignSimulation
    {
        class _ResultSettingsBuilderBuilder;
        class ResultSettingsBuilderImpl;
        /** Creates a @link NXOpen::DesignSimulation::ResultSettingsBuilder NXOpen::DesignSimulation::ResultSettingsBuilder@endlink .
              <br> To create a new instance of this class, use @link NXOpen::DesignSimulation::PostManager::CreateResultSettingsBuilder  NXOpen::DesignSimulation::PostManager::CreateResultSettingsBuilder @endlink  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class NXOPENCPP_DESIGNSIMULATIONEXPORT  ResultSettingsBuilder : public NXOpen::Builder
        {
            private: ResultSettingsBuilderImpl * m_resultsettingsbuilder_impl;
            private: friend class  _ResultSettingsBuilderBuilder;
            protected: ResultSettingsBuilder();
            public: ~ResultSettingsBuilder();
            /**Returns  the result component type 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ViewContourBuilder::ResultComponentOption ResultComponent
            (
            );
            /**Sets  the result component type 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetResultComponent
            (
                NXOpen::DesignSimulation::ViewContourBuilder::ResultComponentOption resultComponentType /** resultcomponenttype */ 
            );
            /**Returns  the contour display style 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ViewContourBuilder::ContourDisplayStyleOption ContourDisplayStyle
            (
            );
            /**Sets  the contour display style 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetContourDisplayStyle
            (
                NXOpen::DesignSimulation::ViewContourBuilder::ContourDisplayStyleOption contourDisplayStyle /** contourdisplaystyle */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
