#ifndef NXOpen_DIAGRAMMING_FILL_HXX_INCLUDED
#define NXOpen_DIAGRAMMING_FILL_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Diagramming_Fill.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Diagramming_SheetElement.hxx>
#include <NXOpen/libnxopencpp_diagramming_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Diagramming
    {
        class Fill;
    }
    namespace Diagramming
    {
        class SheetElement;
    }
    namespace Diagramming
    {
        class _FillBuilder;
        class FillImpl;

        /// \cond NX_NO_DOC 
        /** Represents the Fill class.  <br> To create or edit an instance of this class, use @link NXOpen::Diagramming::FillBuilder  NXOpen::Diagramming::FillBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_DIAGRAMMINGEXPORT  Fill : public NXOpen::Diagramming::SheetElement
        {
            private: FillImpl * m_fill_impl;
            private: friend class  _FillBuilder;
            protected: Fill();
            public: ~Fill();
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
