#ifndef NXOpen_FEATURES_ADASCOORDINATESYSTEM_HXX_INCLUDED
#define NXOpen_FEATURES_ADASCOORDINATESYSTEM_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ADASCoordinateSystem.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class ADASCoordinateSystem;
    }
    namespace Features
    {
        class Feature;
    }
    namespace Features
    {
        class _ADASCoordinateSystemBuilder;
        class ADASCoordinateSystemImpl;

        /// \cond NX_NO_DOC 
        /** Represents a adascoordinate system feature  <br> To create or edit an instance of this class, use @link NXOpen::Features::ADASCoordinateSystemBuilder  NXOpen::Features::ADASCoordinateSystemBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  ADASCoordinateSystem : public NXOpen::Features::Feature
        {
            private: ADASCoordinateSystemImpl * m_adascoordinatesystem_impl;
            private: friend class  _ADASCoordinateSystemBuilder;
            protected: ADASCoordinateSystem();
            public: ~ADASCoordinateSystem();
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
