#ifndef NXOpen_FEATURES_SHEETMETAL_BULGERELIEF_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_BULGERELIEF_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_BulgeRelief.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_BodyFeature.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class BulgeRelief;
        }
    }
    namespace Features
    {
        class BodyFeature;
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class _BulgeReliefBuilder;
            class BulgeReliefImpl;
            /** Represents a bulge relief feature  <br> To create or edit an instance of this class, use @link NXOpen::Features::SheetMetal::BulgeReliefBuilder  NXOpen::Features::SheetMetal::BulgeReliefBuilder @endlink  <br> 
             <br>  Created in NX2212.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  BulgeRelief : public NXOpen::Features::BodyFeature
            {
                private: BulgeReliefImpl * m_bulgerelief_impl;
                private: friend class  _BulgeReliefBuilder;
                protected: BulgeRelief();
                public: ~BulgeRelief();
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
