#ifndef NXOpen_FEATURES_AECDESIGN_CEILINGBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_AECDESIGN_CEILINGBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_AECDesign_CeilingBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_AECDesign_BoundaryOffsetBuilder.hxx>
#include <NXOpen/Features_AECDesign_LevelReferenceBuilder.hxx>
#include <NXOpen/Features_AECDesign_MaterialLayersBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace AECDesign
        {
            class CeilingBuilder;
        }
    }
    class Expression;
    namespace Features
    {
        namespace AECDesign
        {
            class BoundaryOffsetBuilder;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class LevelReferenceBuilder;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class MaterialLayersBuilder;
        }
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    class ScCollector;
    class Section;
    namespace Features
    {
        namespace AECDesign
        {
            class _CeilingBuilderBuilder;
            class CeilingBuilderImpl;
            /**  @brief 
                    Represents a ceiling builder for AEC Design. 
                     

             
                    
                    This builder is used to create ceiling feature in AEC Design.
                    
                 <br> To create a new instance of this class, use @link NXOpen::Features::AECDesignCollection::CreateAecCeilingBuilder  NXOpen::Features::AECDesignCollection::CreateAecCeilingBuilder @endlink  <br> 
            Default values.
            <list type="table"> 
             
            <listheader><term> 
            Property</term>  <description> 
            Value</description> </listheader>
            <item><term> 
             
            Offset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            Thickness.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            TrimFlag </term> <description> 
             
            0 </description> </item> 

            </list> 

             <br>  Created in NX2206.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  CeilingBuilder : public NXOpen::Features::FeatureBuilder
            {
                private: CeilingBuilderImpl * m_ceilingbuilder_impl;
                private: friend class  _CeilingBuilderBuilder;
                protected: CeilingBuilder();
                public: ~CeilingBuilder();
                /**Returns  the boundary curve to define ceiling. 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Section * SelectCurves
                (
                );
                /**Returns  the offset distance between ceiling and the original room top face. 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Offset
                (
                );
                /**Returns  the thickness 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Thickness
                (
                );
                /**Returns  the material layers
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::MaterialLayersBuilder * MaterialLayers
                (
                );
                /**Returns  the level reference
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::LevelReferenceBuilder * LevelReference
                (
                );
                /**Returns  the level reference
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::BoundaryOffsetBuilder * BoundaryOffset
                (
                );
                /**Returns  the building element trim flag 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: bool TrimFlag
                (
                );
                /**Sets  the building element trim flag 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetTrimFlag
                (
                    bool trimFlag /** trimflag */ 
                );
                /**Returns  the tool body 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::ScCollector * ToolBody
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
