#ifndef NXOpen_FEATURES_SHIPDESIGN_STEELFEATURESPREADSHEETBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHIPDESIGN_STEELFEATURESPREADSHEETBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_SteelFeatureSpreadsheetBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_Industry_SectionFeatureSpreadsheetBuilder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class SteelFeatureSpreadsheetBuilder;
        }
    }
    namespace Features
    {
        namespace Industry
        {
            class SectionFeatureSpreadsheetBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class _SteelFeatureSpreadsheetBuilderBuilder;
            class SteelFeatureSpreadsheetBuilderImpl;
            /**
                    Represents a @link NXOpen::Features::ShipDesign::SteelFeatureSpreadsheetBuilder NXOpen::Features::ShipDesign::SteelFeatureSpreadsheetBuilder@endlink  builder. 
                    It is used to manage the data contained in the ship sketch based steel feature block.
                     <br> This class is sub-object of another builder, and cannot be directly instantiated.  <br> 
             <br>  Created in NX8.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  SteelFeatureSpreadsheetBuilder : public NXOpen::Features::Industry::SectionFeatureSpreadsheetBuilder
            {
                private: SteelFeatureSpreadsheetBuilderImpl * m_steelfeaturespreadsheetbuilder_impl;
                private: friend class  _SteelFeatureSpreadsheetBuilderBuilder;
                protected: SteelFeatureSpreadsheetBuilder();
                public: ~SteelFeatureSpreadsheetBuilder();
                /**Returns  the flag to indicate whether current builder is modified. 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: bool Modified
                (
                );
                /**Sets  the flag to indicate whether current builder is modified. 
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") OR nx_ship_basic ("Ship Basic Design") */
                public: void SetModified
                (
                    bool modified /** modified */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
