#ifndef NXOpen_PARTMFG_PROCESSTOLERANCEBUILDER_HXX_INCLUDED
#define NXOpen_PARTMFG_PROCESSTOLERANCEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     PartMfg_ProcessToleranceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libpartmfgopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace PartMfg
    {
        class ProcessToleranceBuilder;
    }
    class Builder;
    namespace PartMfg
    {
        class _ProcessToleranceBuilderBuilder;
        class ProcessToleranceBuilderImpl;
        /** Builder class  <br> To create a new instance of this class, use @link NXOpen::PartMfg::ProcessToleranceCollection::CreateProcessToleranceBuilder  NXOpen::PartMfg::ProcessToleranceCollection::CreateProcessToleranceBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        IdMethod </term> <description> 
         
        Manual </description> </item> 

        <item><term> 
         
        MethodType </term> <description> 
         
        Manual </description> </item> 

        <item><term> 
         
        SelectAllOperations </term> <description> 
         
        0 </description> </item> 

        </list> 

         <br>  Created in NX2212.0.0.  <br>  
        */
        class PARTMFGOPENCPPEXPORT  ProcessToleranceBuilder : public NXOpen::Builder
        {
            /** operation method type */
            public: enum MethodType1
            {
                MethodType1Manual/** Manual */,
                MethodType1ToleranceTable/** Tolerance table */
            };

            /** identification method */
            public: enum IdentificationMethod
            {
                IdentificationMethodManual/** Manual */,
                IdentificationMethodDerived/** Derived */
            };

            private: ProcessToleranceBuilderImpl * m_processtolerancebuilder_impl;
            private: friend class  _ProcessToleranceBuilderBuilder;
            protected: ProcessToleranceBuilder();
            public: ~ProcessToleranceBuilder();
            /**Returns  the method type 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::PartMfg::ProcessToleranceBuilder::MethodType1 MethodType
            (
            );
            /**Sets  the method type 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetMethodType
            (
                NXOpen::PartMfg::ProcessToleranceBuilder::MethodType1 methodType /** methodtype */ 
            );
            /**Returns  the select all operations 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: bool SelectAllOperations
            (
            );
            /**Sets  the select all operations 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetSelectAllOperations
            (
                bool selectAllOperations /** selectalloperations */ 
            );
            /**Returns  the tolerance value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXString ToleranceValue
            (
            );
            /**Sets  the tolerance value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetToleranceValue
            (
                const NXString & toleranceValue /** tolerancevalue */ 
            );
            /**Sets  the tolerance value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            void SetToleranceValue
            (
                const char * toleranceValue /** tolerancevalue */ 
            );
            /**Returns  the lower value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXString LowerValue
            (
            );
            /**Sets  the lower value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetLowerValue
            (
                const NXString & lowerValue /** lowervalue */ 
            );
            /**Sets  the lower value 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            void SetLowerValue
            (
                const char * lowerValue /** lowervalue */ 
            );
            /**Returns  the id method 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::PartMfg::ProcessToleranceBuilder::IdentificationMethod IdMethod
            (
            );
            /**Sets  the id method 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetIdMethod
            (
                NXOpen::PartMfg::ProcessToleranceBuilder::IdentificationMethod idMethod /** idmethod */ 
            );
            /**Returns  the identification 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Identification
            (
            );
            /**Sets  the identification 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetIdentification
            (
                const NXString & identification /** identification */ 
            );
            /**Sets  the identification 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            void SetIdentification
            (
                const char * identification /** identification */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
