#ifndef NXOpen_SCHEMATIC_MECHANICAL_BRANCH_HXX_INCLUDED
#define NXOpen_SCHEMATIC_MECHANICAL_BRANCH_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Schematic_Mechanical_Branch.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Schematic_Model_BaseObject.hxx>
#include <NXOpen/libnxopencpp_schematic_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Schematic
    {
        namespace Mechanical
        {
            class Branch;
        }
    }
    namespace Schematic
    {
        namespace Model
        {
            class BaseObject;
        }
    }
    namespace Schematic
    {
        namespace Mechanical
        {
            class _BranchBuilder;
            class BranchImpl;

            /// \cond NX_NO_DOC 
            /** Represents the Branch class.  <br> Instance of this can not directly created.  <br> 
             <br>  Created in NX2206.0.0.  <br>  
            */
            class NXOPENCPP_SCHEMATICEXPORT  Branch : public NXOpen::Schematic::Model::BaseObject
            {
                private: BranchImpl * m_branch_impl;
                private: friend class  _BranchBuilder;
                protected: Branch();
                public: ~Branch();
            };

            /// \endcond 
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
