#ifndef NXOpen_SCHEMATIC_PROPERTYTYPE_HXX_INCLUDED
#define NXOpen_SCHEMATIC_PROPERTYTYPE_HXX_INCLUDED
//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Schematic_PropertyType.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Schematic
    {
        /** This is an internal API and can be changed at any time 
         <br>  Created in NX2212.0.0.  <br>  
        */

        /// \cond NX_NO_DOC 
        enum JaSchematicPropertytype
        {
            JaSchematicPropertytypeNull/** Null type */,
            JaSchematicPropertytypeIndex/** Index of object */,
            JaSchematicPropertytypeUserAttribute/** User attribute */,
            JaSchematicPropertytypeId/** ID object */,
            JaSchematicPropertytypeName/** Name of object */,
            JaSchematicPropertytypeSymbol/** The symbol svg */,
            JaSchematicPropertytypeSymbolDescription/** The symbol description */,
            JaSchematicPropertytypeQuantity/** The quantity of same object */ = 11,
            JaSchematicPropertytypeParentRun/** The parent run of pipe stock */ = 101,
            JaSchematicPropertytypeRunAttribute/** The attibute of run object */,
            JaSchematicPropertytypeEquipmentAttribute/** The attibute of equipment object */,
            JaSchematicPropertytypePipeAttribute/** Pipe  attribute */
        };


        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#endif
