from __future__ import annotations
from typing import overload, Tuple, List, Callable
from enum import Enum
from abc import abstractmethod
##  Represents the selection filter members for NXOpen development 
##  No filter. Should not be used. 
class FilterMember(Enum):
    """
    Members Include: <NotSet> <Group> <Pattern> <PatternPoint> <ProductDefinition> <ViewSet> <Field> <AllAnalyses> <DeviationGauge> <GridSectionAnalysis> <HighlightLinesAnalysis> <SurfaceContinuityAnalysis> <GapAndFlushnessAnalysis> <CurveContinuityAnalysis> <SectionAnalysis> <CurveAnalysis> <SurfaceIntersectionAnalysis> <DraftAnalysis> <TrimAngleCheck> <LocalRadiusAnalysis> <MoldFlowMoldx3dAnalysis> <WallThicknessAnalysis> <FaceCurvatureAnalysis> <FaceAnalysis> <SheetBoundaryAnalysis> <DistanceAnalysis> <RadiusAnalysis> <ReflectionAnalysis> <SlopeAnalysis> <AnimationDesignerAll> <AnimationDesignerRigidGroup> <AnimationDesignerContact> <AnimationDesignerJoint> <AnimationDesignerMotor> <AnimationDesignerCoupler> <AnimationDesignerMonitor> <AnimationDesignerAnimatedEffects> <AnimationDesignerJointJogger> <AnimationDesignerContainer> <AnimationDesignerFlexibleObject> <Component> <ComponentPattern> <AssemblyConstraint> <AssemblyConstraintGroup> <AutomationDesignerTerminalNode> <AutomationDesignerEPLANMacro> <AutomationDesignerAspect> <AutomationDesignerProgramBlock> <AutomationDesignerPageObject> <AutomationDesignerEngineeringObject> <AutomationDesignerVariable> <AutomationDesignerPlugNode> <AutomationDesignerNode> <AutomationDesignerTag> <AutomationDesignerCPU> <AutomationDesignerUserConstant> <AutomationDesignerStation> <AutomationDesignerPLCStation> <AutomationDesignerHardwareDevice> <AutomationDesignerHardwareItem> <AutomationDesignerLocalModuleFolder> <AutomationDesignerDistributedIOFolder> <AutomationDesignerUpstreamDataObject> <AutomationDesignerSymbol> <AutomationDesignerConnection> <AutomationDesignerConnectionPoint> <AutomationDesignerAnnotation> <AutomationDesignerTable> <AutomationDesignerAutomationUnassigned> <AutomationDesignerDocumentRoot> <AutomationDesignerDocumentStructureNode> <AutomationDesignerFragmentNode> <AutomationDesignerProduct> <AutomationDesignerProductComponent> <AutomationDesignerGroup> <AutomationDesignerQuery> <AutomationDesignerReportDefinition> <AutomationDesignerPLCTagsFolder> <AutomationDesignerEClass> <AutomationDesignerConnector> <AutomationDesignerUserPort> <AutomationDesignerPLCSubnet> <AutomationDesignerUdt> <AutomationDesignerBaseDefinitionNode> <AutomationDesignerSymbolStructureNode> <AutomationDesignerInterruptionPoint> <AutomationDesignerTagInterruptionPointNode> <AutomationDesignerRoot> <AutomationDesignerUnassigned> <AutomationDesignerProductTemplateLinkNode> <AutomationDesignerMemoryArea> <AutomationDesigner2DSymbols3DModels> <AutomationDesignerCableCore> <AutomationDesignerTagTable> <AutomationDesignerStationFolder> <AutomationDesignerRack> <AutomationDesignerConnectedDevice> <AutomationDesignerSymbolVariant> <AutomationDesignerViewPageNode> <AutomationDesignerBMECatVersionNode> <AutomationDesignerEClassVersionNode> <AutomationDesignerTemplateContent> <AllCAE> <CAEPolygonEdge> <CAEPolygonFace> <CAEPolygonBody> <CAEPolygonVertex> <CAELoad> <CAEConstraint> <CAESimulationObject> <CAEConnection> <CAEMeshPoint> <CAEEdgeDensity> <CAEFaceDensity> <CAEWeldRowDensity> <CAEMappedHoleDensity> <CAEFilletDensity> <CAECylinderDensity> <CAEPointDensity> <CAEBoundingVolumeDensity> <CAEMeshMating> <CAEEdgeSeparationCondition> <CAEBoundaryLayer> <CAESelectionRecipe> <CAECrackFaceCondition> <CAEFaceMatchControl> <CAEEdgeMatchControl> <CAEDOFSet> <CAEMesh> <CAETransientMesh> <CAESensor> <CAEResponseAnalysisStrainGauge> <CAEElement> <CAEElementEdge> <CAEElementFace> <CAENode> <CAEMarginCalculation> <CAELoadCaseSet> <CAEMarginSolution> <CAEFilteringSolution> <CAEFilteringCalculation> <CAEDurabilitySpecialistEvent> <CAELocalDefinition> <CAESpecialistSolution> <CAEFunctionDefinition> <CAECorrelationInput> <CAEVibrationInput> <CAERandomDataSource> <CAEDurabilitySpecialistStrainGauge> <CAEResultReference> <CAELayoutState> <CAEFemDataSet> <CAELoadRecipe> <CAEDataSource> <CAEDataProcessing> <CAEModelAndLoadPreprocessing> <CAEAcousticsAndVibrationSolution> <CAETransientMeshGroup> <CAEUniversalConnectionFolder> <CAEUniversalConnection> <CAESpotWeldConnection> <CAEAdhesiveConnection> <CAEBoltConnection> <CAESeamWeldConnection> <CAESealingConnection> <CAESpringConnection> <CAEDamperConnection> <CAERigidConnection> <CAEBushingConnection> <CAEKinematicConnection> <CAELumpedMass> <CAERivet> <CAEClinch> <CAECrimpConnection> <CAEBarConnection> <CAEBearingConnection> <CAELoadCaseFilteringSolution> <CAEStressLinearization> <CAEStressLinearizationManager> <CAEPostTransNode> <CAEPostTransElement> <CAEPostTransMesh> <CAEPostTransPolygonEdge> <CAEPostTransPolygonFace> <CAEPostTransComponent> <CAEFreeBody> <CAEResultProbe> <CAEPostTransElementFace> <CAEPostTransElementEdge> <CAEFreeBodyFolder> <CAEStressLinearizationFolder> <CoatingLayer> <CoatingStack> <LinearMaterial> <DatumAxis> <DatumPlane> <SectionSegment> <SectionLine> <CoordinateSystem> <Plane> <DatumPlaneGrid> <PlanarShipGrid> <Traceline> <Image> <ControlCage> <CageFace> <CageEdge> <CageVertex> <DesignMeshBody> <DesignMeshFace> <DesignMeshEdge> <DesignMeshVertex> <AllDimensions> <LinearDimension> <AngularDimension> <RadialDimension> <OrdinateDimension> <ChamferDimension> <ThicknessDimension> <ArcLengthDimension> <DimensionSet> <AllDrafting> <AllCenterlines> <AreaFill> <AllSymbols> <Note> <Label> <Balloon> <GDTSymbol> <Centerline> <FullCircularCenterline> <PartialCircularCenterline> <FullBoltCircle> <PartialBoltCircle> <CenterMark> <CylindricalCenterline> <SymmetricalCenterline> <Centerline2D> <Crosshatch> <Intersection> <TargetPoint> <UserDefinedSymbol> <OffsetCenterPoint> <LabelOnParent> <TitleBlock> <FrameBar> <Arrow> <CuttingPlaneSymbol> <ShipTic> <SupplementalGeometry> <ViewBreak> <DrawingTemplateRegion> <SurfaceFinish> <TabularNote> <DrawingImage> <Component2D> <ProductGrid> <EdgeConditionSymbol> <AllFacetBodies> <NormalFacetBody> <CloudFacetBody> <NXFacet> <AllBasicAndWeldFeatures> <AllBasicFeatures> <SolidFeature> <CurveFeature> <DatumPlaneFeature> <DatumAxisFeature> <DatumCoordinateSystemFeature> <SketchFeature> <HD3DMarkup> <HD3DMarkupElement> <AllJoinObjects> <JoinPoint> <JoinCurve> <JoinFace> <JoinHole> <LineDesignerConnector> <MachiningFeature> <MachiningToolPath> <MachiningInProcessWorkpiece> <AdditiveManufacturingSerialNumber> <AdditiveManufacturingPartGroup> <AdditiveManufacturingBuildTray> <AdditiveManufacturingPart> <AdditiveManufacturingPartOccurrence> <AdditiveManufacturingSupport> <AdditiveManufacturingSupportOccurrence> <AdditiveManufacturingPartRegion> <AdditiveManufacturingPartRegionOccurrence> <ManufacturingPlanningRigidGroup> <ManufacturingPlanningJoint> <MDCLogicalElement> <MDCConnectionElement> <MDCPortArtifact> <AllMechatronics> <MechatronicsJoint> <MechatronicsCollisionBody> <MechatronicsCollisionSensor> <MechatronicsRuntimeButton> <MechatronicsDistanceSensor> <Mechatronics2DLaserScanner> <MechatronicsLightCurtain> <MechatronicsPositionSensor> <MechatronicsVelocitySensor> <MechatronicsGenericSensor> <MechatronicsLimitSwitch> <MechatronicsRelay> <MechatronicsInclinometer> <MechatronicsAccelerometer> <MechatronicsPneumaticCylinder> <MechatronicsPneumaticValve> <MechatronicsHydraulicCylinder> <MechatronicsHydraulicValve> <MechatronicsRigidBody> <MechatronicsConstraint> <MechatronicsTransportSurface> <MechatronicsObjectSource> <MechatronicsObjectSink> <MechatronicsObjectTransformer> <MechatronicsObjectBehavior> <MechatronicsObjectData> <MechatronicsProxyObject> <MechatronicsSignal> <MechatronicsSnapPoint> <MechatronicsDynamicMaterial> <AllMotionSim> <AllMotionSimForceObjects> <AllMotionSimJoints> <MotionSimRoad> <MotionSimBearing> <MotionSimBearingProperty> <MotionSimControlPort> <MotionSimControlInput> <MotionSimPathFollower> <MotionSimControlOperation> <MotionSimControlOutput> <MotionSimGear> <MotionSimGearContact> <MotionSimAnimation> <MotionSimGraph> <MotionSimMlpp> <MotionSimCurveOperationRecord> <MotionSimMotionBodyDriver> <MotionSimLoadTransfer> <MotionSimJointDriver> <MotionSimStandaloneDriver> <MotionSimMechatronics> <MotionSimProfile> <MotionSimDiscreteDrivetrain> <MotionSimAnimationCamera> <MotionSimAutoflexProperty> <MotionSimBasicTireProperty> <MotionSimMotorcycleTireProperty> <MotionSimNonInertialTireProperty> <MotionSimFTireProperty> <MotionSimCDTireProperty> <MotionSimMFTyreAndMFSwiftTireProperty> <MotionSimTire> <MotionSimVehicleReporting> <MotionSimSuspensionReporting> <MotionSimInitialCondition> <MotionSimAnalyticalContact> <MotionSimAnalyticalContactProperty> <MotionSimSpring> <MotionSimRotationalSpring> <MotionSimTranslationalSpring> <MotionSimDamper> <MotionSimRotationalDamper> <MotionSimTranslationalDamper> <MotionSimSpringDamper> <MotionSimRotationalSpringDamper> <MotionSimTranslationalSpringDamper> <MotionSimSplineBeam> <MotionSimSplineBeamProperty> <MotionSimBeamSection> <MotionSimBeamForce> <MotionSimUserDefinedForce> <MotionSimFriction> <MotionSimThreePointForce> <MotionSimThreePointTorque> <MotionSimSubmechanism> <MotionSimSubmechanismPositioner> <MotionSimMotionConstraint> <MotionSimMotionBody> <MotionSimScalarForce> <MotionSimFlexibleBody> <MotionSimMarker> <MotionSimScalarTorque> <MotionSimCurveCurveContact> <MotionSimContact> <MotionSimBushing> <MotionSimBushingProperty> <MotionSimVectorForce> <MotionSimVectorTorque> <MotionSimSensor> <MotionSimMotor> <MotionSimMotionVector> <MotionSimMeasure> <MotionSimTrace> <MotionSimInterference> <MotionSimFixedJoint> <MotionSimScrewJoint> <MotionSimRevoluteJoint> <MotionSimSliderJoint> <MotionSimCylinderJoint> <MotionSimUniversalJoint> <MotionSimSphericalJoint> <MotionSimPlanarJoint> <MotionSimGearJoint> <MotionSimRackAndPinion> <MotionSimPointOnCurve> <MotionSimCurveOnCurve> <MotionSimCable> <MotionSimConstantVelocity> <MotionSimAtpointJoint> <MotionSimInlineJoint> <MotionSimInplaneJoint> <MotionSimOrientationJoint> <MotionSimParallelJoint> <MotionSimPerpendicularJoint> <MotionSimGeneralCoupler> <MotionSimMotionBodyCoupler> <MotionSimPlantInput> <MotionSimPlantOutput> <MotionSimSolutionStop> <MotionSimSignalChart> <MotionSimSolution> <MotionSimGearSpur> <MotionSimGearHelical> <MotionSimGearStraightBevel> <MotionSimGearSpiralBevel> <MotionSimGearHypoid> <MotionSimBumpStop> <MotionSimCompoundJoint> <MotionSimAnimationVector> <MotionSimHydrodynamicBearing> <MotionSimSprungMass> <MotionSimDiscreteDrivetrainReport> <MotionSimElectromagneticForce> <MotionSimGeneralSensor> <MotionSimContactPattern> <MotionSimFlexModalContent> <MotionSimFixedJointDriver> <MotionSimFrfInput> <MotionSimFrfOutput> <PhysicalDiagrammingAnnotation> <PhysicalDiagrammingConnection> <PhysicalDiagrammingNode> <BoundaryNode> <PIDAnnotation> <PIDConnection> <PIDSymbol> <PIDRun> <PIDBranch> <PIDSheet> <PIDSystem> <PressLineSimulationLineComponent> <PressLineSimulationPressModelRoot> <AllRoutingObjects> <RoutingControlPoint> <RoutingPort> <RoutingPartAnchor> <RoutingSegment> <RoutingStock> <AllShip> <AllShipPlateSystem> <AllShipProfileSystem> <ShipHull> <ShipDeck> <ShipTransverseBulkhead> <ShipLongitudinalBulkhead> <ShipGenericPlateSystem> <ShipStiffenerSystem> <ShipPillarSystem> <ShipEdgeReinforcement> <ShipSeam> <SketchRelation> <Sketch> <SketchFoundRelation> <SketchCoincidentRelation> <SketchConcentricRelation> <SketchPointOnCurveRelation> <SketchCollinearRelation> <SketchHorizontalRelation> <SketchHorizontalAlignmentRelation> <SketchVerticalRelation> <SketchVerticalAlignmentRelation> <SketchTangentRelation> <SketchParallelRelation> <SketchPerpendicularRelation> <SketchEqualLengthRelation> <SketchEqualRadiusRelation> <SketchSymmetricRelation> <SketchMidpointRelation> <SketchPointOnStringRelation> <SketchTangentToStringRelation> <SketchPerpendicularToStringRelation> <SketchUniformScaleRelation> <SketchG1SplineRelation> <SketchG2SplineRelation> <SketchTrimRelation> <SketchOffsetRelation> <SketchLinearPatternRelation> <SketchRectangularPatternRelation> <SketchCircularPatternRelation> <SketchGeneralPatternRelation> <SketchMirrorRelation> <SketchPolygonRelation> <SketchRigidGroupRelation> <SketchScalableGroupRelation> <SketchIgnoredRelation> <AllEdges> <AllFaces> <AllSolidBodies> <AllSheetBodies> <ConvergentSolidBody> <ConvergentSheetBody> <PlanarFace> <CylindricalFace> <ConicalFace> <SphericalFace> <ToroidalFace> <ParametricFace> <BlendedFace> <OffsetFace> <ExtrudedFace> <RevolvedFace> <ForeignFace> <ConvergentFace> <LinearEdge> <CircularEdge> <EllipticalEdge> <IntersectionEdge> <SplineEdge> <SPCurveEdge> <ForeignEdge> <ConstantParameterEdge> <ConvergentEdge> <ConvergentFacet> <StagedModelStage> <StagedModelStageSet> <StructureDesignMemberCorner> <TechnicalDataPackagePage> <TechnicalDataPackageViewport> <TechnicalDataPackageViewCarousel> <TechnicalDataPackageRectangle> <TechnicalDataPackagePDFFormField> <TechnicalDataPackageAutomaticTable> <TechnicalDataPackageViewList> <TechnicalDataPackagePrintView> <TechnicalDataPackageDiagramArea> <AllViews> <SectionView> <ImportedView> <OrthographicView> <AuxiliaryView> <DetailView> <DrawingSheetView> <ImportedPMILightweightSectionView> <AllBodyInWhiteDatums> <AllWeldingObjects> <AllWeldingMeasurementObjects> <GrooveWeld> <FilletWeld> <ResistanceSpotWeld> <ArcSpotWeld> <NutWeld> <StudWeld> <MechanicalClinchWeld> <DollopWeld> <Custom1Weld> <Custom2Weld> <Custom3Weld> <Custom4Weld> <Custom5Weld> <UserDefinedWeld> <FillWeld> <WeldingJoint> <WeldBead> <WeldPlugSlot> <SurfaceWeld> <TranslateWeld> <JointMarkWeld> <CompoundWeld> <DatumSurface> <DatumPin> <DatumCustom1> <DatumCustom2> <DatumCustom3> <MeasurementSurface> <MeasurementHole> <MeasurementStud> <MeasurementSlot> <MeasurementTrim> <MeasurementHemmedEdge> <MeasurementCustom1> <MeasurementCustom2> <MeasurementCustom3> <AllConicCurves> <AllCurves> <Point> <PointCloud> <Line> <Arc> <Ellipse> <Parabola> <Hyperbola> <Spline> <Polyline> <Stroke> <CompositesLaminate> <CompositesPly> <AllCompositesObjects> <AECGridLine> <AECLevelLine> <AECSymbol> <AECLineFormat>
    """
    NotSet: int
    Group: int
    Pattern: int
    PatternPoint: int
    ProductDefinition: int
    ViewSet: int
    Field: int
    AllAnalyses: int
    DeviationGauge: int
    GridSectionAnalysis: int
    HighlightLinesAnalysis: int
    SurfaceContinuityAnalysis: int
    GapAndFlushnessAnalysis: int
    CurveContinuityAnalysis: int
    SectionAnalysis: int
    CurveAnalysis: int
    SurfaceIntersectionAnalysis: int
    DraftAnalysis: int
    TrimAngleCheck: int
    LocalRadiusAnalysis: int
    MoldFlowMoldx3dAnalysis: int
    WallThicknessAnalysis: int
    FaceCurvatureAnalysis: int
    FaceAnalysis: int
    SheetBoundaryAnalysis: int
    DistanceAnalysis: int
    RadiusAnalysis: int
    ReflectionAnalysis: int
    SlopeAnalysis: int
    AnimationDesignerAll: int
    AnimationDesignerRigidGroup: int
    AnimationDesignerContact: int
    AnimationDesignerJoint: int
    AnimationDesignerMotor: int
    AnimationDesignerCoupler: int
    AnimationDesignerMonitor: int
    AnimationDesignerAnimatedEffects: int
    AnimationDesignerJointJogger: int
    AnimationDesignerContainer: int
    AnimationDesignerFlexibleObject: int
    Component: int
    ComponentPattern: int
    AssemblyConstraint: int
    AssemblyConstraintGroup: int
    AutomationDesignerTerminalNode: int
    AutomationDesignerEPLANMacro: int
    AutomationDesignerAspect: int
    AutomationDesignerProgramBlock: int
    AutomationDesignerPageObject: int
    AutomationDesignerEngineeringObject: int
    AutomationDesignerVariable: int
    AutomationDesignerPlugNode: int
    AutomationDesignerNode: int
    AutomationDesignerTag: int
    AutomationDesignerCPU: int
    AutomationDesignerUserConstant: int
    AutomationDesignerStation: int
    AutomationDesignerPLCStation: int
    AutomationDesignerHardwareDevice: int
    AutomationDesignerHardwareItem: int
    AutomationDesignerLocalModuleFolder: int
    AutomationDesignerDistributedIOFolder: int
    AutomationDesignerUpstreamDataObject: int
    AutomationDesignerSymbol: int
    AutomationDesignerConnection: int
    AutomationDesignerConnectionPoint: int
    AutomationDesignerAnnotation: int
    AutomationDesignerTable: int
    AutomationDesignerAutomationUnassigned: int
    AutomationDesignerDocumentRoot: int
    AutomationDesignerDocumentStructureNode: int
    AutomationDesignerFragmentNode: int
    AutomationDesignerProduct: int
    AutomationDesignerProductComponent: int
    AutomationDesignerGroup: int
    AutomationDesignerQuery: int
    AutomationDesignerReportDefinition: int
    AutomationDesignerPLCTagsFolder: int
    AutomationDesignerEClass: int
    AutomationDesignerConnector: int
    AutomationDesignerUserPort: int
    AutomationDesignerPLCSubnet: int
    AutomationDesignerUdt: int
    AutomationDesignerBaseDefinitionNode: int
    AutomationDesignerSymbolStructureNode: int
    AutomationDesignerInterruptionPoint: int
    AutomationDesignerTagInterruptionPointNode: int
    AutomationDesignerRoot: int
    AutomationDesignerUnassigned: int
    AutomationDesignerProductTemplateLinkNode: int
    AutomationDesignerMemoryArea: int
    AutomationDesigner2DSymbols3DModels: int
    AutomationDesignerCableCore: int
    AutomationDesignerTagTable: int
    AutomationDesignerStationFolder: int
    AutomationDesignerRack: int
    AutomationDesignerConnectedDevice: int
    AutomationDesignerSymbolVariant: int
    AutomationDesignerViewPageNode: int
    AutomationDesignerBMECatVersionNode: int
    AutomationDesignerEClassVersionNode: int
    AutomationDesignerTemplateContent: int
    AllCAE: int
    CAEPolygonEdge: int
    CAEPolygonFace: int
    CAEPolygonBody: int
    CAEPolygonVertex: int
    CAELoad: int
    CAEConstraint: int
    CAESimulationObject: int
    CAEConnection: int
    CAEMeshPoint: int
    CAEEdgeDensity: int
    CAEFaceDensity: int
    CAEWeldRowDensity: int
    CAEMappedHoleDensity: int
    CAEFilletDensity: int
    CAECylinderDensity: int
    CAEPointDensity: int
    CAEBoundingVolumeDensity: int
    CAEMeshMating: int
    CAEEdgeSeparationCondition: int
    CAEBoundaryLayer: int
    CAESelectionRecipe: int
    CAECrackFaceCondition: int
    CAEFaceMatchControl: int
    CAEEdgeMatchControl: int
    CAEDOFSet: int
    CAEMesh: int
    CAETransientMesh: int
    CAESensor: int
    CAEResponseAnalysisStrainGauge: int
    CAEElement: int
    CAEElementEdge: int
    CAEElementFace: int
    CAENode: int
    CAEMarginCalculation: int
    CAELoadCaseSet: int
    CAEMarginSolution: int
    CAEFilteringSolution: int
    CAEFilteringCalculation: int
    CAEDurabilitySpecialistEvent: int
    CAELocalDefinition: int
    CAESpecialistSolution: int
    CAEFunctionDefinition: int
    CAECorrelationInput: int
    CAEVibrationInput: int
    CAERandomDataSource: int
    CAEDurabilitySpecialistStrainGauge: int
    CAEResultReference: int
    CAELayoutState: int
    CAEFemDataSet: int
    CAELoadRecipe: int
    CAEDataSource: int
    CAEDataProcessing: int
    CAEModelAndLoadPreprocessing: int
    CAEAcousticsAndVibrationSolution: int
    CAETransientMeshGroup: int
    CAEUniversalConnectionFolder: int
    CAEUniversalConnection: int
    CAESpotWeldConnection: int
    CAEAdhesiveConnection: int
    CAEBoltConnection: int
    CAESeamWeldConnection: int
    CAESealingConnection: int
    CAESpringConnection: int
    CAEDamperConnection: int
    CAERigidConnection: int
    CAEBushingConnection: int
    CAEKinematicConnection: int
    CAELumpedMass: int
    CAERivet: int
    CAEClinch: int
    CAECrimpConnection: int
    CAEBarConnection: int
    CAEBearingConnection: int
    CAELoadCaseFilteringSolution: int
    CAEStressLinearization: int
    CAEStressLinearizationManager: int
    CAEPostTransNode: int
    CAEPostTransElement: int
    CAEPostTransMesh: int
    CAEPostTransPolygonEdge: int
    CAEPostTransPolygonFace: int
    CAEPostTransComponent: int
    CAEFreeBody: int
    CAEResultProbe: int
    CAEPostTransElementFace: int
    CAEPostTransElementEdge: int
    CAEFreeBodyFolder: int
    CAEStressLinearizationFolder: int
    CoatingLayer: int
    CoatingStack: int
    LinearMaterial: int
    DatumAxis: int
    DatumPlane: int
    SectionSegment: int
    SectionLine: int
    CoordinateSystem: int
    Plane: int
    DatumPlaneGrid: int
    PlanarShipGrid: int
    Traceline: int
    Image: int
    ControlCage: int
    CageFace: int
    CageEdge: int
    CageVertex: int
    DesignMeshBody: int
    DesignMeshFace: int
    DesignMeshEdge: int
    DesignMeshVertex: int
    AllDimensions: int
    LinearDimension: int
    AngularDimension: int
    RadialDimension: int
    OrdinateDimension: int
    ChamferDimension: int
    ThicknessDimension: int
    ArcLengthDimension: int
    DimensionSet: int
    AllDrafting: int
    AllCenterlines: int
    AreaFill: int
    AllSymbols: int
    Note: int
    Label: int
    Balloon: int
    GDTSymbol: int
    Centerline: int
    FullCircularCenterline: int
    PartialCircularCenterline: int
    FullBoltCircle: int
    PartialBoltCircle: int
    CenterMark: int
    CylindricalCenterline: int
    SymmetricalCenterline: int
    Centerline2D: int
    Crosshatch: int
    Intersection: int
    TargetPoint: int
    UserDefinedSymbol: int
    OffsetCenterPoint: int
    LabelOnParent: int
    TitleBlock: int
    FrameBar: int
    Arrow: int
    CuttingPlaneSymbol: int
    ShipTic: int
    SupplementalGeometry: int
    ViewBreak: int
    DrawingTemplateRegion: int
    SurfaceFinish: int
    TabularNote: int
    DrawingImage: int
    Component2D: int
    ProductGrid: int
    EdgeConditionSymbol: int
    AllFacetBodies: int
    NormalFacetBody: int
    CloudFacetBody: int
    NXFacet: int
    AllBasicAndWeldFeatures: int
    AllBasicFeatures: int
    SolidFeature: int
    CurveFeature: int
    DatumPlaneFeature: int
    DatumAxisFeature: int
    DatumCoordinateSystemFeature: int
    SketchFeature: int
    HD3DMarkup: int
    HD3DMarkupElement: int
    AllJoinObjects: int
    JoinPoint: int
    JoinCurve: int
    JoinFace: int
    JoinHole: int
    LineDesignerConnector: int
    MachiningFeature: int
    MachiningToolPath: int
    MachiningInProcessWorkpiece: int
    AdditiveManufacturingSerialNumber: int
    AdditiveManufacturingPartGroup: int
    AdditiveManufacturingBuildTray: int
    AdditiveManufacturingPart: int
    AdditiveManufacturingPartOccurrence: int
    AdditiveManufacturingSupport: int
    AdditiveManufacturingSupportOccurrence: int
    AdditiveManufacturingPartRegion: int
    AdditiveManufacturingPartRegionOccurrence: int
    ManufacturingPlanningRigidGroup: int
    ManufacturingPlanningJoint: int
    MDCLogicalElement: int
    MDCConnectionElement: int
    MDCPortArtifact: int
    AllMechatronics: int
    MechatronicsJoint: int
    MechatronicsCollisionBody: int
    MechatronicsCollisionSensor: int
    MechatronicsRuntimeButton: int
    MechatronicsDistanceSensor: int
    Mechatronics2DLaserScanner: int
    MechatronicsLightCurtain: int
    MechatronicsPositionSensor: int
    MechatronicsVelocitySensor: int
    MechatronicsGenericSensor: int
    MechatronicsLimitSwitch: int
    MechatronicsRelay: int
    MechatronicsInclinometer: int
    MechatronicsAccelerometer: int
    MechatronicsPneumaticCylinder: int
    MechatronicsPneumaticValve: int
    MechatronicsHydraulicCylinder: int
    MechatronicsHydraulicValve: int
    MechatronicsRigidBody: int
    MechatronicsConstraint: int
    MechatronicsTransportSurface: int
    MechatronicsObjectSource: int
    MechatronicsObjectSink: int
    MechatronicsObjectTransformer: int
    MechatronicsObjectBehavior: int
    MechatronicsObjectData: int
    MechatronicsProxyObject: int
    MechatronicsSignal: int
    MechatronicsSnapPoint: int
    MechatronicsDynamicMaterial: int
    AllMotionSim: int
    AllMotionSimForceObjects: int
    AllMotionSimJoints: int
    MotionSimRoad: int
    MotionSimBearing: int
    MotionSimBearingProperty: int
    MotionSimControlPort: int
    MotionSimControlInput: int
    MotionSimPathFollower: int
    MotionSimControlOperation: int
    MotionSimControlOutput: int
    MotionSimGear: int
    MotionSimGearContact: int
    MotionSimAnimation: int
    MotionSimGraph: int
    MotionSimMlpp: int
    MotionSimCurveOperationRecord: int
    MotionSimMotionBodyDriver: int
    MotionSimLoadTransfer: int
    MotionSimJointDriver: int
    MotionSimStandaloneDriver: int
    MotionSimMechatronics: int
    MotionSimProfile: int
    MotionSimDiscreteDrivetrain: int
    MotionSimAnimationCamera: int
    MotionSimAutoflexProperty: int
    MotionSimBasicTireProperty: int
    MotionSimMotorcycleTireProperty: int
    MotionSimNonInertialTireProperty: int
    MotionSimFTireProperty: int
    MotionSimCDTireProperty: int
    MotionSimMFTyreAndMFSwiftTireProperty: int
    MotionSimTire: int
    MotionSimVehicleReporting: int
    MotionSimSuspensionReporting: int
    MotionSimInitialCondition: int
    MotionSimAnalyticalContact: int
    MotionSimAnalyticalContactProperty: int
    MotionSimSpring: int
    MotionSimRotationalSpring: int
    MotionSimTranslationalSpring: int
    MotionSimDamper: int
    MotionSimRotationalDamper: int
    MotionSimTranslationalDamper: int
    MotionSimSpringDamper: int
    MotionSimRotationalSpringDamper: int
    MotionSimTranslationalSpringDamper: int
    MotionSimSplineBeam: int
    MotionSimSplineBeamProperty: int
    MotionSimBeamSection: int
    MotionSimBeamForce: int
    MotionSimUserDefinedForce: int
    MotionSimFriction: int
    MotionSimThreePointForce: int
    MotionSimThreePointTorque: int
    MotionSimSubmechanism: int
    MotionSimSubmechanismPositioner: int
    MotionSimMotionConstraint: int
    MotionSimMotionBody: int
    MotionSimScalarForce: int
    MotionSimFlexibleBody: int
    MotionSimMarker: int
    MotionSimScalarTorque: int
    MotionSimCurveCurveContact: int
    MotionSimContact: int
    MotionSimBushing: int
    MotionSimBushingProperty: int
    MotionSimVectorForce: int
    MotionSimVectorTorque: int
    MotionSimSensor: int
    MotionSimMotor: int
    MotionSimMotionVector: int
    MotionSimMeasure: int
    MotionSimTrace: int
    MotionSimInterference: int
    MotionSimFixedJoint: int
    MotionSimScrewJoint: int
    MotionSimRevoluteJoint: int
    MotionSimSliderJoint: int
    MotionSimCylinderJoint: int
    MotionSimUniversalJoint: int
    MotionSimSphericalJoint: int
    MotionSimPlanarJoint: int
    MotionSimGearJoint: int
    MotionSimRackAndPinion: int
    MotionSimPointOnCurve: int
    MotionSimCurveOnCurve: int
    MotionSimCable: int
    MotionSimConstantVelocity: int
    MotionSimAtpointJoint: int
    MotionSimInlineJoint: int
    MotionSimInplaneJoint: int
    MotionSimOrientationJoint: int
    MotionSimParallelJoint: int
    MotionSimPerpendicularJoint: int
    MotionSimGeneralCoupler: int
    MotionSimMotionBodyCoupler: int
    MotionSimPlantInput: int
    MotionSimPlantOutput: int
    MotionSimSolutionStop: int
    MotionSimSignalChart: int
    MotionSimSolution: int
    MotionSimGearSpur: int
    MotionSimGearHelical: int
    MotionSimGearStraightBevel: int
    MotionSimGearSpiralBevel: int
    MotionSimGearHypoid: int
    MotionSimBumpStop: int
    MotionSimCompoundJoint: int
    MotionSimAnimationVector: int
    MotionSimHydrodynamicBearing: int
    MotionSimSprungMass: int
    MotionSimDiscreteDrivetrainReport: int
    MotionSimElectromagneticForce: int
    MotionSimGeneralSensor: int
    MotionSimContactPattern: int
    MotionSimFlexModalContent: int
    MotionSimFixedJointDriver: int
    MotionSimFrfInput: int
    MotionSimFrfOutput: int
    PhysicalDiagrammingAnnotation: int
    PhysicalDiagrammingConnection: int
    PhysicalDiagrammingNode: int
    BoundaryNode: int
    PIDAnnotation: int
    PIDConnection: int
    PIDSymbol: int
    PIDRun: int
    PIDBranch: int
    PIDSheet: int
    PIDSystem: int
    PressLineSimulationLineComponent: int
    PressLineSimulationPressModelRoot: int
    AllRoutingObjects: int
    RoutingControlPoint: int
    RoutingPort: int
    RoutingPartAnchor: int
    RoutingSegment: int
    RoutingStock: int
    AllShip: int
    AllShipPlateSystem: int
    AllShipProfileSystem: int
    ShipHull: int
    ShipDeck: int
    ShipTransverseBulkhead: int
    ShipLongitudinalBulkhead: int
    ShipGenericPlateSystem: int
    ShipStiffenerSystem: int
    ShipPillarSystem: int
    ShipEdgeReinforcement: int
    ShipSeam: int
    SketchRelation: int
    Sketch: int
    SketchFoundRelation: int
    SketchCoincidentRelation: int
    SketchConcentricRelation: int
    SketchPointOnCurveRelation: int
    SketchCollinearRelation: int
    SketchHorizontalRelation: int
    SketchHorizontalAlignmentRelation: int
    SketchVerticalRelation: int
    SketchVerticalAlignmentRelation: int
    SketchTangentRelation: int
    SketchParallelRelation: int
    SketchPerpendicularRelation: int
    SketchEqualLengthRelation: int
    SketchEqualRadiusRelation: int
    SketchSymmetricRelation: int
    SketchMidpointRelation: int
    SketchPointOnStringRelation: int
    SketchTangentToStringRelation: int
    SketchPerpendicularToStringRelation: int
    SketchUniformScaleRelation: int
    SketchG1SplineRelation: int
    SketchG2SplineRelation: int
    SketchTrimRelation: int
    SketchOffsetRelation: int
    SketchLinearPatternRelation: int
    SketchRectangularPatternRelation: int
    SketchCircularPatternRelation: int
    SketchGeneralPatternRelation: int
    SketchMirrorRelation: int
    SketchPolygonRelation: int
    SketchRigidGroupRelation: int
    SketchScalableGroupRelation: int
    SketchIgnoredRelation: int
    AllEdges: int
    AllFaces: int
    AllSolidBodies: int
    AllSheetBodies: int
    ConvergentSolidBody: int
    ConvergentSheetBody: int
    PlanarFace: int
    CylindricalFace: int
    ConicalFace: int
    SphericalFace: int
    ToroidalFace: int
    ParametricFace: int
    BlendedFace: int
    OffsetFace: int
    ExtrudedFace: int
    RevolvedFace: int
    ForeignFace: int
    ConvergentFace: int
    LinearEdge: int
    CircularEdge: int
    EllipticalEdge: int
    IntersectionEdge: int
    SplineEdge: int
    SPCurveEdge: int
    ForeignEdge: int
    ConstantParameterEdge: int
    ConvergentEdge: int
    ConvergentFacet: int
    StagedModelStage: int
    StagedModelStageSet: int
    StructureDesignMemberCorner: int
    TechnicalDataPackagePage: int
    TechnicalDataPackageViewport: int
    TechnicalDataPackageViewCarousel: int
    TechnicalDataPackageRectangle: int
    TechnicalDataPackagePDFFormField: int
    TechnicalDataPackageAutomaticTable: int
    TechnicalDataPackageViewList: int
    TechnicalDataPackagePrintView: int
    TechnicalDataPackageDiagramArea: int
    AllViews: int
    SectionView: int
    ImportedView: int
    OrthographicView: int
    AuxiliaryView: int
    DetailView: int
    DrawingSheetView: int
    ImportedPMILightweightSectionView: int
    AllBodyInWhiteDatums: int
    AllWeldingObjects: int
    AllWeldingMeasurementObjects: int
    GrooveWeld: int
    FilletWeld: int
    ResistanceSpotWeld: int
    ArcSpotWeld: int
    NutWeld: int
    StudWeld: int
    MechanicalClinchWeld: int
    DollopWeld: int
    Custom1Weld: int
    Custom2Weld: int
    Custom3Weld: int
    Custom4Weld: int
    Custom5Weld: int
    UserDefinedWeld: int
    FillWeld: int
    WeldingJoint: int
    WeldBead: int
    WeldPlugSlot: int
    SurfaceWeld: int
    TranslateWeld: int
    JointMarkWeld: int
    CompoundWeld: int
    DatumSurface: int
    DatumPin: int
    DatumCustom1: int
    DatumCustom2: int
    DatumCustom3: int
    MeasurementSurface: int
    MeasurementHole: int
    MeasurementStud: int
    MeasurementSlot: int
    MeasurementTrim: int
    MeasurementHemmedEdge: int
    MeasurementCustom1: int
    MeasurementCustom2: int
    MeasurementCustom3: int
    AllConicCurves: int
    AllCurves: int
    Point: int
    PointCloud: int
    Line: int
    Arc: int
    Ellipse: int
    Parabola: int
    Hyperbola: int
    Spline: int
    Polyline: int
    Stroke: int
    CompositesLaminate: int
    CompositesPly: int
    AllCompositesObjects: int
    AECGridLine: int
    AECLevelLine: int
    AECSymbol: int
    AECLineFormat: int
    ## Returns enum member equivalent to the value passed. Useful for bit operations of enum members.
    ## <param name="value" type="int"> Any integer value or bit operation result of enum </param>
    @staticmethod
    def ValueOf(value: int) -> FilterMember:
        """
        Returns enum member equivalent to the value passed. Useful for bit operations of enum members.
        """
        pass


## @package NXOpen.Select
## Classes, Enums and Structs under NXOpen.Select namespace

