//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     AnimationDesigner_PointOnCurveKinematicsChain.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/libanimationdesigneropencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace AnimationDesigner
    {
        class PointOnCurveKinematicsChain;
    }
    class DisplayableObject;
    namespace AnimationDesigner
    {
        class _PointOnCurveKinematicsChainBuilder;
        class PointOnCurveKinematicsChainImpl;
        /** @brief  Represents a Point On Curve Kinematics Chain feature.  

          <br> To create or edit an instance of this class, use @link NXOpen::AnimationDesigner::PointOnCurveKinematicsChainBuilder  NXOpen::AnimationDesigner::PointOnCurveKinematicsChainBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class ANIMATIONDESIGNEROPENCPPEXPORT  PointOnCurveKinematicsChain : public NXOpen::DisplayableObject
        {
            private: PointOnCurveKinematicsChainImpl * m_pointoncurvekinematicschain_impl;
            private: friend class  _PointOnCurveKinematicsChainBuilder;
            protected: PointOnCurveKinematicsChain();
            public: ~PointOnCurveKinematicsChain();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
