//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CableRouter_Managed_EditCablePropertiesBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_cablerouter_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CableRouter
    {
        namespace Managed
        {
            class EditCablePropertiesBuilder;
        }
    }
    class Builder;
    class SelectTaggedObject;
    class SelectTaggedObjectList;
    namespace CableRouter
    {
        namespace Managed
        {
            class _EditCablePropertiesBuilderBuilder;
            class EditCablePropertiesBuilderImpl;

            /// \cond NX_NO_DOC 
            /** Represents a builder class that performs Edit Cable Properties operations.
                         <br> To create a new instance of this class, use @link NXOpen::CableRouter::CableRouterCollection::CreateManagedEditCablePropertiesBuilder  NXOpen::CableRouter::CableRouterCollection::CreateManagedEditCablePropertiesBuilder @endlink  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_CABLEROUTEREXPORT  EditCablePropertiesBuilder : public NXOpen::Builder
            {
                private: EditCablePropertiesBuilderImpl * m_editcablepropertiesbuilder_impl;
                private: friend class  _EditCablePropertiesBuilderBuilder;
                protected: EditCablePropertiesBuilder();
                public: ~EditCablePropertiesBuilder();

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectFromPort
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectFromNode
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double FromDirectDistance
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetFromDirectDistance
                (
                    double fromDirectDistance /** fromdirectdistance */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectToPort
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectToNode
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double ToDirectDistance
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetToDirectDistance
                (
                    double toDirectDistance /** todirectdistance */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double LengthCorrectionFactor
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetLengthCorrectionFactor
                (
                    double lengthCorrectionFactor /** lengthcorrectionfactor */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double FromEndExtraLength
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetFromEndExtraLength
                (
                    double fromEndExtraLength /** fromendextralength */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: double ToEndExtraLength
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Sets  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_cable_router (" NX Cable Router") */
                public: void SetToEndExtraLength
                (
                    double toEndExtraLength /** toendextralength */ 
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObjectList * SelectSeparateCable
                (
                );

                /// \endcond 

                /// \cond NX_NO_DOC 
                /**Returns  This is an internal API and can be changed at any time 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObjectList * SelectGroupedCable
                (
                );

                /// \endcond 
            };

            /// \endcond 
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
