//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CableRouter_Managed_Device.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CableRouter_Managed_BaseData.hxx>
#include <NXOpen/libnxopencpp_cablerouter_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CableRouter
    {
        namespace Managed
        {
            class Device;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class BaseData;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class _DeviceBuilder;
            class DeviceImpl;

            /// \cond NX_NO_DOC 
            /** Represents the Device class.  <br> To create or edit an instance of this class, use @link NXOpen::CableRouter::Managed::DeviceBuilder  NXOpen::CableRouter::Managed::DeviceBuilder @endlink  <br> 
             <br>  Created in NX2406.0.0.  <br>  
            */
            class NXOPENCPP_CABLEROUTEREXPORT  Device : public NXOpen::CableRouter::Managed::BaseData
            {
                private: DeviceImpl * m_device_impl;
                private: friend class  _DeviceBuilder;
                protected: Device();
                public: ~Device();
            };

            /// \endcond 
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
