//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CableRouter_ObjectManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_cablerouter_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CableRouter
    {
        class ObjectManager;
    }
    class Part;
    namespace CableRouter
    {
        namespace Managed
        {
            class CableCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class CablewayAssemblyCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class ContainerCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class DeviceCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class LineSegmentCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class NodeCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class PortCollection;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class RoutingOperations;
        }
    }
    namespace CableRouter
    {
        namespace Managed
        {
            class StructuralItemCollection;
        }
    }
    namespace CableRouter
    {
        class ObjectManagerImpl;

        /// \cond NX_NO_DOC 
        /** A manager to deal with all objects.  <br> To obtain an instance of this class, refer to @link NXOpen::Part  NXOpen::Part @endlink  <br> 
         <br>  Created in NX2406.0.0.  <br>  
        */
        class NXOPENCPP_CABLEROUTEREXPORT  ObjectManager
        {
            private: ObjectManagerImpl * m_objectmanager_impl;
            private: NXOpen::Part* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit ObjectManager(NXOpen::Part *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~ObjectManager();



            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::NodeCollection *Nodes();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::DeviceCollection *Devices();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::LineSegmentCollection *LineSegments();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::CableCollection *Cables();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::ContainerCollection *Containers();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::PortCollection *Ports();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::RoutingOperations *RoutingOperations();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::StructuralItemCollection *StructuralItems();

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2406.0.0.  <br>  
            */
            public: NXOpen::CableRouter::Managed::CablewayAssemblyCollection *CablewayAssemblies();

            /// \endcond 
        }; //lint !e1712 default constructor not defined for class  


        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
