//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_ModelAndLoadPreProcessSectorToFullSectionBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_ModelAndLoadPreProcessOperationBuilder.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class ModelAndLoadPreProcessSectorToFullSectionBuilder;
    }
    namespace CAE
    {
        class ModelAndLoadPreProcessOperationBuilder;
    }
    class CoordinateSystem;
    namespace CAE
    {
        class _ModelAndLoadPreProcessSectorToFullSectionBuilderBuilder;
        class ModelAndLoadPreProcessSectorToFullSectionBuilderImpl;
        /**
            Builds a @link NXOpen::CAE::ModelAndLoadPreProcessSectorToFullSectionBuilder NXOpen::CAE::ModelAndLoadPreProcessSectorToFullSectionBuilder@endlink  object which 
            represets an operation.
             <br> There is no kf creator for this.  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  ModelAndLoadPreProcessSectorToFullSectionBuilder : public NXOpen::CAE::ModelAndLoadPreProcessOperationBuilder
        {
            private: ModelAndLoadPreProcessSectorToFullSectionBuilderImpl * m_modelandloadpreprocesssectortofullsectionbuilder_impl;
            private: friend class  _ModelAndLoadPreProcessSectorToFullSectionBuilderBuilder;
            protected: ModelAndLoadPreProcessSectorToFullSectionBuilder();
            public: ~ModelAndLoadPreProcessSectorToFullSectionBuilder();
            /** Autodetect sector boundaries and setup primary and secondary periodic nodes and rotation axis 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void AutodetectSectorBoundaries
            (
            );
            /** 
             <br>  @deprecated Deprecated in NX2406.0.0.  Use @link NXOpen::CAE::ModelAndLoadPreProcessSectorToFullSectionBuilder::ReverseDirection NXOpen::CAE::ModelAndLoadPreProcessSectorToFullSectionBuilder::ReverseDirection@endlink  instead. <br>  

             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NX_DEPRECATED("Deprecated in NX2406.0.0.  Use NXOpen::CAE::ModelAndLoadPreProcessSectorToFullSectionBuilder::ReverseDirection instead.") void ReverseZCAxis
            (
            );
            /** Reverse direction of the mirroring operation 
             <br>  Created in NX2406.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void ReverseDirection
            (
            );
            /**Returns  the primary periodic node on sector boundary of transient mesh 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int PrimarySelectionNodeLabel
            (
            );
            /**Sets  the primary periodic node on sector boundary of transient mesh 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetPrimarySelectionNodeLabel
            (
                int primarySelectionNodeLabel /** primaryselectionnodelabel */ 
            );
            /**Returns  the secondary periodic node on sector boundary of transient mesh 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int SecondarySelectionNodeLabel
            (
            );
            /**Sets  the secondary periodic node on sector boundary of transient mesh 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetSecondarySelectionNodeLabel
            (
                int secondarySelectionNodeLabel /** secondaryselectionnodelabel */ 
            );
            /**Returns  the center of sector and rotation axis as Csys. 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CoordinateSystem * RotationCsys
            (
            );
            /**Sets  the center of sector and rotation axis as Csys. 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetRotationCsys
            (
                NXOpen::CoordinateSystem * rotationCsys /** rotationcsys */ 
            );
            /**Returns  the option for discarding unmapped nodes from data export. 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: bool DoMirroring
            (
            );
            /**Sets  the option for discarding unmapped nodes from data export. 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetDoMirroring
            (
                bool doMirroring /** domirroring */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
