//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CollaborationApplication_CollaborationZoneMgr.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/CollaborationApplication_BoxShape.hxx>
#include <NXOpen/CollaborationApplication_BoxShapeBuilder.hxx>
#include <NXOpen/CollaborationApplication_NotificationZone.hxx>
#include <NXOpen/CollaborationApplication_NotificationZoneBuilder.hxx>
#include <NXOpen/TransientObject.hxx>
#include <NXOpen/libnxopencpp_collaborationapplication_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CollaborationApplication
    {
        class CollaborationZoneMgr;
    }
    namespace CollaborationApplication
    {
        class BoxShape;
    }
    namespace CollaborationApplication
    {
        class BoxShapeBuilder;
    }
    namespace CollaborationApplication
    {
        class CollaborationZone;
    }
    namespace CollaborationApplication
    {
        class NotificationZone;
    }
    namespace CollaborationApplication
    {
        class NotificationZoneBuilder;
    }
    class Part;
    namespace CollaborationApplication
    {
    }
    namespace CollaborationApplication
    {
        class CollaborationZoneMgrImpl;

        /// \cond NX_NO_DOC 
        /** Represents the collaboration zone manager. 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_COLLABORATIONAPPLICATIONEXPORT  CollaborationZoneMgr : public NXOpen::TransientObject
        {
            private: CollaborationZoneMgrImpl * m_collaborationzonemgr_impl;
            /// \cond NX_NO_DOC 
            public: explicit CollaborationZoneMgr(void *ptr);
            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: NXOpen::CollaborationApplication::BoxShapeBuilder * CreateBoxShapeBuilder
            (
                NXOpen::Part * part /** part */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: NXOpen::CollaborationApplication::BoxShapeBuilder * CreateBoxShapeBuilderToEdit
            (
                NXOpen::CollaborationApplication::BoxShape * shape /** shape */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: NXOpen::CollaborationApplication::NotificationZoneBuilder * CreateNotificationZoneBuilder
            (
                NXOpen::Part * part /** part */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: NXOpen::CollaborationApplication::NotificationZoneBuilder * CreateNotificationZoneBuilderToEdit
            (
                NXOpen::CollaborationApplication::NotificationZone * zone /** zone */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void DeleteNotificationZones
            (
                const std::vector<NXOpen::CollaborationApplication::NotificationZone *> & zonesToDelete /** zonestodelete */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void ShowNotificationZones
            (
                const std::vector<NXOpen::CollaborationApplication::NotificationZone *> & zonesToShow /** zonestoshow */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void HideNotificationZones
            (
                const std::vector<NXOpen::CollaborationApplication::NotificationZone *> & zonesToHide /** zonestohide */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: std::vector<NXOpen::CollaborationApplication::CollaborationZone *> FetchZonesFromDatabase
            (
                NXOpen::Part * part /** part */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: virtual ~CollaborationZoneMgr();

            /// \endcond 
        }; //lint !e1712 default constructor not defined for class  


        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
