//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CollaborationApplication_BoxShapeBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_collaborationapplication_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CollaborationApplication
    {
        class BoxShapeBuilder;
    }
    class Builder;
    namespace CollaborationApplication
    {
        class _BoxShapeBuilderBuilder;
        class BoxShapeBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Represents the builder to create a @link NXOpen::CollaborationApplication::BoxShape NXOpen::CollaborationApplication::BoxShape@endlink  object.  <br> To create a new instance of this class, use @link NXOpen::CollaborationApplication::CollaborationZoneMgr::CreateBoxShapeBuilder  NXOpen::CollaborationApplication::CollaborationZoneMgr::CreateBoxShapeBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_COLLABORATIONAPPLICATIONEXPORT  BoxShapeBuilder : public NXOpen::Builder
        {
            private: BoxShapeBuilderImpl * m_boxshapebuilder_impl;
            private: friend class  _BoxShapeBuilderBuilder;
            protected: BoxShapeBuilder();
            public: ~BoxShapeBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: double Length
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void SetLength
            (
                double length /** length */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: double Width
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void SetWidth
            (
                double width /** width */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: double Height
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : nx_mu_notifications (" NX Multi-User Notifications") */
            public: void SetHeight
            (
                double height /** height */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
