//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Composites_AddPlyPieceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libcompositesopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Composites
    {
        class AddPlyPieceBuilder;
    }
    class Builder;
    namespace Composites
    {
        class SelectPly;
    }
    namespace Features
    {
        class Feature;
    }
    namespace Composites
    {
        class _AddPlyPieceBuilderBuilder;
        class AddPlyPieceBuilderImpl;
        /**
            Creates or edits a @link Composites::PlyPiece Composites::PlyPiece@endlink  object.
             <br> To create a new instance of this class, use @link NXOpen::Composites::Manager::CreateAddPlyPieceBuilder  NXOpen::Composites::Manager::CreateAddPlyPieceBuilder @endlink  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class COMPOSITESOPENCPPEXPORT  AddPlyPieceBuilder : public NXOpen::Builder
        {
            private: AddPlyPieceBuilderImpl * m_addplypiecebuilder_impl;
            private: friend class  _AddPlyPieceBuilderBuilder;
            protected: AddPlyPieceBuilder();
            public: ~AddPlyPieceBuilder();
            /**Returns  the @link Composites::Ply Composites::Ply@endlink  to be spliced. 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: NXOpen::Composites::SelectPly * Ply
            (
            );
            /**Returns  the selected @link Composites::Features::Region Composites::Features::Region@endlink , defining the extents of the @link Composites::PlyPiece Composites::PlyPiece@endlink 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: NXOpen::Features::Feature * BoundaryRegion
            (
            );
            /**Sets  the selected @link Composites::Features::Region Composites::Features::Region@endlink , defining the extents of the @link Composites::PlyPiece Composites::PlyPiece@endlink 
             <br>  Created in NX1926.0.0.  <br>  
             <br> License requirements : nx_composites (" Composites") */
            public: void SetBoundaryRegion
            (
                NXOpen::Features::Feature * region /** region */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
