//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Diagramming_FillBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Diagramming_SheetElementBuilder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_diagramming_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Diagramming
    {
        class FillBuilder;
    }
    namespace Diagramming
    {
        namespace Geometry
        {
            class SelectBaseGeometryList;
        }
    }
    namespace Diagramming
    {
        class SheetElementBuilder;
    }
    namespace Diagramming
    {
        class _FillBuilderBuilder;
        class FillBuilderImpl;
        /**
            Represents a FillBuilder.
             <br> To create a new instance of this class, use @link NXOpen::Diagramming::FillCollection::CreateFillBuilder  NXOpen::Diagramming::FillCollection::CreateFillBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_DIAGRAMMINGEXPORT  FillBuilder : public NXOpen::Diagramming::SheetElementBuilder
        {
            private: FillBuilderImpl * m_fillbuilder_impl;
            private: friend class  _FillBuilderBuilder;
            protected: FillBuilder();
            public: ~FillBuilder();
            /**Returns  the boundary geometries
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Diagramming::Geometry::SelectBaseGeometryList * Geometries
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
