//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DiagrammingLibraryAuthor_LineTypeAuthoringBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DiagrammingLibraryAuthor_LineTypeBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/libnxopencpp_diagramminglibraryauthor_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DiagrammingLibraryAuthor
    {
        class LineTypeAuthoringBuilder;
    }
    class Builder;
    namespace DiagrammingLibraryAuthor
    {
        class LineTypeBuilder;
    }
    namespace DiagrammingLibraryAuthor
    {
        class LineTypeBuilderList;
    }
    namespace DiagrammingLibraryAuthor
    {
        class _LineTypeAuthoringBuilderBuilder;
        class LineTypeAuthoringBuilderImpl;
        /**  @brief  Represents a LineTypeAuthoringBuilder.  

          
                Calling @link Builder::Commit Builder::Commit@endlink  on this builder will only return NULL.  <br> To create a new instance of this class, use @link NXOpen::DiagrammingLibraryAuthor::SymbolDesignerManager::CreateLineTypeAuthoringBuilder  NXOpen::DiagrammingLibraryAuthor::SymbolDesignerManager::CreateLineTypeAuthoringBuilder @endlink  <br> 
         <br>  Created in NX2212.3000.0.  <br>  
        */
        class NXOPENCPP_DIAGRAMMINGLIBRARYAUTHOREXPORT  LineTypeAuthoringBuilder : public NXOpen::Builder
        {
            private: LineTypeAuthoringBuilderImpl * m_linetypeauthoringbuilder_impl;
            private: friend class  _LineTypeAuthoringBuilderBuilder;
            protected: LineTypeAuthoringBuilder();
            public: ~LineTypeAuthoringBuilder();
            /** Creates a new line type 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DiagrammingLibraryAuthor::LineTypeBuilder * CreateLineType
            (
            );
            /**Returns  the list of line types. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DiagrammingLibraryAuthor::LineTypeBuilderList * LineTypes
            (
            );
            /**Returns  the output folder for generated files. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: NXString OutputFolder
            (
            );
            /**Sets  the output folder for generated files. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: void SetOutputFolder
            (
                const NXString & outputFolder /** outputfolder */ 
            );
            /**Sets  the output folder for generated files. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            void SetOutputFolder
            (
                const char * outputFolder /** outputfolder */ 
            );
            /**Returns  the discipline of the object. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: NXString Discipline
            (
            );
            /**Sets  the discipline of the object. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            public: void SetDiscipline
            (
                const NXString & discipline /** discipline */ 
            );
            /**Sets  the discipline of the object. 
             <br>  Created in NX2212.3000.0.  <br>  
             <br> License requirements : None */
            void SetDiscipline
            (
                const char * discipline /** discipline */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
