//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Document_ArcBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Diagramming_Geometry_ArcBuilder.hxx>
#include <NXOpen/Document_BaseObjectBuilder.hxx>
#include <NXOpen/libdocumentopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Document
    {
        class ArcBuilder;
    }
    namespace Diagramming
    {
        namespace Geometry
        {
            class ArcBuilder;
        }
    }
    namespace Document
    {
        class BaseObjectBuilder;
    }
    namespace Document
    {
        class _ArcBuilderBuilder;
        class ArcBuilderImpl;
        /** Represents a BaseObjectBuilder  <br> To create a new instance of this class, use @link NXOpen::Document::ArcCollection::CreateArcBuilder  NXOpen::Document::ArcCollection::CreateArcBuilder @endlink  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class DOCUMENTOPENCPPEXPORT  ArcBuilder : public NXOpen::Document::BaseObjectBuilder
        {
            private: ArcBuilderImpl * m_arcbuilder_impl;
            private: friend class  _ArcBuilderBuilder;
            protected: ArcBuilder();
            public: ~ArcBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Diagramming::Geometry::ArcBuilder * Geometry
            (
            );

            /// \endcond 
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
