//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Fabric_Features_ShoeHole.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_BodyFeature.hxx>
#include <NXOpen/libfabricopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Fabric
    {
        namespace Features
        {
            class ShoeHole;
        }
    }
    namespace Features
    {
        class BodyFeature;
    }
    namespace Fabric
    {
        namespace Features
        {
            class _ShoeHoleBuilder;
            class ShoeHoleImpl;

            /// \cond NX_NO_DOC 
            /** Represents a Shoe Hole feature <br> To create or edit an instance of this class, use @link NXOpen::Fabric::Features::ShoeHoleBuilder  NXOpen::Fabric::Features::ShoeHoleBuilder @endlink  <br> 
             <br>  Created in NX2212.0.0.  <br>  
            */
            class FABRICOPENCPPEXPORT  ShoeHole : public NXOpen::Features::BodyFeature
            {
                private: ShoeHoleImpl * m_shoehole_impl;
                private: friend class  _ShoeHoleBuilder;
                protected: ShoeHole();
                public: ~ShoeHole();
            };

            /// \endcond 
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
