//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_AECDesign_BIMClassificationBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace AECDesign
        {
            class BIMClassificationBuilder;
        }
    }
    class Builder;
    class Part;
    namespace Features
    {
        namespace AECDesign
        {
            class _BIMClassificationBuilderBuilder;
            class BIMClassificationBuilderImpl;
            /**  @brief 
                Represents a classify component builder for AEC.
                 

             
                
                This builder is used to classify component in AEC. 
                
                 <br> To create a new instance of this class, use @link NXOpen::Features::AECDesignCollection::CreateBimclassificationBuilder  NXOpen::Features::AECDesignCollection::CreateBimclassificationBuilder @endlink  <br> 
            Default values.
            <list type="table"> 
             
            <listheader><term> 
            Property</term>  <description> 
            Value</description> </listheader>
            <item><term> 
             
            PropertiesRequisiteType </term> <description> 
             
            All </description> </item> 

            </list> 

             <br>  Created in NX2212.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  BIMClassificationBuilder : public NXOpen::Builder
            {
                /**Specify display property type*/
                public: enum RequisiteTypes
                {
                    RequisiteTypesAll/**Lists all available properties            */,
                    RequisiteTypesMandatory/**Lists only the mandatory properties  */,
                    RequisiteTypesOptional/**Lists only the optional properties    */,
                    RequisiteTypesUserDefined/** user defined */ 
                };

                private: BIMClassificationBuilderImpl * m_bimclassificationbuilder_impl;
                private: friend class  _BIMClassificationBuilderBuilder;
                protected: BIMClassificationBuilder();
                public: ~BIMClassificationBuilder();
                /**Returns  the component type 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: int ComponentType
                (
                );
                /**Sets  the component type 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetComponentType
                (
                    int componentType /** componenttype */ 
                );
                /** Gets the select parts 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void GetSelectParts
                (
                    std::vector<NXOpen::Part *> & selectParts /** selectparts */ 
                );
                /** Sets the selected parts. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetSelectParts
                (
                    const std::vector<NXOpen::Part *> & selectParts /** selectparts */ 
                );
                /** Sets reclassify 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetReclassify
                (
                    bool isReclassify /** isreclassify */ 
                );
                /**Returns  the properties filter type 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::BIMClassificationBuilder::RequisiteTypes PropertiesRequisiteType
                (
                );
                /**Sets  the properties filter type 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetPropertiesRequisiteType
                (
                    NXOpen::Features::AECDesign::BIMClassificationBuilder::RequisiteTypes propertiesRequisiteType /** propertiesrequisitetype */ 
                );
                /**Returns the currently selected category name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString Category
                (
                );
                /**Sets the currently selected category name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetCategory
                (
                    const NXString & category /** category */ 
                );
                /**Sets the currently selected category name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetCategory
                (
                    const char * category /** category */ 
                );
                /**Returns the currently accessing property name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString Property
                (
                );
                /**Sets the currently accessing property name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetProperty
                (
                    const NXString & propertyName /** propertyname */ 
                );
                /**Sets the currently accessing property name. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetProperty
                (
                    const char * propertyName /** propertyname */ 
                );
                /**Returns the string value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString StringValue
                (
                );
                /**Sets the string value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetStringValue
                (
                    const NXString & stringValue /** stringvalue */ 
                );
                /**Sets the string value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetStringValue
                (
                    const char * stringValue /** stringvalue */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetStringValueAndTypeAsPropertyName
                (
                    const NXString & propertyName /** propertyname */ ,
                    const NXString & stringValue /** stringvalue */ ,
                    const NXString & strDataType /** strdatatype */ ,
                    const NXString & strRequisite /** strrequisite */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetStringValueAndTypeAsPropertyName
                (
                    const char * propertyName /** propertyname */ ,
                    const char * stringValue /** stringvalue */ ,
                    const char * strDataType /** strdatatype */ ,
                    const char * strRequisite /** strrequisite */ 
                );
                /**Returns the double value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: double DoubleValue
                (
                );
                /**Sets the double value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetDoubleValue
                (
                    double doubleValue /** doublevalue */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetDoubleValueAndTypeAsPropertyName
                (
                    const NXString & propertyName /** propertyname */ ,
                    double doubleValue /** doublevalue */ ,
                    const NXString & strDataType /** strdatatype */ ,
                    const NXString & strRequisite /** strrequisite */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetDoubleValueAndTypeAsPropertyName
                (
                    const char * propertyName /** propertyname */ ,
                    double doubleValue /** doublevalue */ ,
                    const char * strDataType /** strdatatype */ ,
                    const char * strRequisite /** strrequisite */ 
                );
                /**Returns the int value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: int IntValue
                (
                );
                /**Sets the int value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetIntValue
                (
                    int intValue /** intvalue */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetIntValueAndTypeAsPropertyName
                (
                    const NXString & propertyName /** propertyname */ ,
                    int intValue /** intvalue */ ,
                    const NXString & strDataType /** strdatatype */ ,
                    const NXString & strRequisite /** strrequisite */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetIntValueAndTypeAsPropertyName
                (
                    const char * propertyName /** propertyname */ ,
                    int intValue /** intvalue */ ,
                    const char * strDataType /** strdatatype */ ,
                    const char * strRequisite /** strrequisite */ 
                );
                /**Returns the bool value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : None */
                public: bool BoolValue
                (
                );
                /**Sets the bool value of currently accessing property. 
                 <br>  Created in NX2212.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetBoolValue
                (
                    bool boolValue /** boolvalue */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                public: void SetBoolValueAndTypeAsPropertyName
                (
                    const NXString & propertyName /** propertyname */ ,
                    bool boolValue /** boolvalue */ ,
                    const NXString & strDataType /** strdatatype */ ,
                    const NXString & strRequisite /** strrequisite */ 
                );
                /** Sets the variant type and value as property name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : nx_bim ("AEC Design") */
                void SetBoolValueAndTypeAsPropertyName
                (
                    const char * propertyName /** propertyname */ ,
                    bool boolValue /** boolvalue */ ,
                    const char * strDataType /** strdatatype */ ,
                    const char * strRequisite /** strrequisite */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
