//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_AssociateObjectBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_SheetMetal_AssociateObjectInputListItemBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class AssociateObjectBuilder;
        }
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class AssociateObjectInputListItemBuilder;
        }
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class AssociateObjectInputListItemBuilderList;
        }
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class _AssociateObjectBuilderBuilder;
            class AssociateObjectBuilderImpl;
            /** Represents a @link Features::SheetMetal::AssociateObjectBuilder Features::SheetMetal::AssociateObjectBuilder@endlink   <br> To create a new instance of this class, use @link NXOpen::Features::SheetMetal::SheetmetalManager::CreateAssociateObjectBuilder  NXOpen::Features::SheetMetal::SheetmetalManager::CreateAssociateObjectBuilder @endlink  <br> 
             <br>  Created in NX1872.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  AssociateObjectBuilder : public NXOpen::Features::FeatureBuilder
            {
                /** enum for feature option type */
                public: enum LinkedBodyFeatureOptions
                {
                    LinkedBodyFeatureOptionsOneForEachComponent/** An option to create one extracted or linked body feature for all selected bodies within same component as body collector */,
                    LinkedBodyFeatureOptionsOneForEachBody/** An option to create a separate extracted or linked body feature per single body */
                };

                private: AssociateObjectBuilderImpl * m_associateobjectbuilder_impl;
                private: friend class  _AssociateObjectBuilderBuilder;
                protected: AssociateObjectBuilder();
                public: ~AssociateObjectBuilder();
                /**Returns  the input list associated to current Associate Object Builder, containing elements of type 
                            @link Features::SheetMetal::AssociateObjectInputListItemBuilder Features::SheetMetal::AssociateObjectInputListItemBuilder@endlink . 
                 <br>  Created in NX1872.0.0.  <br>  
                 <br> License requirements : nx_flexible_pcb ("NX Flexible PCB") */
                public: NXOpen::Features::SheetMetal::AssociateObjectInputListItemBuilderList * InputList
                (
                );
                /** Creates a new list item of type @link Features::SheetMetal::AssociateObjectInputListItemBuilder Features::SheetMetal::AssociateObjectInputListItemBuilder@endlink  or 
                             will return an list item associated with current Associate Object Builder. 
                 <br>  Created in NX1872.0.0.  <br>  
                 <br> License requirements : nx_flexible_pcb ("NX Flexible PCB") */
                public: NXOpen::Features::SheetMetal::AssociateObjectInputListItemBuilder * CreateAssociateObjectInputListItemBuilder
                (
                );
                /**Returns  the Linked Body Features option type 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::AssociateObjectBuilder::LinkedBodyFeatureOptions LinkedBodyOption
                (
                );
                /**Sets  the Linked Body Features option type 
                 <br>  Created in NX2406.0.0.  <br>  
                 <br> License requirements : nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetLinkedBodyOption
                (
                    NXOpen::Features::SheetMetal::AssociateObjectBuilder::LinkedBodyFeatureOptions featureOptionType /** featureoptiontype */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
