//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_AECDesign_LongitudinalRebarsBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_AECDesign_MaterialSectionBuilder.hxx>
#include <NXOpen/Features_AECDesign_RebarHookBlockBuilder.hxx>
#include <NXOpen/Features_AECDesign_RebarLimitBuilder.hxx>
#include <NXOpen/Features_AECDesign_RebarsBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace AECDesign
        {
            class LongitudinalRebarsBuilder;
        }
    }
    class Expression;
    namespace Features
    {
        namespace AECDesign
        {
            class MaterialSectionBuilder;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class RebarHookBlockBuilder;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class RebarLimitBuilder;
        }
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        class SelectFeatureList;
    }
    class ScCollector;
    class Section;
    namespace Features
    {
        namespace AECDesign
        {
            class _LongitudinalRebarsBuilderBuilder;
            class LongitudinalRebarsBuilderImpl;
            /**  @brief 
                    Represents a longitudinal rebars builder for AEC Design. 
                     

             
                    
                    This builder is used to create longitudinal rebars feature in AEC Design.
                    
                 <br> To create a new instance of this class, use @link NXOpen::Features::AECDesignCollection::CreateAecLongitudinalRebarsBuilder  NXOpen::Features::AECDesignCollection::CreateAecLongitudinalRebarsBuilder @endlink  <br> 
             <br>  Created in NX2312.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  LongitudinalRebarsBuilder : public NXOpen::Features::FeatureBuilder
            {
                private: LongitudinalRebarsBuilderImpl * m_longitudinalrebarsbuilder_impl;
                private: friend class  _LongitudinalRebarsBuilderBuilder;
                protected: LongitudinalRebarsBuilder();
                public: ~LongitudinalRebarsBuilder();
                /**Returns  the placement method used to locate the longitudinal rebars. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarsBuilder::LongitudinalCreationMethod PlacementMethod
                (
                );
                /**Sets  the placement method used to locate the longitudinal rebars. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : nx_concrete ("Concrete Design") */
                public: void SetPlacementMethod
                (
                    NXOpen::Features::AECDesign::RebarsBuilder::LongitudinalCreationMethod placementMethod /** placementmethod */ 
                );
                /**Returns  the start face. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::ScCollector * StartFace
                (
                );
                /**Returns  the select edge. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::ScCollector * SelectEdge
                (
                );
                /**Returns  the specify point 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Section * SpecifyPoint
                (
                );
                /**Returns  the select crossing features. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SelectFeatureList * CrossingRebarsFeature
                (
                );
                /**Returns  the start limit. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarLimitBuilder * StartLimit
                (
                );
                /**Returns  the end limit. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarLimitBuilder * EndLimit
                (
                );
                /**Returns  the materialSection. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::MaterialSectionBuilder * MaterialSection
                (
                );
                /**Returns  the diameter. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Diameter
                (
                );
                /**Returns  the space setting. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarsBuilder::PatternOption PatternSetting
                (
                );
                /**Sets  the space setting. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : nx_concrete ("Concrete Design") */
                public: void SetPatternSetting
                (
                    NXOpen::Features::AECDesign::RebarsBuilder::PatternOption patternSetting /** patternsetting */ 
                );
                /** Rotate the rebar 90 degrees. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : nx_concrete ("Concrete Design") */
                public: void AlternateSolution
                (
                );
                /**Returns  the number of rebars. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: int NumberOfRebars
                (
                );
                /**Sets  the number of rebars. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : nx_concrete ("Concrete Design") */
                public: void SetNumberOfRebars
                (
                    int numberOfRebars /** numberofrebars */ 
                );
                /**Returns  the start faces thickness. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * StartFacesThickness
                (
                );
                /**Returns  the end faces thickness. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * EndFacesThickness
                (
                );
                /**Returns  the start hook. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarHookBlockBuilder * StartHook
                (
                );
                /**Returns  the end hook. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::AECDesign::RebarHookBlockBuilder * EndHook
                (
                );
                /** Updates referenced columns. 
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : nx_concrete ("Concrete Design") */
                public: void UpdateReferencedRebarBodies
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
