//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Join_MultiEditCurveJoinParametersBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libjoinopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Join
    {
        class MultiEditCurveJoinParametersBuilder;
    }
    class Builder;
    namespace Weld
    {
        class JointExitBuilder;
    }
    namespace Join
    {
        class _MultiEditCurveJoinParametersBuilderBuilder;
        class MultiEditCurveJoinParametersBuilderImpl;
        /** Represents a MultiEditCurveJoinParametersBuilder class  <br> To create a new instance of this class, use @link NXOpen::Join::JoinManager::CreateMultiEditCurveJoinParametersBuilder  NXOpen::Join::JoinManager::CreateMultiEditCurveJoinParametersBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class JOINOPENCPPEXPORT  MultiEditCurveJoinParametersBuilder : public NXOpen::Builder
        {
            private: MultiEditCurveJoinParametersBuilderImpl * m_multieditcurvejoinparametersbuilder_impl;
            private: friend class  _MultiEditCurveJoinParametersBuilderBuilder;
            protected: MultiEditCurveJoinParametersBuilder();
            public: ~MultiEditCurveJoinParametersBuilder();

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_join (" NX Join") */
            public: void SetRowChanged
            (
                int row /** row of cell */
            );

            /// \endcond 
            /** Reset the values of @link NXOpen::Weld::JointExitBuilder NXOpen::Weld::JointExitBuilder@endlink  to the callback values. 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_join (" NX Join") */
            public: void ResetToCallbackValues
            (
                NXOpen::Weld::JointExitBuilder * exitBuilder /** exitbuilder */ 
            );
            /** Get the @link NXOpen::Weld::JointExitBuilder NXOpen::Weld::JointExitBuilder@endlink . 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : nx_join (" NX Join") */
            public: NXOpen::Weld::JointExitBuilder * GetJointExitBuilder
            (
                int row /** row of cell */
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
