//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MBD_WebRuleInstanceStringInput.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/MBD_WebRuleInstanceInput.hxx>
#include <NXOpen/libmbdopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MBD
    {
        class WebRuleInstanceStringInput;
    }
    namespace MBD
    {
        class WebRuleInstanceInput;
    }
    namespace MBD
    {
        class _WebRuleInstanceStringInputBuilder;
        class WebRuleInstanceStringInputImpl;

        /// \cond NX_NO_DOC 
        /** Represents a @link NXOpen::MBD::WebRuleInstanceStringInput NXOpen::MBD::WebRuleInstanceStringInput@endlink   <br>   <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class MBDOPENCPPEXPORT  WebRuleInstanceStringInput : public NXOpen::MBD::WebRuleInstanceInput
        {
            private: WebRuleInstanceStringInputImpl * m_webruleinstancestringinput_impl;
            private: friend class  _WebRuleInstanceStringInputBuilder;
            protected: WebRuleInstanceStringInput();
            public: ~WebRuleInstanceStringInput();

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: bool IsMultiLine
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: std::vector<NXString> GetValues
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: void SetValues
            (
                std::vector<NXString> & inputValues /** inputvalues */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
