//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MechanicalRouting_SpoolDelimiterBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Routing_RouteObjectCollector.hxx>
#include <NXOpen/libnxopencpp_mechanicalrouting_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MechanicalRouting
    {
        class SpoolDelimiterBuilder;
    }
    class Builder;
    namespace Routing
    {
        class RouteObjectCollector;
    }
    namespace MechanicalRouting
    {
        class _SpoolDelimiterBuilderBuilder;
        class SpoolDelimiterBuilderImpl;
        /** Builder for specifying delimiters for spools from Routing assemblies.
             <br> To create a new instance of this class, use @link NXOpen::MechanicalRouting::BuilderFactory::CreateSpoolDelimiterBuilder  NXOpen::MechanicalRouting::BuilderFactory::CreateSpoolDelimiterBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_MECHANICALROUTINGEXPORT  SpoolDelimiterBuilder : public NXOpen::Builder
        {
            private: SpoolDelimiterBuilderImpl * m_spooldelimiterbuilder_impl;
            private: friend class  _SpoolDelimiterBuilderBuilder;
            protected: SpoolDelimiterBuilder();
            public: ~SpoolDelimiterBuilder();
            /**Returns  the @link NXOpen::Routing::RouteObjectCollector NXOpen::Routing::RouteObjectCollector@endlink  used to collect the components for delimiting spools 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : routing_advanced ("Routing Advanced") OR routing_pipetube ("Routing Piping and Tubing") OR routing_hvac ("Routing HVAC") */
            public: NXOpen::Routing::RouteObjectCollector * FittingComponents
            (
            );
            /**Returns  the @link NXOpen::Routing::RouteObjectCollector NXOpen::Routing::RouteObjectCollector@endlink  used to collect ports to set as spool delimiters 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : routing_advanced ("Routing Advanced") OR routing_pipetube ("Routing Piping and Tubing") OR routing_hvac ("Routing HVAC") */
            public: NXOpen::Routing::RouteObjectCollector * PortsToSetAsDelimiters
            (
            );
            /**Returns  the @link NXOpen::Routing::RouteObjectCollector NXOpen::Routing::RouteObjectCollector@endlink  used to collect ports to unset as spool delimiters 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : routing_advanced ("Routing Advanced") OR routing_pipetube ("Routing Piping and Tubing") OR routing_hvac ("Routing HVAC") */
            public: NXOpen::Routing::RouteObjectCollector * PortsToUnsetAsDelimiters
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
