//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Routing_Electrical_SplicePoint.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/libnxopencpp_routing_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Routing
    {
        namespace Electrical
        {
            class SplicePoint;
        }
    }
    namespace Features
    {
        class Feature;
    }
    class Point;
    namespace Routing
    {
        namespace Electrical
        {
            class ConnectorDevice;
        }
    }
    namespace Routing
    {
        namespace Electrical
        {
            class _SplicePointBuilder;
            class SplicePointImpl;
            /** Represents a @link NXOpen::Routing::Electrical::SplicePoint NXOpen::Routing::Electrical::SplicePoint@endlink .  <br> To create or edit an instance of this class, use @link NXOpen::Routing::Electrical::SplicePositionBuilder  NXOpen::Routing::Electrical::SplicePositionBuilder @endlink  <br> 
             <br>  Created in NX2306.0.0.  <br>  
            */
            class NXOPENCPP_ROUTINGEXPORT  SplicePoint : public NXOpen::Point
            {
                private: SplicePointImpl * m_splicepoint_impl;
                private: friend class  _SplicePointBuilder;
                protected: SplicePoint();
                public: ~SplicePoint();
                /**Returns  the name of this splice point. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : routing_advanced ("Routing Advanced") */
                public: NXString Name
                (
                );
                /**Returns  the additional length required for a wire using this splice point. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : routing_advanced ("Routing Advanced") */
                public: double AdditionalLength
                (
                );
                /**Returns  the sphere feature that represents this splice point. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : routing_advanced ("Routing Advanced") */
                public: NXOpen::Features::Feature * SphereFeature
                (
                );
                /**Returns  the @link Routing::Electrical::ConnectorDevice Routing::Electrical::ConnectorDevice@endlink  to which this splice is assigned.
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : routing_advanced ("Routing Advanced") */
                public: NXOpen::Routing::Electrical::ConnectorDevice * ConnectorDevice
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
