//--------------------------------------------------------------------------
// Copyright 2024 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Schematic_Mechanical_Branch.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Schematic_Model_BaseObject.hxx>
#include <NXOpen/Schematic_Model_BaseObject.hxx>
#include <NXOpen/libnxopencpp_schematic_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Schematic
    {
        namespace Mechanical
        {
            class Branch;
        }
    }
    namespace Schematic
    {
        namespace Model
        {
            class BaseObject;
        }
    }
    namespace Schematic
    {
        namespace Mechanical
        {
            class _BranchBuilder;
            class BranchImpl;
            /** Represents the Branch class.  <br> Instance of this can not directly created.  <br> 
             <br>  Created in NX2206.0.0.  <br>  
            */
            class NXOPENCPP_SCHEMATICEXPORT  Branch : public NXOpen::Schematic::Model::BaseObject
            {
                private: BranchImpl * m_branch_impl;
                private: friend class  _BranchBuilder;
                protected: Branch();
                public: ~Branch();
                /** Gets the ordered objects in the branch.
                 <br>  Created in NX2312.0.0.  <br>  
                 <br> License requirements : None */
                public: void GetOrderedObjects
                (
                    std::vector<NXOpen::Schematic::Model::BaseObject *> & objs /** the collection of ordered objects except direct connections in the branch. */
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
