//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_DraftingSurfaceFinishSymbol.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_BaseSurfaceFinishSymbol.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Annotations
    {
        class DraftingSurfaceFinishSymbol;
    }
    namespace Annotations
    {
        class BaseSurfaceFinishSymbol;
    }
    namespace Annotations
    {
        class _DraftingSurfaceFinishSymbolBuilder;
        class DraftingSurfaceFinishSymbolImpl;

        /// \cond NX_NO_DOC 
        /** Represents Drafting Surface Finish Symbol  <br> To create or edit an instance of this class, use @link NXOpen::Annotations::DraftingSurfaceFinishSymbolBuilder  NXOpen::Annotations::DraftingSurfaceFinishSymbolBuilder @endlink  <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class NXOPENCPP_ANNOTATIONSEXPORT  DraftingSurfaceFinishSymbol : public NXOpen::Annotations::BaseSurfaceFinishSymbol
        {
            private: DraftingSurfaceFinishSymbolImpl * m_draftingsurfacefinishsymbol_impl;
            private: friend class  _DraftingSurfaceFinishSymbolBuilder;
            protected: DraftingSurfaceFinishSymbol();
            public: ~DraftingSurfaceFinishSymbol();
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
