//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Assemblies_ProductInterface_Collection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Assemblies_ProductInterface_ObjectBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_assemblies_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Assemblies
    {
        namespace ProductInterface
        {
            class Collection;
        }
    }
    class Part;
    namespace Assemblies
    {
        namespace ProductInterface
        {
            class InterfaceObject;
        }
    }
    namespace Assemblies
    {
        namespace ProductInterface
        {
            class ObjectBuilder;
        }
    }
    namespace Assemblies
    {
        namespace ProductInterface
        {
            class PropertyBuilder;
        }
    }
    class NXObject;
    class TaggedObject;
    namespace Assemblies
    {
        namespace ProductInterface
        {
            class CollectionImpl;
            /** This class represents the collection of product interface objects  <br> To obtain an instance of this class, refer to @link NXOpen::Part  NXOpen::Part @endlink  <br> 
             <br>  Created in NX5.0.0.  <br>  
            */
            class NXOPENCPP_ASSEMBLIESEXPORT  Collection
            {
                private: CollectionImpl * m_collection_impl;
                private: NXOpen::Part* m_owner;
                /// \cond NX_NO_DOC 
                public: explicit Collection(NXOpen::Part *owner);


                /// \endcond 
                public: 
                /**Returns the tag of this object.  */
                tag_t Tag() const; 
                public: ~Collection();
                /** Create Product Interface Object Builder 
                 <br>  @deprecated Deprecated in NX11.0.1.  Please use @link NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithVersion NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithVersion@endlink  instead. <br>  

                 <br>  Created in NX5.0.0.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX11.0.1.  Please use NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithVersion instead.") NXOpen::Assemblies::ProductInterface::ObjectBuilder * CreateObjectBuilder
                (
                );
                /** Create Product Interface Object Builder with version
                 <br>  @deprecated Deprecated in NX1872.0.0.  Please use @link NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithBuilderVersion NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithBuilderVersion@endlink  instead. <br>  

                 <br>  Created in NX11.0.1.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX1872.0.0.  Please use NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithBuilderVersion instead.") NXOpen::Assemblies::ProductInterface::ObjectBuilder * CreateObjectBuilderWithVersion
                (
                    int version /** Please see the definition at @link NXOpen::Assemblies::ProductInterface::ObjectBuilder::BuilderVersion NXOpen::Assemblies::ProductInterface::ObjectBuilder::BuilderVersion@endlink  */
                );
                /** Create Product Interface Object Builder with @link NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithBuilderVersion NXOpen::Assemblies::ProductInterface::Collection::CreateObjectBuilderWithBuilderVersion@endlink 
                 <br>  Created in NX1872.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Assemblies::ProductInterface::ObjectBuilder * CreateObjectBuilderWithBuilderVersion
                (
                    NXOpen::Assemblies::ProductInterface::ObjectBuilder::BuilderVersion version /** version */ 
                );
                /** Create Product Interface Property Builder 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Assemblies::ProductInterface::PropertyBuilder * CreatePropertyBuilder
                (
                );
                /** Find the Product Interface Object with input name  @return  Product Interface Object with this identifier 
                 <br>  Created in NX5.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXObject * FindObject
                (
                    const NXString & journalIdentifier /** Identifier of the product interface object you want */
                );
                /** Find the Product Interface Object with input name  @return  Product Interface Object with this identifier 
                 <br>  Created in NX5.0.0.  <br>  
                 <br> License requirements : None */
                NXOpen::NXObject * FindObject
                (
                    const char * journalIdentifier /** Identifier of the product interface object you want */
                );
                /** Returns all the product interface objects in the part  @return  product interface objects in the part 
                 <br>  Created in NX10.0.2.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXOpen::Assemblies::ProductInterface::InterfaceObject *> GetProductInterfaces
                (
                );
                /** Creates the Product Interface Group in the part 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::TaggedObject * NewGroup
                (
                );
                /** Rename the Product Interface Group 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void RenameGroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ ,
                    const NXString & groupName /** groupname */ 
                );
                /** Rename the Product Interface Group 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                void RenameGroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ ,
                    const char * groupName /** groupname */ 
                );
                /** Return the Product Interface Group name 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString GetGroupName
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ 
                );
                /** Move the member to the Product Interface Group. It will removed from the old group and added to the new group.
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void MoveMemberToGroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ ,
                    NXOpen::TaggedObject * memberToMove /** membertomove */ 
                );
                /** Remove the member from the Product Interface Group. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void RemoveMemberFromGroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ ,
                    NXOpen::TaggedObject * memberToRemove /** membertoremove */ 
                );
                /** Ungroup the Product Interface Group. This will delete the group and members will be moved to the parent group. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void Ungroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ 
                );
                /** Delete the Product Interface Group. 
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void DeleteGroup
                (
                    NXOpen::TaggedObject * prodIntGroup /** prodintgroup */ ,
                    bool deleteWithMembers /** deletewithmembers */ 
                );
                /** Add the member to the Product Interface Group. It will not be removed from any of the existing group.
                 <br>  Created in NX2306.0.0.  <br>  
                 <br> License requirements : None */
                public: void AddMemberToGroups
                (
                    NXOpen::TaggedObject * productInterfaceObject /** productinterfaceobject */ ,
                    const std::vector<NXOpen::TaggedObject *> & selectedGroups /** items in list */
                );
            }; //lint !e1712 default constructor not defined for class  

        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
