//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Assemblies_LabelModelingComponentBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_assemblies_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Assemblies
    {
        class LabelModelingComponentBuilder;
    }
    class Builder;
    class SelectDisplayableObjectList;
    namespace Assemblies
    {
        class _LabelModelingComponentBuilderBuilder;
        class LabelModelingComponentBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Represents a @link NXOpen::Assemblies::LabelModelingComponentBuilder NXOpen::Assemblies::LabelModelingComponentBuilder@endlink .  <br> To create a new instance of this class, use @link NXOpen::Assemblies::AssemblyManager::CreateLabelModelingComponentBuilder  NXOpen::Assemblies::AssemblyManager::CreateLabelModelingComponentBuilder @endlink  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class NXOPENCPP_ASSEMBLIESEXPORT  LabelModelingComponentBuilder : public NXOpen::Builder
        {
            private: LabelModelingComponentBuilderImpl * m_labelmodelingcomponentbuilder_impl;
            private: friend class  _LabelModelingComponentBuilderBuilder;
            protected: LabelModelingComponentBuilder();
            public: ~LabelModelingComponentBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectDisplayableObjectList * Components
            (
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
