//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_Connections_INodalTargetCenterOption.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_Connections_Types.hxx>
#include <NXOpen/INXObject.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        namespace Connections
        {
            class INodalTargetCenterOption;
        }
    }
    class INXObject;
    namespace CAE
    {
        namespace Connections
        {
            /**  @brief  This class represents an Interface to the Nodal Target Center Option.  

              
             <br>  Created in NX1847.0.0.  <br>  
            */
            class NXOPENCPP_CAEEXPORT  INodalTargetCenterOption : public virtual NXOpen::INXObject
            {
                public: virtual ~INodalTargetCenterOption() {}
                /**Returns  the target center type 
                 <br>  Created in NX1899.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual NXOpen::CAE::Connections::NodalTargetCenterType CenterType
                (
                ) = 0;
                /**Sets  the target center type 
                 <br>  Created in NX1899.0.0.  <br>  
                 <br> License requirements : nx_masterfem ("Finite Element Modeling") */
                public: virtual void SetCenterType
                (
                    NXOpen::CAE::Connections::NodalTargetCenterType centerType /** centertype */ 
                ) = 0;
                /** Check if center type is allowed 
                 <br>  Created in NX1899.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual bool IsCoincidentCenterTypeAllowed
                (
                ) = 0;
                /** Get available center types
                 <br>  Created in NX2206.0.0.  <br>  
                 <br> License requirements : None */
                public: virtual void GetAvailableTargetCenterTypes
                (
                    std::vector<NXOpen::CAE::Connections::NodalTargetCenterType> & types /** types */ 
                ) = 0;
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
