//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAM_HoleMakingNcmTransfer.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAM_NcmTransfer.hxx>
#include <NXOpen/libnxopencpp_cam_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAM
    {
        class HoleMakingNcmTransfer;
    }
    namespace CAM
    {
        class InheritableToolDepBuilder;
    }
    namespace CAM
    {
        class NcmTransfer;
    }
    namespace CAM
    {
        class _HoleMakingNcmTransferBuilder;
        class HoleMakingNcmTransferImpl;
        /**
            Represents a @link NXOpen::CAM::HoleMakingNcmTransfer NXOpen::CAM::HoleMakingNcmTransfer@endlink 
            
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_CAMEXPORT  HoleMakingNcmTransfer : public NXOpen::CAM::NcmTransfer
        {
            /** Available types for the secondary transfer between features in hole making */
            public: enum SecondaryTransferTypes
            {
                SecondaryTransferTypesClearance/** tool axis to clearance */,
                SecondaryTransferTypesShortestToClearance/** shortest to clearance */,
                SecondaryTransferTypesCutPlaneToClearance/** cut plane to clearance */,
                SecondaryTransferTypesLowestTiltedPlane/** lowest tilted plane */,
                SecondaryTransferTypesRelativeTiltedPlane/** relative tilted plane */
            };

            private: HoleMakingNcmTransferImpl * m_holemakingncmtransfer_impl;
            private: friend class  _HoleMakingNcmTransferBuilder;
            protected: HoleMakingNcmTransfer();
            public: ~HoleMakingNcmTransfer();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAM::HoleMakingNcmTransfer::SecondaryTransferTypes SecondaryType
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : cam_base ("CAM BASE") */
            public: void SetSecondaryType
            (
                NXOpen::CAM::HoleMakingNcmTransfer::SecondaryTransferTypes transferType /** transfertype */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAM::InheritableToolDepBuilder * SecondarySafeDistanceBuilder
            (
            );

            /// \endcond 
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
