//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DesignSimulation_ViewXygraphBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DesignSimulation_OptimizationConstraint.hxx>
#include <NXOpen/DesignSimulation_Study.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_designsimulation_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DesignSimulation
    {
        class ViewXygraphBuilder;
    }
    class Builder;
    namespace DesignSimulation
    {
        class OptimizationConstraint;
    }
    namespace DesignSimulation
    {
        class Study;
    }
    namespace DesignSimulation
    {
        class _ViewXygraphBuilderBuilder;
        class ViewXygraphBuilderImpl;
        /**
            Represents a builder to draw xygraph for optimization objective or optimization constraint
             <br> To create a new instance of this class, use @link NXOpen::DesignSimulation::PostManager::CreateViewXygraphBuilder  NXOpen::DesignSimulation::PostManager::CreateViewXygraphBuilder @endlink  <br> 
         <br>  Created in NX2206.0.0.  <br>  
        */
        class NXOPENCPP_DESIGNSIMULATIONEXPORT  ViewXygraphBuilder : public NXOpen::Builder
        {
            /** Xygraph content option*/
            public: enum ContentOption
            {
                ContentOptionOptimizationObjective/** optimization objective */ ,
                ContentOptionOptimizationConstraint/** optimization constraint */ 
            };

            private: ViewXygraphBuilderImpl * m_viewxygraphbuilder_impl;
            private: friend class  _ViewXygraphBuilderBuilder;
            protected: ViewXygraphBuilder();
            public: ~ViewXygraphBuilder();
            /**Returns  the xygraph content. 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOption XygraphContent
            (
            );
            /**Sets  the xygraph content. 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            public: void SetXygraphContent
            (
                NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOption xygraphContent /** xygraphcontent */ 
            );
            /**Returns  the target study. 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::Study * Study
            (
            );
            /**Sets  the target study. 
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            public: void SetStudy
            (
                NXOpen::DesignSimulation::Study * study /** study */ 
            );
            /**Returns  the optimization constraint.
                    
                    This property needs to be set when @link NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent@endlink 
                    is @link NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint@endlink .
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::DesignSimulation::OptimizationConstraint * OptimizationConstraint
            (
            );
            /**Sets  the optimization constraint.
                    
                    This property needs to be set when @link NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent@endlink 
                    is @link NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint@endlink .
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            public: void SetOptimizationConstraint
            (
                NXOpen::DesignSimulation::OptimizationConstraint * constraint /** constraint */ 
            );
            /**Returns  the corresponding subcase name for optimization constraint.
                    
                    This property needs to be set when @link NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent@endlink 
                    is @link NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint@endlink .
                    For following constraints, their iterative results are independent on subcase, the subcase name should be set as empty.
                    <ol>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit@endlink 
                    </li>
                    </ol>
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: NXString SubcaseName
            (
            );
            /**Sets  the corresponding subcase name for optimization constraint.
                    
                    This property needs to be set when @link NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent@endlink 
                    is @link NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint@endlink .
                    For following constraints, their iterative results are independent on subcase, the subcase name should be set as empty.
                    <ol>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit@endlink 
                    </li>
                    </ol>
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            public: void SetSubcaseName
            (
                const NXString & subcaseName /** subcasename */ 
            );
            /**Sets  the corresponding subcase name for optimization constraint.
                    
                    This property needs to be set when @link NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent NXOpen::DesignSimulation::ViewXygraphBuilder::XygraphContent@endlink 
                    is @link NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint NXOpen::DesignSimulation::ViewXygraphBuilder::ContentOptionOptimizationConstraint@endlink .
                    For following constraints, their iterative results are independent on subcase, the subcase name should be set as empty.
                    <ol>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMassTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumMassLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeFirstFlexibleModeTarget@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMinimumFirstFlexibleModeLimit@endlink 
                    </li>
                    <li>
                    @link NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit NXOpen::DesignSimulation::OptimizationConstraintBuilder::ConstraintTypeMaximumFirstFlexibleModeLimit@endlink 
                    </li>
                    </ol>
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            void SetSubcaseName
            (
                const char * subcaseName /** subcasename */ 
            );
            /**Returns  the ID of target window device on which XY graph is displayed.
                    
                    The window device ID is returned when calling @link NXOpen::CAE::Xyplot::WindowManager::NewWindow NXOpen::CAE::Xyplot::WindowManager::NewWindow@endlink 
                    to create a new graphics window. To get existing window device IDs, call @link NXOpen::CAE::Xyplot::WindowManager::GetWindows NXOpen::CAE::Xyplot::WindowManager::GetWindows@endlink .
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : None */
            public: int TargetWindowDevice
            (
            );
            /**Sets  the ID of target window device on which XY graph is displayed.
                    
                    The window device ID is returned when calling @link NXOpen::CAE::Xyplot::WindowManager::NewWindow NXOpen::CAE::Xyplot::WindowManager::NewWindow@endlink 
                    to create a new graphics window. To get existing window device IDs, call @link NXOpen::CAE::Xyplot::WindowManager::GetWindows NXOpen::CAE::Xyplot::WindowManager::GetWindows@endlink .
                    
                    
             <br>  Created in NX2206.0.0.  <br>  
             <br> License requirements : des_top_opt ("Topology Optimization for Designers") OR sc_des_topol_opt (" Topology Optimization for Designers") */
            public: void SetTargetWindowDevice
            (
                int winDevice /** windevice */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
