//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DesignSimulation_AnalysisReportSettings.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/libnxopencpp_designsimulation_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace DesignSimulation
    {
        class AnalysisReportSettings;
    }
    class NXObject;
    namespace DesignSimulation
    {
        class _AnalysisReportSettingsBuilder;
        class AnalysisReportSettingsImpl;
        /** Represents a Design Simulation Analysis Report Settings  <br> To create or edit an instance of this class, use @link NXOpen::DesignSimulation::AnalysisReportBuilder  NXOpen::DesignSimulation::AnalysisReportBuilder @endlink  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_DESIGNSIMULATIONEXPORT  AnalysisReportSettings : public NXOpen::NXObject
        {
            private: AnalysisReportSettingsImpl * m_analysisreportsettings_impl;
            private: friend class  _AnalysisReportSettingsBuilder;
            protected: AnalysisReportSettings();
            public: ~AnalysisReportSettings();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
