//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     EclassStandard_EclassKeyLovProperty.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/EclassStandard_EclassObject.hxx>
#include <NXOpen/libeclassstandardopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace EclassStandard
    {
        class EclassKeyLovProperty;
    }
    namespace EclassStandard
    {
        class EclassObject;
    }
    namespace EclassStandard
    {
        class _EclassKeyLovPropertyBuilder;
        class EclassKeyLovPropertyImpl;

        /// \cond NX_NO_DOC 
        /** Represents a @link NXOpen::EclassStandard::EclassKeyLovProperty NXOpen::EclassStandard::EclassKeyLovProperty@endlink   <br> Use @link NXOpen::EclassStandard::EclassManager::CreateEclassObject NXOpen::EclassStandard::EclassManager::CreateEclassObject@endlink  to get the instance of this class.  <br> 
         <br>  Created in NX2306.0.0.  <br>  
        */
        class ECLASSSTANDARDOPENCPPEXPORT  EclassKeyLovProperty : public NXOpen::EclassStandard::EclassObject
        {
            private: EclassKeyLovPropertyImpl * m_eclasskeylovproperty_impl;
            private: friend class  _EclassKeyLovPropertyBuilder;
            protected: EclassKeyLovProperty();
            public: ~EclassKeyLovProperty();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: int KeyLovIndex
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetKeyLovIndex
            (
                int index /** index */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXString ReferenceKeylovIrdi
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: void SetReferenceKeylovIrdi
            (
                const NXString & refKeylovId /** ref keylov id */ 
            );
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            void SetReferenceKeylovIrdi
            (
                const char * refKeylovId /** ref keylov id */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
