//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_AECDesign_SectionFeatureSpreadsheetBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_Industry_SectionFeatureSpreadsheetBuilder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace AECDesign
        {
            class SectionFeatureSpreadsheetBuilder;
        }
    }
    namespace Features
    {
        namespace Industry
        {
            class SectionFeatureSpreadsheetBuilder;
        }
    }
    namespace Features
    {
        namespace AECDesign
        {
            class _SectionFeatureSpreadsheetBuilderBuilder;
            class SectionFeatureSpreadsheetBuilderImpl;
            /**
                    Represents a @link NXOpen::Features::AECDesign::SectionFeatureSpreadsheetBuilder NXOpen::Features::AECDesign::SectionFeatureSpreadsheetBuilder@endlink  builder. 
                    It is used to manage the data contained in the ship sketch based steel feature block.
                     <br> This class is sub-object of another builder, and cannot be directly instantiated.  <br> 
             <br>  Created in NX2212.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  SectionFeatureSpreadsheetBuilder : public NXOpen::Features::Industry::SectionFeatureSpreadsheetBuilder
            {
                private: SectionFeatureSpreadsheetBuilderImpl * m_sectionfeaturespreadsheetbuilder_impl;
                private: friend class  _SectionFeatureSpreadsheetBuilderBuilder;
                protected: SectionFeatureSpreadsheetBuilder();
                public: ~SectionFeatureSpreadsheetBuilder();
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
