//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ClipLattice2.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_BodyFeature.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class ClipLattice2;
    }
    namespace Features
    {
        class BodyFeature;
    }
    namespace Features
    {
        class _ClipLattice2Builder;
        class ClipLattice2Impl;
        /** Represents a clip lattice 2 feature  <br> To create or edit an instance of this class, use @link NXOpen::Features::ClipLattice2Builder  NXOpen::Features::ClipLattice2Builder @endlink  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  ClipLattice2 : public NXOpen::Features::BodyFeature
        {
            private: ClipLattice2Impl * m_cliplattice2_impl;
            private: friend class  _ClipLattice2Builder;
            protected: ClipLattice2();
            public: ~ClipLattice2();
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
