//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MBD_WebRuleInstanceInput.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libmbdopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MBD
    {
        class WebRuleInstanceInput;
    }
    namespace MBD
    {
        class _WebRuleInstanceInputBuilder;
        class WebRuleInstanceInputImpl;

        /// \cond NX_NO_DOC 
        /** Represents a @link NXOpen::MBD::WebRuleInstanceInput NXOpen::MBD::WebRuleInstanceInput@endlink   <br>   <br> 
         <br>  Created in NX2212.0.0.  <br>  
        */
        class MBDOPENCPPEXPORT  WebRuleInstanceInput : public NXOpen::TaggedObject
        {
            /** This is an internal API and can be changed at any time */

            /// \cond NX_NO_DOC 
            public: enum InputType
            {
                InputTypeBoolean/** boolean */ ,
                InputTypeDouble/** double */ ,
                InputTypeFolder/** folder */ ,
                InputTypeInteger/** integer */ ,
                InputTypeSelection/** selection */ ,
                InputTypeString/** string */ ,
                InputTypeEnum/** enum */ ,
                InputTypeColor/** color */ ,
                InputTypeUnsupported/** unsupported */ 
            };


            /// \endcond 
            private: WebRuleInstanceInputImpl * m_webruleinstanceinput_impl;
            private: friend class  _WebRuleInstanceInputBuilder;
            protected: WebRuleInstanceInput();
            public: ~WebRuleInstanceInput();

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::MBD::WebRuleInstanceInput::InputType GetInputType
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2212.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Name
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: bool IsRequired
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /** This is an internal API and can be changed at any time 
             <br>  Created in NX2306.0.0.  <br>  
             <br> License requirements : None */
            public: NXString GetInputNodeName
            (
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
