//--------------------------------------------------------------------------
// Copyright 2023 Siemens
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     PartMfg_ToleranceValidationBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#pragma once

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libpartmfgopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace PartMfg
    {
        class ToleranceValidationBuilder;
    }
    class Builder;
    namespace PartMfg
    {
        class _ToleranceValidationBuilderBuilder;
        class ToleranceValidationBuilderImpl;

        /// \cond NX_NO_DOC 
        /** Builder class  <br> To create a new instance of this class, use @link NXOpen::PartMfg::ToleranceCollection::CreateToleranceValidationBuilder  NXOpen::PartMfg::ToleranceCollection::CreateToleranceValidationBuilder @endlink  <br> 
         <br>  Created in NX2312.0.0.  <br>  
        */
        class PARTMFGOPENCPPEXPORT  ToleranceValidationBuilder : public NXOpen::Builder
        {
            private: ToleranceValidationBuilderImpl * m_tolerancevalidationbuilder_impl;
            private: friend class  _ToleranceValidationBuilderBuilder;
            protected: ToleranceValidationBuilder();
            public: ~ToleranceValidationBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int Method
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: void SetMethod
            (
                int method /** method */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int Maximum
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: void SetMaximum
            (
                int maximum /** maximum */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: int MaximumForKpc
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  This is an internal API and can be changed at any time 
             <br>  Created in NX2312.0.0.  <br>  
             <br> License requirements : None */
            public: void SetMaximumForKpc
            (
                int maximumForKpc /** maximumforkpc */ 
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
